/*
----------------------------
MetaDoom
Actor Definitions
Pinata Items
----------------------------
*/

Mixin Class MetaPinataZooper
{
	Actor zoopTarget;
	
	string validGrab;
	
	property CheckToGrab : validGrab;
	
	void ZoopThink()
	{
		if ( bNOSECTOR ) return;
		
		if ( GetAge() < 35 ) return;
		
		if ( level.maptime % 2 == 0 )
		{
			for ( int i = 0; i < MAXPLAYERS; i++ )
			{
				if ( players[i].mo && Distance3D(players[i].mo) <= 192 && CanZoop(players[i].mo) )
				{
					bNOGRAVITY = true;
					zoopTarget = players[i].mo;
					SetStateLabel("Seek");
					return;
				}
			}
		}
		
		if ( zoopTarget && CanZoop(zoopTarget) )
		{
			Vector3 diff = level.Vec3Diff(pos, zoopTarget.pos+(0,0,zoopTarget.height/2));
			Vector3 goDir = diff.Unit() * 24;
			vel = goDir;
			if ( diff.Length() <= 64 )
			{
				Touch(zoopTarget);
			}
		}
		else
		{
			bNOGRAVITY = false;
		}
	}
	
	bool CanZoop(Actor grabber)
	{
		if ( validGrab != "" )
		{
			let inv = grabber.FindInventory(validGrab);
			if ( inv && inv.Amount >= inv.MaxAmount )
			{
				return false;
			}
		}
		return true;
	}
	
	action State A_DoZoop()
	{
		if ( !(invoker.zoopTarget && invoker.CanZoop(invoker.zoopTarget)) )
		{
			return invoker.resolveState("Spawn");
		}
		return invoker.resolveState(null);
	}
	
	States
	{
		Seek:
			"----" A 1 A_DoZoop();
			Loop;
	}
}

// Doom 2016-style "pinata" pickups - contextual icons that give you stuff.

// This one fades away!
class MetaHealthPinata : Health
{
	Default
	{
		-COUNTITEM
		//+INVENTORY.ALWAYSPICKUP
		Inventory.Amount 2;
		Inventory.PickupMessage "$GOTPINATAHEALTH";
		Inventory.PickupSound "items/health/shard";
		TeleFogSourceType "MetaItemFog";
		TeleFogDestType "MetaItemFog";
		scale 0.75;
		RenderStyle "Add";
	}
	
	int lifespan;
	
	States
	{
		Spawn:
			PINH A 0;
			PINH A 0 { lifespan = 0; }
		Sit:
			PINH A 4 bright;
			PINH A 4 { lifespan++; }
			PINH A 0 A_JumpIf(lifespan >= 12, "Fade");
			loop;
		Fade:
			PINH A 4 bright A_FadeOut(0.2);
			PINH A 4 A_FadeOut(0.2);
			loop;
	}
	
	mixin MetaPinataZooper;
	
	override void Tick()
	{
		super.Tick();
		ZoopThink();
	}
	
	override bool TryPickup(in out Actor toucher)
    {
		if (toucher == target)
			return false;
		else
			bALWAYSPICKUP = true;
			return Super.TryPickup(toucher);
    }
}

// This one, not so much.
class MetaHealthPinataPerm : MetaHealthPinata
{
	Default
	{
		Inventory.Amount 4;
	}
	
	States
	{
	Spawn:
		PINH A 4 bright;
		PINH A 4;
		loop;
	}
}	

class MetaArmorPinata : BasicArmorBonus
{
	Default
	{
		-COUNTITEM
		+INVENTORY.ALWAYSPICKUP
		Armor.Savepercent 33.335;
		Armor.Saveamount 4;
		Armor.Maxsaveamount 100;
		Inventory.PickupSound "items/armor/shard";
		Inventory.PickupMessage "$GOTPINATAARMOR";
		TeleFogSourceType "MetaItemFog";
		TeleFogDestType "MetaItemFog";
		scale 0.75;
		RenderStyle "Add";
	}
	
	mixin MetaPinataZooper;
	
	override void Tick()
	{
		super.Tick();
		ZoopThink();
	}
	
	States
	{
		Spawn:
			PINA A 4 bright;
			PINA A 4;
			loop;
	}
}

class MetaArmorPinataFade : BasicArmorBonus
{
	Default
	{
		-COUNTITEM
		+INVENTORY.ALWAYSPICKUP
		Armor.Savepercent 33.335;
		Armor.Saveamount 4;
		Armor.Maxsaveamount 100;
		Inventory.PickupSound "items/armor/shard";
		Inventory.PickupMessage "$GOTPINATAARMOR";
		TeleFogSourceType "MetaItemFog";
		TeleFogDestType "MetaItemFog";
		scale 0.75;
		RenderStyle "Add";
	}
	
	int lifespan;
	
	mixin MetaPinataZooper;
	
	override void Tick()
	{
		super.Tick();
		ZoopThink();
	}
	
	States
	{
		Spawn:
			PINA A 0;
			PINA A 0 { lifespan = 0; }
		Sit:
			PINA A 4 bright;
			PINA A 4 { lifespan++; }
			PINA A 0 A_JumpIf(lifespan >= 12, "Fade");
			loop;
		Fade:
			PINA A 4 bright A_FadeOut(0.2);
			PINA A 4 A_FadeOut(0.2);
			loop;
	}
}

class MetaPinataClip : Clip
{
	Default
	{
		Inventory.PickupMessage "$GOTPINATAAMMO_CLIP";
		Inventory.Amount 5;
		TeleFogSourceType "MetaItemFog";
		TeleFogDestType "MetaItemFog";
		inventory.pickupsound "items/clip";
		scale 0.75;
		RenderStyle "Add";
		self.CheckToGrab "Clip";
	}
	
	mixin MetaPinataZooper;
	
	override void Tick()
	{
		super.Tick();
		ZoopThink();
	}
	
	States
	{
	Spawn:
		PINM A 4 bright;
		PINM A 4;
		loop;
	}
}

class MetaPinataShell : Shell
{
	Default
	{
		Inventory.PickupMessage "$GOTPINATAAMMO_SHELL";
		Inventory.Amount 2;
		inventory.pickupsound "items/shell";
		TeleFogSourceType "MetaItemFog";
		TeleFogDestType "MetaItemFog";
		scale 0.75;
		RenderStyle "Add";
		self.CheckToGrab "Shell";
	}
	
	mixin MetaPinataZooper;
	
	override void Tick()
	{
		super.Tick();
		ZoopThink();
	}
	
	States
	{
	Spawn:
		PINM B 4 bright;
		PINM B 4;
		loop;
	}
}

class MetaPinataRocket : RocketAmmo
{
	Default
	{
		Inventory.PickupMessage "$GOTPINATAAMMO_ROCKET";
		Inventory.Amount 2;
		inventory.pickupsound "items/rocket";
		TeleFogSourceType "MetaItemFog";
		TeleFogDestType "MetaItemFog";
		scale 0.75;
		RenderStyle "Add";
		self.CheckToGrab "RocketAmmo";
	}
	
	mixin MetaPinataZooper;
	
	override void Tick()
	{
		super.Tick();
		ZoopThink();
	}
	
	States
	{
	Spawn:
		PINM C 4 bright;
		PINM C 4;
		loop;
	}
}

class MetaPinataCell : Cell
{
	Default
	{
		Inventory.PickupMessage "$GOTPINATAAMMO_CELL";
		Inventory.Amount 10;
		inventory.pickupsound "items/cell";
		TeleFogSourceType "MetaItemFog";
		TeleFogDestType "MetaItemFog";
		scale 0.75;
		RenderStyle "Add";
		self.CheckToGrab "Cell";
	}
	
	mixin MetaPinataZooper;
	
	override void Tick()
	{
		super.Tick();
		ZoopThink();
	}
	
	States
	{
	Spawn:
		PINM D 4 bright;
		PINM D 4;
		loop;
	}
}