/*
----------------------------
MetaDoom
Actor Definitions
Grenade Launcher
----------------------------
*/

class MetaGrenadeLauncherPickup : WeaponGiver
{
	Default
	{
		DropItem "MetaGrenadeLauncher";
		Inventory.PickupMessage "$GOTGRENLAUN";
		Inventory.PickupSound "weapons/grenadelauncher/get";
	}
	
	States
	{
	Spawn:
		GLAU Z 0;
		GLAU Z 0 { bDROPPED = 0; }
		GLAU Z -1;
		Stop;
	}
}

class MetaGrenadeLauncher : MetaDoomWeapon
{
	Default
	{
		Weapon.SelectionOrder 2500;
		Weapon.AmmoUse1 1;
		Weapon.AmmoUse2 3;
		Weapon.AmmoGive 4;
		Weapon.AmmoType1 "RocketAmmo";
		Weapon.AmmoType2 "RocketAmmo";
		+WEAPON.NOAUTOFIRE
		Inventory.PickupMessage "$GOTGRENLAUN";
		Tag "$TAGGRENLAUN";
		Inventory.PickupSound "weapons/grenadelauncher/get";
		+WEAPON.NOALERT
		+WEAPON.ALT_AMMO_OPTIONAL
		Weapon.BobRangeX 0.5;
		Weapon.BobRangey 0.75;
		Weapon.UpSound "weapons/grenadelauncher/use";
		//$Category "Weapons/MetaDoom"
		//$Title "Grenade Launcher"
		//$NotAngled
		//$Color 14
	}
	
	action void A_MetaGrenadeRecoil()
	{
		let recoil = new("Meta_RecoilInfo");
		recoil.tics_in = 2;
		recoil.tics_out = 14;
		recoil.pitch = 3;
		recoil.roll_shake = 0.2;
		recoil.roll_speed = 42+random(-2,2);
		A_MetaRecoil(recoil);
	}
	
	States
	{
	Ready:
		GLAU A 1 A_WeaponReady;
		"####" A 0 A_JumpIfInventory("MeleePunch", 1, "MeleePunch");
		Loop;
	Deselect:
		GLAU A 0 A_JumpIf(health <= 0, "DeadDude");
		GLAU A 0 A_PlaySound("weapons/swap");
	FinishDeselect:
		GLAU A 1 A_SmoothLower();
		Loop;
	Select:
		GLAU A 0 A_OverlayScale(PSP_WEAPON, 1, 1);
		GLAU A 1 A_SmoothRaise();
		loop;
	Fire:
		GLAU A 0;
		GLAU A 3 bright
		{
			A_FireProjectile("GrenadeLauncherProj", pitch: -12);
			A_PlaySound ("weapons/grenadelauncher/fire", CHAN_WEAPON);
			
			if (CountInv("PowerMetaDamage") > 0)
			{
				A_PlaySound("powerups/quad/use", CHAN_5);
			}
			
			A_GunFlash();
			A_AlertMonsters();
			A_Overlay(14, "Overlay.Fire");
			A_MetaGrenadeRecoil();
		}
		GLAU AAAAA 2;
		GLAU BCDEA 2;
		GLAU A 2;
		GLAU A 0 A_Refire;
		Goto Ready;
	AltFire:
		GLAU A 0 A_JumpIfInventory("RocketAmmo",3,"GasShot");
		GLAU A 1 Offset(0,34) A_PlaySound("weapons/grenadelauncher/altdeny", CHAN_BODY);
		GLAU A 1 Offset(0,33);
		GLAU A 1 Offset(0,32);
		GLAU A 10;
		goto Ready;
	GasShot:
		GLAU B 0 A_GunFlash;
		GLAU A 3 bright
		{
			A_FireProjectile ("GasBombProj", pitch: -12);
			A_PlaySound ("weapons/grenadelauncher/altfire", CHAN_WEAPON);
			
			if (CountInv("PowerMetaDamage") > 0)
			{
				A_PlaySound("powerups/quad/use", CHAN_5);
			}
			
			A_GunFlash();
			A_AlertMonsters();
			A_Overlay(14, "Overlay.Fire");
			A_MetaGrenadeRecoil();
		}
		GLAU AAAAA 2;
		GLAU BCDEA 2;
		GLAU A 2;
		GLAU A 0 A_Refire;
		Goto Ready;
	Flash:
		GLAU FGH 2 BRIGHT A_Light1;
		GLAU I 2 BRIGHT A_Light2;
		Goto LightDone;
	Spawn:
		GLAU Z -1;
		Stop;
		
	Overlay.Fire:
		TNT1 B 1 { A_WeaponOffset(GetShake(),45,WOF_INTERPOLATE); }// A_SetPitch(pitch-2, SPF_INTERPOLATE); }
		TNT1 B 1 { A_WeaponOffset(GetShake()*3,53,WOF_INTERPOLATE); }// A_SetPitch(pitch-2, SPF_INTERPOLATE); }
		TNT1 B 1 A_WeaponOffset(GetShake()*3,56,WOF_INTERPOLATE);
		TNT1 C 1 { A_WeaponOffset(GetShake()*2,55,WOF_INTERPOLATE); }// A_SetPitch(pitch+1, SPF_INTERPOLATE); }
		TNT1 C 1 { A_WeaponOffset(GetShake()*2,52,WOF_INTERPOLATE); }// A_SetPitch(pitch+1, SPF_INTERPOLATE); }
		TNT1 C 1 { A_WeaponOffset(GetShake(),46,WOF_INTERPOLATE); }// A_SetPitch(pitch+1, SPF_INTERPOLATE); }
		TNT1 D 1 { A_WeaponOffset(GetShake(),45,WOF_INTERPOLATE); }// A_SetPitch(pitch+1, SPF_INTERPOLATE); }
		TNT1 D 1 A_WeaponOffset(0,42,WOF_INTERPOLATE);
		TNT1 D 1 A_WeaponOffset(0,38,WOF_INTERPOLATE);
		TNT1 A 1 A_WeaponOffset(0,36,WOF_INTERPOLATE);
		TNT1 A 1 A_WeaponOffset(0,34,WOF_INTERPOLATE);
		TNT1 A 1 A_WeaponOffset(0,33,WOF_INTERPOLATE);
		TNT1 A 1 A_WeaponOffset(0,32,WOF_INTERPOLATE);
		TNT1 A -1;
		stop;
	}
}

class GrenadeLauncherProj : Actor
{
	Default
	{
		+CANBOUNCEWATER
		Radius 8;
		Height 8;
		Speed 30;
		Damage 0;
		PROJECTILE;
		+RANDOMIZE
		-NOGRAVITY
		+ROLLSPRITE
		+ROLLCENTER
		+STRETCHPIXELS
		+BRIGHT
		BounceSound "weapons/grenadelauncher/bounce";
		+ALLOWBOUNCEONACTORS
		+BOUNCEONFLOORS
		+BOUNCEONCEILINGS
		+BOUNCEONWALLS
		+BOUNCEONACTORS
		Obituary "$OB_GRENLAUNCHER";
		//scale 0.5;
		//ReactionTime 60;	//Just over five seconds;
		Damagetype "Explosive";
	}
	
	int det_timer;
	
	const DET_TIME = 56;
	
	virtual int GrenDamage()
	{
		return 20;
	}
	
	override void Tick()
	{
		super.Tick();
		
		Vector3 diff = (prev - pos);
		int len = diff.Length();
		for ( int i = 0; i < len; i += 12 )
		{
			let p = Level.SpawnVisualThinker("MetaGrenadeLauncher_GrenadeTrail");
			if ( p )
			{
				p.pos = level.Vec3Offset(pos, diff.Unit() * i);
			}
		}
		
		if ( det_timer < DET_TIME )
		{
			det_timer += 1;
			if ( det_timer >= DET_TIME )
			{
				ExplodeMissile();
			}
		}
	}
	
	override int SpecialBounceHit(Actor bounceMobj, Line bounceLine, SecPlane bouncePlane)
	{
		if ( bounceMobj && bounceMobj.bShootable )
		{
			bounceMobj.DamageMobj(self, target, GrenDamage()*random(1,3), 'Explosive');
			A_StartSound(self.deathsound, CHAN_BODY);
			ExplodeMissile();
			return MHIT_DEFAULT;
		}
		
		if ( vel.Length() <= 3 )
		{
			SetStateLabel("BounceStop");
			vel *= 0;
			return MHIT_PASS;
		}
		
		switch ( random(1,4) )
		{
			case 1: SetStateLabel("Bounce1"); break;
			case 2: SetStateLabel("Bounce1"); break;
			case 3: SetStateLabel("Bounce2"); break;
			case 4: SetStateLabel("Flying"); break;
		}
		
		return MHIT_DEFAULT;
	}
	
	States
	{
	Spawn:
		TNT1 A 0;
		//TNT1 A 0 ThrustThingZ(0,16,0,1);
		TNT1 A 0
		{
			return ResolveState("Flying");
		}
		Wait;
	Flying:
		GBOM ABCDEFGH 2;// A_CountDown;
		loop;
	Bounce1:
		//"####" # 0 A_CountDown;
		"####" # 1 A_SetRoll((roll + 5));
		"####" # 1 A_SetRoll((roll + 5));
		"####" # 1 A_SetRoll((roll + 5));
		loop;
	Bounce2:
		//"####" # 0 A_CountDown;
		"####" # 1 A_SetRoll((roll - 5));
		"####" # 1 A_SetRoll((roll - 5));
		"####" # 1 A_SetRoll((roll - 5));
		loop;
	BounceStop:
		//"####" # 0 A_CountDown;
		"####" # -1;
		Stop;
	Death:
		TNT1 A 0 A_SpawnItemEx("GrenadeLauncherExplosion",0,0,24,0,0,0,0,SXF_TRANSFERPOINTERS);
		Stop;
	}
}

class GrenadeLauncherExplosion : MetaExplosion
{
	States
	{
	Spawn:
	EXPL A 0;
	EXPL A 2 BRIGHT
	{
		A_PlaySound("weapons/grenadelauncher/explode", CHAN_WEAPON);
		A_Explode();
		A_Quake (3,10,0,750,0);
		A_SpawnItem("Shockwave",0,0);
		
		if (pos.z <= (floorz + 64))
		{
			A_SpawnItem("ExplosionScorchMark",0,0);
		}
	}
	EXPL B 2 BRIGHT;
	EXPL C 2 BRIGHT;
	EXPL DEF 2;
	Stop;
	}
}

class GasBombProj : GrenadeLauncherProj
{
	Default
	{
		-BOUNCEONFLOORS
		BounceSound "weapons/grenadelauncher/bounce";
	}
	
	override int GrenDamage()
	{
		return 0;
	}
	
	States
	{
		Flying:
			GBOM IJKLMNOP 2;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItemEx("GasBombExplosion",0,0,24,0,0,0,0,SXF_TRANSFERPOINTERS);
			Stop;
	}
}

class GasBombExplosion : Actor
{
	Default
	{
		Radius 10;
		Height 10;
		Speed 5;
		PROJECTILE;
		+NOCLIP
		Decal "Scorch";
		Obituary "$OB_GRENLAUNCHER_GAS";
	}
	
	const GAS_TIME = 48;
	const GAS_RADIUS = 128;
	
	int gastimer;
	
	override void PostBeginPlay()
	{
		super.PostBeginPlay();
	}
	
	override void Tick()
	{
		super.Tick();
		
		offTick = !offTick;
		
		if ( !offTick ) return;
		
		playerOffTick = !playerOffTick;
		
		for ( int i = 0; i < 2; i++ )
		{
			let p = MetaGrenadeLauncher_GasCloud(Level.SpawnVisualThinker("MetaGrenadeLauncher_GasCloud"));
			if ( p )
			{
				p.angler = random(0,360)+(360/2.)*i;
				p.pos = pos;
			}
		}
		
		BlockThingsIterator it = BlockThingsIterator.Create(self, GAS_RADIUS);
		Actor mo;

		while ( it.Next() )
		{
			mo = it.thing;
			
			if ( !mo.bSHOOTABLE
				|| !mo.bSOLID
				|| mo.health <= 0 
				|| (Distance3D(mo) - mo.radius) > GAS_RADIUS
				|| !CheckSight(mo) )
			{
				continue;
			}
			
			bool isPlayer = (mo is "PlayerPawn");
			
			if ( isPlayer && !playerOffTick ) continue;
			
			mo.DamageMobj(self, target, isPlayer ? 3 : 6, 'PoisonCloud', DMG_THRUSTLESS, AngleTo(mo));
		}
		
		gastimer++;
		if ( gastimer >= GAS_TIME )
		{
			Destroy();
		}
	}
	
	bool offTick;
	bool playerOffTick;
	
	States
	{
	Spawn:
		EXPL A 0;
		EXPL A 2 BRIGHT
		{
			A_PlaySound("weapons/grenadelauncher/gasbomb", CHAN_WEAPON);
			A_Explode(32,128);
			A_Quake (3,10,0,750,0);
			
			if (pos.z <= (floorz + 64))
			{
				A_SpawnItem("ExplosionScorchMark",0,0);
			}
			
			/*A_SpawnItemEx("GasBombCloud",0,0,4,1,random(0,1),0,random(0,360));
			A_SpawnItemEx("GasBombCloud",0,0,4,1,random(0,1),0,random(0,360));
			A_SpawnItemEx("GasBombCloud",0,0,4,1,random(0,1),0,random(0,360));
			A_SpawnItemEx("GasBombCloud",0,0,4,1,random(0,1),0,random(0,360));*/
		}
		EXPL B 2 BRIGHT;
		EXPL C 2 BRIGHT;
		EXPL DEF 2;
		TNT1 A -1;
		Wait;
	}
}

class GasBombCloud : Actor
{
	Default
	{
		Radius 32;
		Height 32;
		Mass 0x7fffffff;
		+NOBLOCKMAP
		+NOGRAVITY
		+DROPOFF
		-SOLID
		//+NODAMAGETHRUST
		+DONTSPLASH
		+BLOODLESSIMPACT
		+THRUACTORS
		+ROLLSPRITE
		RenderStyle "Translucent";
		Obituary "$OB_GRENLAUNCHER_GAS";
		Alpha 0.6;
		DamageType "PoisonCloud";
	}

	States
	{
	Spawn:
		GBOC X 0;
		GBOX X 0 A_SetRoll(random(0,360));
		GBOC XXXXXXXXXXXXXXXX 2;
		GBOC XXXXXXXXXXXXXXXX 2;
		GBOC XXXXXXXXXXXXXXXX 2;
	Death:
		GBOC X 1 A_FadeOut(0.05);
		loop;
	}
}

Class MetaGrenadeLauncher_GrenadeTrail : VisualThinker
{
	int stagger;
	int frame;
	
	override void PostBeginPlay()
	{
		super.PostBeginPlay();
		//SetRenderStyle(STYLE_Translucent);
		SetRenderStyle(STYLE_Translucent);
		flags = SPF_ROLL;//|SPF_FULLBRIGHT;
		roll = random(0,3)*90;
		alpha = 0.35;//+frandom(-0.05,0.05);
		//scale = (0.25,0.25);
		//scolor = "#818181";
		vel = (frandom(-0.25,0.25), frandom(-0.25,0.25), frandom(-0.25,0.25));
		UpdateSprite();
		
		//texture = TexMan.CheckForTexture("graphics/fx/spark.png");
	}
	
	void UpdateSprite()
	{
		texture = TexMan.CheckForTexture("graphics/fx/smoothpuff"..(frame+1)..".png");
	}
	
	override void Tick()
	{
		if ( bDESTROYED )
			return;
	
		super.Tick();
		
		stagger += 1;
		if ( stagger >= 5 )
		{
			stagger = 0;
			frame += 1;
			if ( frame >= 5 )
			{
				Destroy();
				return;
			}
			UpdateSprite();
			//alpha -= 0.1;
		}
		
		//alpha -= 0.005;
		scale.x += 0.01;
		scale.y += 0.01;
		if ( alpha <= 0.0 )
		{
			Destroy();
			return;
		}
		
		vel.x *= 0.9;
		vel.y *= 0.9;
		vel.z += 0.1;
	}
}

Class MetaGrenadeLauncher_GasCloud : VisualThinker
{
	bool fadeOut;
	double angler;
	
	override void PostBeginPlay()
	{
		super.PostBeginPlay();
		SetRenderStyle(STYLE_Translucent);
		flags = SPF_ROLL|SPF_FULLBRIGHT;
		roll = random(0,360);
		alpha = 0.0;
		vel = (cos(angler), sin(angler), frandom(-0.2,0.2)) * 8;
		vel += (frandom(-0.25,0.25), frandom(-0.25,0.25), frandom(-0.25,0.25));
		
		texture = TexMan.CheckForTexture("GBOCX0");
	}
	
	override void Tick()
	{
		if ( bDESTROYED )
			return;
	
		super.Tick();
		
		if ( fadeOut )
		{
			alpha -= 0.025;
			scale.x -= 0.01;
			scale.y -= 0.01;
			if ( alpha <= 0.0 )
			{
				Destroy();
				return;
			}
			vel.z += 0.01;
		}
		else
		{
			alpha += 0.1;
			if ( alpha >= 1.0 )
			{
				alpha = 1.0;
				fadeOut = true;
			}
			vel.z *= 0.93;
		}
		
		vel.x *= 0.92;
		vel.y *= 0.92;
	}
}