/*
----------------------------
MetaDoom
Actor Definitions
Fire Axe
----------------------------
*/

class MetaAxePickup : WeaponGiver
{
	Default
	{
		DropItem "MetaAxe";
		Inventory.PickupMessage "$GOTAXE";
		Inventory.PickupSound "weapons/axe/get";
	}
	States
	{
	Spawn:
		AXEG Z 0;
		AXEG Z 0 { bDROPPED = 0; }
		AXEG Z -1;
		Stop;
	}
}

class MetaAxe : MetaDoomMeleeWeapon
{
	Default
	{
		Weapon.SelectionOrder 2400;
		Weapon.Kickback 100;
		Obituary "$OB_AXE";
		Tag "$TAGAXE";
		+WEAPON.WIMPY_WEAPON
		+WEAPON.MELEEWEAPON
		+WEAPON.NOALERT
		Inventory.PickupMessage "$GOTAXE";
		Inventory.PickupSound "weapons/axe/get";
		Weapon.UpSound "weapons/axe/use";
		//$Category "Weapons/MetaDoom"
		//$Title "Fire Axe"
		//$NotAngled
		//$Color 14
		
		MetaDoomMeleeWeapon.ChargeTime 70;
	}
	
	Vector2 windup_start;
	int windup;
	
	action void A_MetaAxe2()
	{
		if ( A_MetaMelee(20 + random(-2, 2), damageType: 'Axe') )
		{
			A_StartSound("weapons/axe/hit", CHAN_WEAPON);
			A_MetaHitStop(3);
		}
		//A_MetaMelee_Thrust(6,0,5);
		A_MetaMelee_Pinata("MetaHealthPinata", 3, 5, 5);
	}
	
	States
	{
		Ready:
			AXEG A 1 A_WeaponReady;
			"####" A 0 A_JumpIfInventory("MeleePunch", 1, "MeleePunch");
			Loop;
		Deselect:
			AXEG A 0 A_JumpIf(health <= 0, "DeadDude");
			AXEG A 0 A_PlaySound("weapons/swap");
		FinishDeselect:
			AXEG A 1 A_SmoothLower();
			Loop;
		Select:
			AXEG A 0 A_OverlayScale(PSP_WEAPON, 1, 1);
			AXEG A 1 A_SmoothRaise();
			loop;
		AltFire:
		Fire:
			TNT1 A 0 A_PlaySound("weapons/swap", CHAN_AUTO, 0.5);
		WindUp:
			AXEG A 0
			{
				invoker.windup_start = (0,32);
				invoker.windup = 0;
				
				let recoil = new("Meta_RecoilInfo");
				recoil.tics_in = 7;
				recoil.tics_out = 7;
				recoil.pitch = 1;
				recoil.yaw = -0.75;
				A_MetaRecoil(recoil);
			}
			AXEG AAABBB 1
			{
				double progress = (invoker.windup/4.);
				progress = progress * progress * progress;
				double x = invoker.windup_start.x + ( 256 - invoker.windup_start.x ) * progress;
				double y = invoker.windup_start.y + ( 32 - invoker.windup_start.y ) * progress;
				
				A_WeaponOffset(x, y, WOF_INTERPOLATE);
				invoker.windup += 1;
			}
			Goto QuickMelee;
		QuickMelee:
			AXEG A 0 A_WeaponOffset(0,32);
			TNT1 A 2 A_WeaponOffset(0,32);
			AXEG I 1
			{
				A_UseUpCharge();
				
				let recoil = new("Meta_RecoilInfo");
				recoil.tics_in = 3;
				recoil.tics_out = 18;
				recoil.pitch = -2;
				recoil.yaw = 0.75*2;
				recoil.roll = -0.25;
				recoil.yaw_speed = random(25,30);
				recoil.yaw_shake = 0.2;
				recoil.roll_speed = random(30,35);
				recoil.roll_shake = 0.3;
				A_MetaRecoil(recoil);
				A_PlaySound("weapons/axe/fire");
				A_Overlay(PSP_PUNCHANIM, "Overlay.QuickMeleeOffset");
				
				if (CountInv("PowerMetaDamage") > 0)
				{
					A_PlaySound("powerups/quad/use", CHAN_5);
				}
			}
			AXEG CCCD 1;
			AXEG D 1 A_MetaAxe2();//A_CustomPunch(7 * random(1, 5), TRUE, CPF_NOTURN,"MetaAxePuff",80,0,0,"BasicArmorBonus","weapons/axe/hit");
			AXEG D 1;
			AXEG E 10;
			"----" A 0 A_JumpIfQuickMelee("Deselect");
			AXEG A 1 A_WeaponOffset(0,90,WOF_INTERPOLATE);
			AXEG A 1 A_WeaponOffset(0,70,WOF_INTERPOLATE);
			AXEG A 1 A_WeaponOffset(0,55,WOF_INTERPOLATE);
			AXEG A 1 A_WeaponOffset(0,44,WOF_INTERPOLATE);
			AXEG A 1 A_WeaponOffset(0,35,WOF_INTERPOLATE);
			AXEG A 1 A_WeaponOffset(0,33,WOF_INTERPOLATE);
			AXEG A 1 A_WeaponOffset(0,32,WOF_INTERPOLATE);
			Goto Ready;
		Overlay.QuickMeleeOffset:
			TNT1 A 1 A_WeaponOffset(257.84, -5.76, WOF_INTERPOLATE);
			TNT1 A 1 A_WeaponOffset(205.38, -2.84, WOF_INTERPOLATE);
			TNT1 A 1 A_WeaponOffset(121.87, 7.47, WOF_INTERPOLATE);
			TNT1 A 1 A_WeaponOffset(57.27, 28.61, WOF_INTERPOLATE);
			TNT1 A 1 A_WeaponOffset(17.40, 62.34, WOF_INTERPOLATE);
			TNT1 A 1 A_WeaponOffset(-9.71, 102.03, WOF_INTERPOLATE);
			TNT1 A 1 A_WeaponOffset(-29.53, 137.63, WOF_INTERPOLATE);
			TNT1 A 1 A_WeaponOffset(-44.63, 165.95, WOF_INTERPOLATE);
			TNT1 A 1 A_WeaponOffset(-56.42, 187.96, WOF_INTERPOLATE);
			TNT1 A 1 A_WeaponOffset(-65.73, 205.09, WOF_INTERPOLATE);
			TNT1 A 1 A_WeaponOffset(-73.13, 218.51, WOF_INTERPOLATE);
			TNT1 A 1 A_WeaponOffset(-78.98, 229.03, WOF_INTERPOLATE);
			TNT1 A 1 A_WeaponOffset(-83.55, 239.49, WOF_INTERPOLATE);
			TNT1 A 1 A_WeaponOffset(-87.07, 255.26, WOF_INTERPOLATE);
			TNT1 A 1 A_WeaponOffset(-89.66, 275.80, WOF_INTERPOLATE);
			TNT1 A 1 A_WeaponOffset(-91.47, 282.68, WOF_INTERPOLATE);
			TNT1 A 1 A_WeaponOffset(-92.59, 286.77, WOF_INTERPOLATE);
			TNT1 A 1 A_WeaponOffset(-93.10, 289.90, WOF_INTERPOLATE);
			TNT1 A 1 A_WeaponOffset(-93.07, 292.56, WOF_INTERPOLATE);
			TNT1 A 1 A_WeaponOffset(-92.54, 294.93, WOF_INTERPOLATE);
			Stop;
		Spawn:
			AXEG Z -1;
			Stop;
	}
}

class MetaAxePuff : Actor
{
	Default
	{
		+NOBLOCKMAP
		+NOGRAVITY
		+ALLOWPARTICLES
		+RANDOMIZE
		damagetype "Axe";
		RenderStyle "Translucent";
		Alpha 0.5;
		VSpeed 1;
		Mass 5;
		AttackSound "weapons/axe/hitwall";
		SeeSound "weapons/axe/hit";
		Obituary "$OB_AXE";
	}
	States
	{
	Spawn:
		PUFF A 4 Bright;
		PUFF B 4;
	Melee:
		PUFF CD 4;
		Stop;
	}
}