/*
----------------------------
MetaDoom
Actor Definitions
Chaingun
----------------------------
*/

class ChaingunTurretMode : _Boolean {}

class MetaChaingunPickup : WeaponGiver
{
	Default
	{
		DropItem "MetaChaingun";
		Inventory.PickupMessage "$GOTCHAINGUN";
		Inventory.PickupSound "weapons/chaingun/get";
	}
	
	States
	{
	Spawn:
		CHGN Z 0;
		CHGN Z 0 { bDROPPED = 0; }
		CHGN Z -1;
		Stop;
	}
}

Class MetaChaingun_AltSlow : PowerSpeed
{
	Default
	{
		Powerup.Duration 0x7FFFFFFD;
		Speed 0.2;
	}
}

class MetaChaingun : MetaDoomWeapon
{
	Default
	{
		Inventory.PickupMessage "$GOTCHAINGUN";
		Tag "$TAG_CHAINGUN";
		Obituary "$OB_MPCHAINGUN";
		Inventory.PickupSound "weapons/chaingun/get";
		Weapon.SelectionOrder 400;
		Weapon.Kickback 90;
		Weapon.AmmoType "Clip";
		Weapon.AmmoGive 100;
		Weapon.AmmoUse 1;
		Weapon.UpSound "weapons/chaingun/use";
		//$Category "Weapons/MetaDoom"
		//$Title "Chaingun"
		//$NotAngled
		//$Color 14
	}
	
	action void A_MetaChaingunRecoil()
	{
		let recoil = new("Meta_RecoilInfo");
		recoil.tics_in = 1;
		recoil.tics_out = 6;
		recoil.pitch = 0.15+frandom(0.025,0.025);
		recoil.roll_speed = random(20,30);
		recoil.roll_shake = 0.25;
		A_MetaRecoil(recoil);
	}
	
	action void A_MetaChaingunRecoil2()
	{
		let recoil = new("Meta_RecoilInfo");
		recoil.tics_in = 1;
		recoil.tics_out = 6;
		recoil.pitch = 0.25+frandom(0.025,0.025);
		recoil.roll_speed = random(20,30);
		recoil.roll_shake = 0.35;
		A_MetaRecoil(recoil);
	}
	
	action void A_MetaChaingunTransform()
	{
		let recoil = new("Meta_RecoilInfo");
		recoil.tics_in = 1;
		recoil.tics_out = 4;
		recoil.pitch = frandom(-0.25,0.25);
		recoil.roll_speed = random(40,50);
		recoil.roll_shake = 0.15;
		A_MetaRecoil(recoil);
	}
	
	States
	{
	Spawn:
		CHGN Z -1;
		loop;
	Ready:
		CHGN A 0;
		CHGN A 0 A_JumpIfInventory("ChaingunTurretMode",1,"AltfireReady");
		CHGN A 1 A_WeaponReady;
		"####" # 0 A_JumpIfInventory("MeleePunch", 1, "MeleePunch");
		Loop;
	AltfireReady:
		CHGN J 1 A_WeaponReady(WRF_NOBOB);
		"####" # 0 A_JumpIfInventory("MeleePunch", 1, "AltfireReady");
		Loop;
	Deselect:
		CHGN A 0;
		TNT1 A 0;
		TNT1 A 0 
		{
			A_StopSound(CHAN_BODY);
			A_StopSound(CHAN_WEAPON);
			A_StopSound(CHAN_6);
		}
		CHGN A 0 A_JumpIf(health <= 0, "DeadDude");
		CHGN A 0 A_JumpIfInventory("ChaingunTurretMode",1,"AltfireDeselect");
		CHGN A 0 A_PlaySound("weapons/swap");
	FinishDeselect:
		CHGN A 1 A_SmoothLower();
		Loop;
	Select:
		CHGN A 0 A_OverlayScale(PSP_WEAPON, 1, 1);
		CHGN A 1 A_SmoothRaise();
		loop;
	Fire:
		CHGN A 0 A_JumpIfInventory("ChaingunTurretMode",1,"Altfirefire");
		CHGN B 6 A_PlaySound("weapons/chaingun/windup",6);
		CHGN C 5;
		CHGN D 4;
		CHGN A 3;
		CHGN B 2;
		CHGN BCDABCD 1;
		CHGN D 0 A_ReFire;
	WindDown:
		CHGN A 1 { A_PlaySound("weapons/chaingun/winddown",6); A_WeaponOffset(0,32,WOF_INTERPOLATE); }
		CHGN B 2;
		CHGN C 3;
		CHGN D 4;
		CHGN A 5;
		CHGN BCD 6;
		CHGN A 0 A_CheckReload();
		Goto Ready;
	Hold:
		CHGN A 0 A_JumpIfInventory("ChaingunTurretMode",1,"Altfirefire");
		CHGN A 0 A_Quake(8,2,0,128,"null");
		CHGN A 0 A_PlaySound("weapons/chaingun/loop",6,1,1);
		CHGN A 1 BRIGHT 
		{
			A_PlaySound("weapons/chaingun/fire",CHAN_WEAPON);
			
			if (CountInv("PowerMetaDamage") > 0)
			{
				A_PlaySound("powerups/quad/use", CHAN_5);
			}
			
			A_FireBullets(5.6,5.6,1,5,"MetaBulletPuff");
			if (meta_perf_spentbrass == 1)
			{
				A_FireProjectile("BulletCasingSpawn",5,0,8,-9);
			}
			A_GunFlash("Flash1");
			A_Quake (3,5,0,750,0);
			A_WeaponOffset(random(-2,2),random(32,34),WOF_INTERPOLATE);
			A_MetaChaingunRecoil();
		}
		CHGN D 0 A_JumpIfNoAmmo("WindDown");
		CHGN B 1 BRIGHT 
		{
			A_PlaySound("weapons/chaingun/fire",CHAN_WEAPON);
			A_FireBullets(5.6,5.6,0,5,"MetaBulletPuff");
			if (meta_perf_spentbrass == 1)
			{
				A_FireProjectile("BulletCasingSpawn",5,0,8,-9);
			}
			A_Quake (3,5,0,750,0);
			A_WeaponOffset(random(-2,2),random(32,34),WOF_INTERPOLATE);
			A_MetaChaingunRecoil();
		}
		CHGN D 0 A_JumpIfNoAmmo("WindDown");
		CHGN C 1 BRIGHT 
		{
			A_PlaySound("weapons/chaingun/fire",CHAN_WEAPON);
			A_FireBullets(5.6,5.6,0,5,"MetaBulletPuff");
			if (meta_perf_spentbrass == 1)
			{
				A_FireProjectile("BulletCasingSpawn",5,0,8,-9);
			}
			A_GunFlash("Flash2");
			A_Quake (3,5,0,750,0);
			A_WeaponOffset(random(-2,2),random(32,34),WOF_INTERPOLATE);
			A_MetaChaingunRecoil();
		}
		CHGN D 0 A_JumpIfNoAmmo("WindDown");
		CHGN D 1 BRIGHT 
		{
			A_PlaySound("weapons/chaingun/fire",CHAN_WEAPON);
			A_FireBullets(5.6,5.6,0,5,"MetaBulletPuff");
			if (meta_perf_spentbrass == 1)
			{
				A_FireProjectile("BulletCasingSpawn",5,0,8,-9);
			}
			A_Quake (3,5,0,750,0);
			A_WeaponOffset(random(-2,2),random(32,34),WOF_INTERPOLATE);
			A_MetaChaingunRecoil();
		}
		CHGN D 0 A_JumpIfNoAmmo("WindDown");
		CHGN D 0 A_ReFire;
		Goto WindDown;
		
	Flash1:
		CHGN E 1 Bright A_Light1;
		CHGN F 1 Bright;
		Goto LightDone;
	Flash2:
		CHGN G 1 Bright A_Light1;
		CHGN H 1 Bright;
		Goto LightDone;
		
	Flash3:
		CHGN I 1 Bright A_Light1;
		CHGN J 1 Bright;
		Goto LightDone;
	Flash4:
		CHGN K 1 Bright A_Light1;
		CHGN L 1 Bright;
		Goto LightDone;
	Glow3:
		CHGN QR 1 Bright A_Light1;
		Stop;
	Glow4:
		CHGN ST 1 Bright;
		Stop;
		
	Altfire:
		MACG E 0 A_JumpIfInventory("ChaingunTurretMode",1,"AltfireEnd");
	AltfireStart:
		MACG E 0 A_JumpIf(CountInv("Clip") < 10, "AltfireBlank");
		MACG E 0 A_GiveInventory("MetaChaingun_AltSlow");
		MACG E 0 A_PlaySound("weapons/chaingun/turretup");
		CHFL A 2 A_WeaponOffset (0,33,WOF_INTERPOLATE);
		CHFL B 2 A_WeaponOffset (0,34,WOF_INTERPOLATE);
		CHFL C 2 A_WeaponOffset (0,33,WOF_INTERPOLATE);
		CHFL D 2 A_WeaponOffset (0,32,WOF_INTERPOLATE);
		"----" A 0 A_MetaChaingunTransform();
		CHFL EEE 1 A_WeaponOffset(random(-1,1),32,WOF_INTERPOLATE);
		CHFL F 2 A_WeaponOffset (0,34,WOF_INTERPOLATE);
		CHFL G 2 A_WeaponOffset (0,33,WOF_INTERPOLATE);
		"----" A 0 A_MetaChaingunTransform();
		CHFL HHH 1 A_WeaponOffset(random(-1,1),random(31,33),WOF_INTERPOLATE);
		CHTR A 5 { A_WeaponOffset (0,32,WOF_INTERPOLATE); A_GiveInventory("ChaingunTurretMode", 1); }
		goto Ready;
	AltfireEnd:
		CHTR A 0 A_StopSound(CHAN_6);
		MACG J 0 A_PlaySound("weapons/chaingun/turretdown");
		MACG E 0 A_TakeInventory("MetaChaingun_AltSlow");
		CHFL G 2 A_WeaponOffset (0,34,WOF_INTERPOLATE);
		CHFL F 2 A_WeaponOffset (0,33,WOF_INTERPOLATE);
		"----" A 0 A_MetaChaingunTransform();
		CHFL E 1 A_WeaponOffset(random(-1,1),random(31,33),WOF_INTERPOLATE);
		CHFL D 2 A_WeaponOffset (0,32,WOF_INTERPOLATE);
		CHFL C 2 A_WeaponOffset (0,34,WOF_INTERPOLATE);
		CHFL B 2 A_WeaponOffset (0,33,WOF_INTERPOLATE);
		CHFL A 2 A_WeaponOffset (0,32,WOF_INTERPOLATE);
		"----" A 0 A_MetaChaingunTransform();
		CHGN AAA 1 A_WeaponOffset(random(-1,1),32,WOF_INTERPOLATE);
		//CHFL GFEDCBA 2
		MACG A 0 { A_WeaponOffset (0,32,WOF_INTERPOLATE); A_TakeInventory("ChaingunTurretMode", 999); }
		Goto Ready;
	AltfireDeselect:
		CHTR A 0 A_StopSound(CHAN_6);
		MACG J 0 A_PlaySound("weapons/chaingun/turretdown");
		MACG E 0 A_TakeInventory("MetaChaingun_AltSlow");
		CHFL G 2 A_WeaponOffset (0,31,WOF_INTERPOLATE);
		CHFL F 2 A_WeaponOffset (0,30,WOF_INTERPOLATE);
		CHFL E 2 A_WeaponOffset (0,29,WOF_INTERPOLATE);
		CHFL D 2 A_WeaponOffset (0,30,WOF_INTERPOLATE);
		CHFL C 2 A_WeaponOffset (0,31,WOF_INTERPOLATE);
		CHFL B 2 A_WeaponOffset (0,32,WOF_INTERPOLATE);
		CHFL A 2 A_WeaponOffset (0,33,WOF_INTERPOLATE);
		//CHFL GFEDCBA 2
		MACG A 0 { A_WeaponOffset (0,32,WOF_INTERPOLATE); A_TakeInventory("ChaingunTurretMode", 999); }
		Goto Deselect;
	AltfireBlank:
		CHGN A 1 Offset(0,34) A_PlaySound("weapons/machinegun/dry", CHAN_BODY);
		CHGN A 1 Offset(0,33);
		CHGN A 1 Offset(0,32) A_TakeInventory("ChaingunTurretMode", 1);
		CHGN A 10;
		goto Ready;
		
	AltfireReady:
		CHTR A 1 A_WeaponReady;
		CHTR A 0 A_JumpIfInventory("MeleePunch", 1, "MeleePunch");
		Loop;
		
	AltfireFire:
		CHTR A 0
		{
			A_PlaySound("weapons/chaingun/turretfire",6,1,1);
			A_MetaChaingunRecoil2();
			A_GunFlash("Flash3");
			A_Overlay(100, "Glow3");
			A_OverlayFlags(100, PSPF_RENDERSTYLE, true);
			A_OverlayRenderstyle(100, STYLE_ADD);
		}
		CHTR BC 1 
		{
			A_FireBullets(3,3,1,5,"MetaTurretPuff",FBF_USEAMMO);
			A_FireBullets(3,3,1,5,"MetaTurretPuff",FBF_USEAMMO);
			A_FireBullets(3,3,1,5,"MetaTurretPuff",FBF_USEAMMO);
			A_FireBullets(3,3,1,5,"MetaTurretPuff",!FBF_USEAMMO);
			//A_FireProjectile("BulletCasingSpawn",5,0,8,-9);
			//A_FireProjectile("BulletCasingSpawn",10,0,16,-9);
			//A_FireProjectile("BulletCasingSpawn",5,0,-16,4);
			A_Quake (1,2,0,750,0);
			A_WeaponOffset(random(-1,1), random(32,33), WOF_INTERPOLATE);
		}
		CHTR A 0 A_Refire("AltfireFire2");
		CHTR A 0 A_PlaySound("weapons/chaingun/turretend",6);
		Goto Ready;
	AltfireFire2:
		CHTR A 0
		{
			A_PlaySound("weapons/chaingun/turretfire",6,1,1);
			A_MetaChaingunRecoil2();
			A_GunFlash("Flash4");
			A_Overlay(100, "Glow4");
			A_OverlayFlags(100, PSPF_RENDERSTYLE, true);
			A_OverlayRenderstyle(100, STYLE_ADD);
		}
		CHTR DA 1 
		{
			A_FireBullets(3,3,1,5,"MetaTurretPuff",FBF_USEAMMO);
			A_FireBullets(3,3,1,5,"MetaTurretPuff",FBF_USEAMMO);
			A_FireBullets(3,3,1,5,"MetaTurretPuff",FBF_USEAMMO);
			A_FireBullets(3,3,1,5,"MetaTurretPuff",!FBF_USEAMMO);
			//A_FireProjectile("BulletCasingSpawn",5,0,8,-9);
			//A_FireProjectile("BulletCasingSpawn",10,0,16,-9);
			//A_FireProjectile("BulletCasingSpawn",5,0,-16,4);
			A_Quake (1,2,0,750,0);
			A_WeaponOffset(random(-1,1), random(32,33), WOF_INTERPOLATE);
		}
		CHTR A 0 A_Refire("AltfireFire");
		CHTR A 0 A_PlaySound("weapons/chaingun/turretend",6);
		Goto Ready;
	}
}