/*
----------------------------
MetaDoom
Actor Definitions
BFG 9000
----------------------------
*/

Class MetaBFG9000Pickup : WeaponGiver
{
	Default
	{
		DropItem "MetaBFG9000";
		Inventory.PickupMessage "$GOTBFG9000";
		Inventory.PickupSound "weapons/bfg/get";
	}
	States
	{
	Spawn:
		MBFG Z 0;
		MBFG Z 0 { bDROPPED = false; }
		MBFG Z -1;
		Stop;
	}
}

Class MetaBFG9000 : MetaDoomWeapon
{
	Default
	{
		Height 20;
		Weapon.SelectionOrder 2800;
		Weapon.AmmoUse1 1;
		Weapon.AmmoUse2 1;
		Weapon.AmmoGive 3;
		Weapon.AmmoType1 "BFGAmmo";
		Weapon.AmmoType2 "BFGAmmo";
		+WEAPON.NOAUTOFIRE;
		Inventory.PickupMessage "$GOTBFG9000";
		Tag "$TAG_BFG9000";
		Inventory.PickupSound "weapons/bfg/get";
		Weapon.BobRangeX 0.5;
		Weapon.BobRangey 0.25;
		Weapon.UpSound "weapons/bfg/use";
		//$Category "Weapons/MetaDoom"
		//$Title "BFG9000"
		//$NotAngled
		//$Color 14
	}
	
	double zoomspeed;
	double shakeamt;
	
	States
	{
		
	Overlay.Lights:
		MBFF D 1 BRIGHT;
		"----" A 1 BRIGHT
		{
			double flicker = sin(level.maptime*6) * frandom(0.5,1);
			A_OverlayAlpha(OverlayID(), 0.75 + flicker*0.25);
			PSprite psp_base = self.player.FindPSprite(PSP_WEAPON);
			PSprite psp_this = self.player.FindPSprite(OverlayID());
			if ( psp_base && psp_this )
			{
				psp_this.frame = psp_base.frame;
			}
			if ( random(0,4) == 0 )
			{
				A_Overlay(101, "Overlay.Zap");
				A_OverlayFlags(101, PSPF_RENDERSTYLE|PSPF_FORCEALPHA, true);
				A_OverlayRenderstyle(101, STYLE_ADD);
				PSprite psp = self.player.FindPSprite(101);
				if ( psp )
				{
					int side = random(0,1);
					double vert = frandom(0.0,1.0);
					psp.frame = random(0,15);
					psp.x = 160 + (112+16*vert) * (side ? 1 : -1);
					psp.y = 132+32*vert;
					psp.pivot = (0.5, 0.5);
					psp.rotation = 45*vert;
					psp.scale = (side ? -1 : 1,1)*frandom(0.8,1.2);
				}
			}
		}
		Wait;
	Overlay.Zap:
		MBFZ A 1 BRIGHT;
		"----" A 1 BRIGHT
		{
			PSprite psp = self.player.FindPSprite(OverlayID());
			if ( psp )
			{
				psp.frame = psp.frame+1 % 16;
			}
		}
		"----" A 1 BRIGHT
		{
			if ( random(0,1) )
			{
				return resolveState("Null");
			}
			PSprite psp = self.player.FindPSprite(OverlayID());
			if ( psp )
			{
				psp.frame = psp.frame+1 % 16;
			}
			return resolveState(null);
		}
		Wait;
	Ready:
		MBFG A 1 A_WeaponReady;
		"####" A 0 A_JumpIfInventory("MeleePunch", 1, "MeleePunch");
		//MBFG F 1 A_WeaponReady;
		//"####" A 0 A_JumpIfInventory("MeleePunch", 1, "MeleePunch");
		Loop;
	Deselect:
		MBFG A 0 A_JumpIf(health <= 0, "DeadDude");
		MBFG A 0 A_PlaySound("weapons/swap");
	FinishDeselect:
		MBFG AB 1 A_SmoothLower();
		Loop;
	Select:
		MBFG A 0
		{
			A_Overlay(100, "Overlay.Lights");
			A_OverlayFlags(100, PSPF_RENDERSTYLE|PSPF_FORCEALPHA, true);
			A_OverlayRenderstyle(100, STYLE_ADD);
		}
		MBFG A 0 A_OverlayScale(PSP_WEAPON, 1, 1);
		MBFG AA 1 A_SmoothRaise();
		Wait;
	Fire:
		MBFG A 1 
		{
			A_PlaySound("weapons/bfg/charge");
			A_Overlay(14, "Overlay.ChargeUp");
			invoker.FOVScale = 1.0;
			invoker.zoomspeed = 0.0;
		}
		//MBFG BABABABABABABABABABABABABABA 1;
		MBFG BBCCDDDDDDDDDDDDDDDDDDDDDDDD 1
		{
			invoker.FOVScale += invoker.zoomspeed;
			invoker.zoomspeed += 0.0005;
		}
		MBFG D 2 BRIGHT
		{
			A_FireProjectile("MetaBFGBall");
			A_PlaySound ("weapons/bfg/fire1", CHAN_WEAPON);
			
			if (CountInv("PowerMetaDamage") > 0)
			{
				A_PlaySound("powerups/quad/use", CHAN_5);
			}
			
			A_GunFlash();
			A_Quake (8,10,0,750,0);
			A_Overlay(14, "Overlay.Primary");
			
			let recoil = new("Meta_RecoilInfo");
			recoil.tics_in = 2;
			recoil.tics_out = 25;
			recoil.pitch = 8;
			recoil.roll_speed = random(30,35);
			recoil.roll_shake = 0.2;
			recoil.pitch_speed = random(30,35);
			recoil.pitch_shake = 0.2;
			A_MetaRecoil(recoil);
		}
		MBFG D 2 bright;
		MBFG D 2 bright;
		MBFG CBA 2;
		//MBFG ABABABABAB 1;
		MBFG A 10;
		Goto Ready;
	AltFire:
		MBFG A 1 
		{
			A_PlaySound("weapons/bfg/altcharge");
			A_Overlay(14, "Overlay.ChargeUp");
		}
		//MBFG BABABABABABABABABABABABABABA 1;
		MBFG AAAAAAAAAAAAAAA 1;
		MBFG C 0 bright
		{
			A_PlaySound ("weapons/bfg/fire2", CHAN_WEAPON);
			
			if (CountInv("PowerMetaDamage") > 0)
			{
				A_PlaySound("powerups/quad/use", CHAN_5);
			}
			
			A_GunFlash("AltFlash");
			A_Quake (8,10,0,750,0);
			A_TakeInventory("BFGAmmo",1);
		}
		MBFG DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD 1 bright
		{
			A_FireProjectile("MetaBFGAltfire",random(-16,16),0,0,0,FPF_NOAUTOAIM,random(-10,10));
			A_FireProjectile("MetaBFGAltfire",random(-9,9),0,0,0,FPF_NOAUTOAIM,random(-7,7));
			invoker.FOVScale = 1.2+frandom(0.0,0.05);
			//A_ZoomFactor(frandom(0.8,0.85), ZOOM_NOSCALETURNING);
		}
		MBFG C 0 bright A_Overlay(14, "Overlay.Alternate");
		MBFG C 1 bright
		{
			let recoil = new("Meta_RecoilInfo");
			recoil.tics_in = 0;
			recoil.tics_out = 15;
			recoil.pitch = 8;
			recoil.roll_speed = random(30,35);
			recoil.roll_shake = 0.2;
			recoil.pitch_speed = random(30,35);
			recoil.pitch_shake = 0.2;
			A_MetaRecoil(recoil);
			A_GunFlash("Null");
		}
		MBFG DE 2 bright;
		MBFG FGH 2;
		MBFG ABABABABAB 1;
		Goto Ready;
	/*Flash:
		TNT1 A 11 Bright A_Light1;
		TNT1 B 6 Bright A_Light2;
		Goto LightDone;*/
	Flash:
		MBFM ABCDE 2;
		Goto LightDone;
	AltFlash:
		MBFM ABDE 2 A_SetTics(random(0,2));
		Loop;
	Spawn:
		MBFG Z -1;
		Stop;
		
	Overlay.ChargeUp:
		TNT1 A 0
		{
			invoker.shakeamt = 0;
		}
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAA 1
		{
			double wobble = invoker.shakeamt * (1-(level.maptime%2)*2);
			A_WeaponOffset(wobble, random(32,33), WOF_INTERPOLATE);
			invoker.shakeamt += 0.25;
		}
		Stop;
		
	Overlay.Primary:
		TNT1 A 1 A_ZoomFactor(0.6, ZOOM_INSTANT|ZOOM_NOSCALETURNING);
		TNT1 C 1 { A_WeaponOffset(0,45,WOF_INTERPOLATE); }// A_SetPitch(pitch-4, SPF_INTERPOLATE); }
		TNT1 D 1 { A_WeaponOffset(0,48,WOF_INTERPOLATE); }// A_SetPitch(pitch-4, SPF_INTERPOLATE); }
		TNT1 D 1 { A_WeaponOffset(0,48,WOF_INTERPOLATE); A_ZoomFactor(1.0, ZOOM_NOSCALETURNING); }
		TNT1 E 1 { A_WeaponOffset(0,46,WOF_INTERPOLATE); }// A_SetPitch(pitch+1, SPF_INTERPOLATE); }
		TNT1 E 1 { A_WeaponOffset(0,44,WOF_INTERPOLATE); }// A_SetPitch(pitch+1, SPF_INTERPOLATE); }
		TNT1 F 1 { A_WeaponOffset(0,42,WOF_INTERPOLATE); }// A_SetPitch(pitch+1, SPF_INTERPOLATE); }
		TNT1 F 1 { A_WeaponOffset(0,38,WOF_INTERPOLATE); }// A_SetPitch(pitch+1, SPF_INTERPOLATE); }
		TNT1 G 1 { A_WeaponOffset(0,36,WOF_INTERPOLATE); }// A_SetPitch(pitch+2, SPF_INTERPOLATE); }
		TNT1 G 1 { A_WeaponOffset(0,34,WOF_INTERPOLATE); }// A_SetPitch(pitch+2, SPF_INTERPOLATE); }
		TNT1 H 1 A_WeaponOffset(0,33,WOF_INTERPOLATE);
		TNT1 H 1 A_WeaponOffset(0,32,WOF_INTERPOLATE);
		TNT1 A -1;
		stop;
		
	Overlay.Alternate:
		TNT1 C 1 { A_WeaponOffset(0,45,WOF_INTERPOLATE); }// A_SetPitch(pitch-4, SPF_INTERPOLATE); }
		TNT1 D 1 { A_WeaponOffset(0,48,WOF_INTERPOLATE); }// A_SetPitch(pitch-4, SPF_INTERPOLATE); }
		TNT1 D 1 { A_WeaponOffset(0,48,WOF_INTERPOLATE); A_ZoomFactor(1.0, ZOOM_NOSCALETURNING); }
		TNT1 E 1 { A_WeaponOffset(0,46,WOF_INTERPOLATE); }// A_SetPitch(pitch+1, SPF_INTERPOLATE); }
		TNT1 E 1 { A_WeaponOffset(0,44,WOF_INTERPOLATE); }// A_SetPitch(pitch+1, SPF_INTERPOLATE); }
		TNT1 F 1 { A_WeaponOffset(0,42,WOF_INTERPOLATE); }// A_SetPitch(pitch+1, SPF_INTERPOLATE); }
		TNT1 F 1 { A_WeaponOffset(0,38,WOF_INTERPOLATE); }// A_SetPitch(pitch+1, SPF_INTERPOLATE); }
		TNT1 G 1 { A_WeaponOffset(0,36,WOF_INTERPOLATE); }// A_SetPitch(pitch+2, SPF_INTERPOLATE); }
		TNT1 G 1 { A_WeaponOffset(0,34,WOF_INTERPOLATE); }// A_SetPitch(pitch+2, SPF_INTERPOLATE); }
		TNT1 H 1 A_WeaponOffset(0,33,WOF_INTERPOLATE);
		TNT1 H 1 A_WeaponOffset(0,32,WOF_INTERPOLATE);
		TNT1 A -1;
		stop;
	}
}

Class MetaBFG9000_GotZapped : Powerup
{
	Default
	{
		Powerup.Duration 35;
	}
	
	override void DoEffect()
	{
		if ( !owner )
		{
			return;
		}
		
		/*if ( owner.tics > 0 )
		{
			owner.tics = owner.tics;
		}*/
		
		owner.SpriteOffset.x = 1 + (-2*(level.maptime%2));
		
		let p = Level.SpawnVisualThinker("MetaBFG9000_ZapTrail");
		p.Texture = TexMan.CheckForTexture("MBFZA0");
		p.pos = owner.pos + (0,0,owner.height/2) + (frandom(-radius,radius)/2, frandom(-radius,radius)/2, frandom(-height,height)/3);
		p.SetRenderStyle(STYLE_Add);
		p.scale *= frandom(0.8,1.0);
		p.roll = random(0,360);
		p.flags = SPF_FULLBRIGHT|SPF_ROLL;
		
		owner.TakeInventory("MetaBFG9000_GotZapped", 1);
	}
	
	override void EndEffect ()
	{
		if ( owner )
		{
			owner.SpriteOffset.x = 0;
		}
		Super.EndEffect();
	}
}

// bfg zapper stuff from argent from xaser, cheers dogg
Class MetaBFGBall : Actor
{
	Default
	{
		Radius 13;
		Height 8;
		Speed 15;
		Damage 250;
		Projectile;
		+RANDOMIZE;
		RenderStyle "Add";
		Alpha 0.75;
		Obituary "$OB_MPBFG_BOOM";
		Decal "BFGLightning";
	}
	
	const BFG_ZAPRADIUS = 480;
	
	action void A_BFGZap(bool finalHit = false)
	{
		BlockThingsIterator it = BlockThingsIterator.Create(self, BFG_ZAPRADIUS);
		Actor mo;
		bool didZap = false;
		bEXTREMEDEATH = finalHit;
		
		Array<Actor> targetsToZap;
		targetsToZap.Clear();

		while ( it.Next() )
		{
			mo = it.thing;
			if ( mo == target ) continue;
			if ( mo.bSHOOTABLE && mo.bSOLID && !mo.bNOTAUTOAIMED && mo.health > 0 && Distance3D(mo)-mo.radius <= BFG_ZAPRADIUS && CheckSight(mo) )
			{
				targetsToZap.Push(mo);
				didZap = true;
			}
		}
		
		if ( didZap )
		{
			A_PlaySound("weapons/bfg/spray");
		}
		
		for ( int i = 0; i < (finalHit ? 30 : 10); i++ )
		{
			if ( targetsToZap.Size() == 0 )
			{
				break;
			}
			
			int toZap = random(0, targetsToZap.Size()-1);
			Actor mo = targetsToZap[toZap];
			targetsToZap.Delete(toZap);
			Vector3 zapPos = pos+(0,0,16);
			Vector3 targPos = mo.pos+(0,0,mo.height/2);
			int dist = level.Vec3Diff(zapPos, targPos).Length();
			int curDist = 0;
			while ( true )
			{
				Vector3 diff = level.Vec3Diff(zapPos, targPos);
				zapPos += diff.Unit()*8;
				let p = Level.SpawnVisualThinker("MetaBFG9000_ZapTrail");
				switch(random(3,4))
				{
					case 3: p.Texture = TexMan.CheckForTexture("BTRLC0"); break;
					case 4: p.Texture = TexMan.CheckForTexture("BTRLD0"); break;
				}
				p.pos = zapPos;
				p.SetRenderStyle(STYLE_Add);
				//p.scale *= frandom(0.8,1.0);
				p.flags = SPF_FULLBRIGHT;
				
				curDist += 8;
				if ( curDist > dist )
				{
					break;
				}
			}
			
			mo.GiveInventory("MetaBFG9000_GotZapped", 35);
			
			int damage;
			if ( finalHit )
			{
				damage = 350;
				if ( mo.bNORADIUSDMG )
				{
					damage = 50;
				}
			}
			else
			{
				damage = 40+20*random(0,1);
			}
			if ( (mo.health - damage) <= -5 )
			{
				damage = mo.health+abs(mo.GetGibHealth())+1;
			}
			mo.DamageMobj(self, target, damage, 'BFG', DMG_THRUSTLESS, AngleTo(mo)); //20*random(1,3);
			
			if ( mo && mo.health > 0 && mo.FindState("Pain") )
			{
				if ( !mo.bNORADIUSDMG )
				{
					mo.SetStateLabel("Pain");
					if ( mo.tics > 0 )
					{
						mo.tics += 5;
					}
				}
				else if ( mo.tics > 0 )
				{
					mo.tics += 1;
				}
			}
		}
	}
	
	States
	{
	Spawn:
		BFS1 A 0;
		BFS1 A 0 A_PlaySound ("weapons/bfg/fly", CHAN_BODY, 1.0, 1);
		BFS1 AAAABBBB 1 Bright 
		{
			A_SetScale(frandom(0.8,1.2),frandom(0.8,1.2));
			A_SpawnItemEx("BFGTrail", frandom(-10,10), frandom(-10,10), frandom(0,20), frandom(-2.5,2.5), frandom(-2.5,2.5), frandom(-2.5,2.5), 0, SXF_CLIENTSIDE, 0);
		}
	Roam:
		"----" A 0 A_BFGZap();
		BFS1 AAAA 1 Bright
		{
			A_SetScale(frandom(0.8,1.2),frandom(0.8,1.2));
			A_SpawnItemEx("BFGTrail", frandom(-10,10), frandom(-10,10), frandom(0,20), frandom(-2.5,2.5), frandom(-2.5,2.5), frandom(-2.5,2.5), 0, SXF_CLIENTSIDE, 0);
		}
		"----" A 0 A_BFGZap();
		BFS1 BBBB 1 Bright 
		{
			A_SetScale(frandom(0.8,1.2),frandom(0.8,1.2));
			A_SpawnItemEx("BFGTrail", frandom(-10,10), frandom(-10,10), frandom(0,20), frandom(-2.5,2.5), frandom(-2.5,2.5), frandom(-2.5,2.5), 0, SXF_CLIENTSIDE, 0);
		}
		Loop;
	Death:
		BFE1 AAAAAAAAAAAAAAAA 0 Bright A_SpawnItemEx("BFGTrail", 0, frandom(-10,10), frandom(-10,10), 0, frandom(-5,5), frandom(-5,5), 0, SXF_CLIENTSIDE, 0);
		BFE1 A 0
		{
			A_StopSound(CHAN_BODY);
			A_PlaySound ("weapons/bfg/explode", CHAN_7, 1.0);
			A_Quake (8,20,0,750,0);
			//A_BFGSpray("BFGSpray", 20, 15, 360, 1024, 32, 0, BFGF_MISSILEORIGIN);
			//A_BFGSpray("BFGSpray", 40, 15, 90, 1024, 32, 0);
			//A_BFGSpray("BFGSpray");
			//A_Explode(128,128,!XF_HURTSOURCE);
			A_BFGZap(true);
		}
		BFE1 ABCDEF 4 Bright;
		TNT1 A 35;
		Stop;
	}
}

Class BFGTrail : Actor
{
	Default
	{
		RenderStyle "Add";
		Alpha 0.75;
		Scale 0.75;
		+NOINTERACTION;
	}
	States
	{
	Spawn:
		BTRL ABCD 3 Bright;
		Stop;
	}
}
Class BFGTrailSmall : BFGTrail { Default { Scale 0.5; } }

Class BFGZapper : Actor
{
	Default
	{
		Radius 2;
		Height 2;
		Speed 0;
		MinMissileChance 0;
		Projectile;
		+LOOKALLAROUND
		+NOINTERACTION
		//+ISMONSTER
		+SEEKERMISSILE
		//+FRIENDLY
		RenderStyle "Add";
		Obituary "$OB_MPBFG_SPLASH";
		AttackSound "weapons/bfg/spray";
		MissileHeight 0;
	}
	States
	{
	Spawn:
		TNT1 A 1 NoDelay A_SeekerMissile(0,0,SMF_CURSPEED|SMF_LOOK,256);
		Goto See;
	See:
		TNT1 A 1
		{
			if(tracer!=null)
			{
				A_PlaySound("weapons/bfg/spray");
				//tracer.DamageMobj(target,target,20*random(1,3),'BFG',0,AngleTo(tracer)); //directly damages the tracer, attributing the damage to the projectile's owner
				tracer.DamageMobj(target, target, 2, 'BFG', 0, AngleTo(tracer));
				if ( tracer.FindState("Pain") )
				{
					tracer.SetStateLabel("Pain");
				}
			}
			target = tracer; //we don't need the owner anymore, but we do need the target to shoot this laser effect at
			A_CustomRailgun(0, 0, "", "", RGF_SILENT | RGF_NOPIERCING, 1, 32, "BFGSpray", 0, 0, 0, 0, 4, 0, "BFGZapperTrail");
		}
		Goto Death;
	Death:
		TNT1 A 0;
		Stop;
	}
}

Class BFGSpray : Actor
{
	Default
	{
		+NOBLOCKMAP
		+NOGRAVITY
		+BLOODSPLATTER
		+EXTREMEDEATH
		RenderStyle "Add";
		Alpha 0.75;
	}
	States
	{
	Spawn:
		BFE2 A 0;
		BFE2 A 0 A_PlaySound("weapons/bfg/spray");
		BFE2 AAAAAAAAAAAAAAAA         0        A_SpawnItemEx("BFGTrailSmall", frandom(-10,10), frandom(-10,10), frandom(-10,10), frandom(-2.5,2.5), frandom(-5.0,5.0), frandom(-5.0,5.0), 0, SXF_CLIENTSIDE, 0);
		BFE2 AAAAAABBBBBBCCCCCCDDDDDD 1 Bright A_SpawnItemEx("BFGTrailSmall", frandom(-10,10), frandom(-10,10), frandom(-10,10), frandom(-2.5,2.5), frandom(-2.5,2.5), frandom(-2.5,2.5), 0, SXF_CLIENTSIDE, 0);
		Stop;
	}
}

Class MetaBFG9000_ZapTrail : VisualThinker
{
	override void PostBeginPlay()
	{
		super.PostBeginPlay();
		startPos = pos;
	}
	
	int time;
	Vector3 startPos;
	
	override void Tick()
	{
		if ( bDESTROYED )
			return;
	
		super.Tick();
		
		pos = startPos+(frandom(-8,8), frandom(-8,8), frandom(-8,8));
		time++;
		
		if ( time >= 4)
		{
			Destroy();
		}
	}
}

Class MetaBFG9000_ZapBit : VisualThinker
{
	int time;
	override void Tick()
	{
		if ( bDESTROYED )
			return;
	
		super.Tick();
		
		if ( time > 0 )
		{
			Destroy();
		}
		time += 1;
	}
}

Class BFGZapperTrail : Actor
{
	Default
	{
		RenderStyle "Add";
		Alpha 0.75;
		Scale 0.75;
		+NOINTERACTION
	}
	States
	{
	Spawn:
		BFE2 D 2 Bright;
		BTRL D 1 Bright;
		Stop;
	}
}

Class MetaBFGAltfire : Actor
{
	Default
	{
		Radius 13;
		Height 8;
		Speed 25;
		Damage 15;
		BounceType "Classic";
		BounceFactor 1.0;
		Projectile;
		+RANDOMIZE;
		RenderStyle "Add";
		Alpha 0.75;
		Obituary "$OB_MPBFG_MBF";
		Decal "GreenPlasmaScorch";
	}
	States
	{
	Spawn:
		PLS1 A 0 A_PlaySound ("weapons/plasmarifle/loop", CHAN_BODY, 1.0, 1);
		PLS1 AB 6 Bright;
		Loop;
	Death:
		PLS1 A 0 A_PlaySound("weapons/plasmarifle/hit");
		PLS1 CDEFG 4 Bright;
		Stop;
	}
}
