/*
----------------------------
MetaDoom
Actor Definitions
Holy Water Pistol
----------------------------
*/

class HolyWaterPistolEquipped : _Boolean {}

class HolyWater : Ammo
{
	Default
	{
		Inventory.PickupMessage "$GOTHOLYWATER";
		Inventory.Amount 1;
		Inventory.MaxAmount 15;
		Ammo.BackpackAmount 5;
		Ammo.BackpackMaxAmount 15;
		Inventory.Icon "HWPAA0";
		Inventory.PickupSound "weapons/waterpistol/ammo";
	}
	
	States
	{
	Spawn:
		TNT1 A 8;
		Stop;
	}
}

class MetaHolyWaterPistolPickup : WeaponGiver
{
	Default
	{
		DropItem "MetaHolyWaterPistol";
		Inventory.Pickupmessage "$GOTHWP";
		Inventory.PickupSound "weapons/waterpistol/get";
	}
	
	States
	{
	Spawn:
		HWPP A 0;
		HWPP A 0 { bDROPPED = 0; }
		HWPP A -1;
		Stop;
	}
}

class MetaHolyWaterPistol : MetaDoomWeapon
{
	Default
	{
		Weapon.SelectionOrder 1900;
		Weapon.AmmoUse 1;
		Weapon.AmmoGive 5;
		Weapon.AmmoType "HolyWater";
		Obituary "$OB_HOLYWATER";
		+WEAPON.WIMPY_WEAPON
		Inventory.Pickupmessage "$GOTHWP";
		Tag "$TAGHWP";
		+WEAPON.AMMO_OPTIONAL
		Inventory.PickupSound "weapons/waterpistol/get";
		scale 0.75;
		Weapon.UpSound "weapons/waterpistol/empty";
		//$Category "Weapons/MetaDoom"
		//$Title "Holy Water Pistol"
		//$NotAngled
		//$Color 14
	}
	
	States
	{
	Ready:
		HWPH A 1 A_WeaponReady;
		"####" A 0 A_JumpIfInventory("MeleePunch", 1, "MeleePunch");
		Loop;
	Deselect:
		HWPH A 0 A_TakeInventory("HolyWaterPistolEquipped",999);
		HWPH A 0 A_JumpIf(health <= 0, "DeadDude");
		HWPH A 0 A_PlaySound("weapons/swap");
	FinishDeselect:
		HWPH A 1 A_SmoothLower();
		Loop;
	Select:
		HWPH A 0 A_OverlayScale(PSP_WEAPON, 1, 1);
		HWPH A 0 A_GiveInventory("HolyWaterPistolEquipped",1);
	FinishSelect:
		HWPH A 1 A_SmoothRaise();
		loop;
	Fire:
		HWPH A 4;
		HWPH A 0 A_JumpIfNoAmmo("NoAmmo");
		HWPH A 0 
		{
			A_Overlay(14, "Overlay.Recoil");
			A_PlaySound("weapons/waterpistol/fire", CHAN_WEAPON);
			
			if (CountInv("PowerMetaDamage") > 0)
			{
				A_PlaySound("powerups/quad/use", CHAN_5);
			}
		}
		HWPH A 1 A_FireProjectile ("HolyWaterShot", frandom(-4,4), 1, 0, 5, FPF_NOAUTOAIM, -5+frandom(-4,4));
		HWPH ABBBBBBBBB 1 A_FireProjectile ("HolyWaterShot", frandom(-4,4), 0, 0, 5, FPF_NOAUTOAIM, -5+frandom(-4,4));
		HWPH BBBBAAAAAA 1 A_FireProjectile ("HolyWaterShot", frandom(-4,4), 0, 0, 5, FPF_NOAUTOAIM, -5+frandom(-4,4));
		HWPH A 4;
		HWPH A 5 ;
		Goto Ready;
	AltFire:
		HWPH A 4;
		HWPH A 0 A_JumpIf(health >= 100, "NoAmmo");
		HWPH A 0 A_JumpIf(CountInv("HolyWater") < 3, "NoAmmo");
		HWPH A 1;
		HWPH A 1 Offset(0,33) A_PlaySound("weapons/swap");
		HWPH A 1 Offset(0,35);
		HWPH A 1 Offset(0,39);
		HWPH B 1 Offset(0,44);
		HWPH B 1 Offset(0,49);
		HWPH B 1 Offset(0,55);
		HWPH B 1 Offset(0,60);
		HWPH B 1 Offset(0,70);
		HWPH B 1 Offset(0,80);
		HWPH B 1 Offset(0,90);
		TNT1 A 10;
		TNT1 A 0 A_TakeInventory("HolyWater", 3);
		TNT1 A 0 A_PlaySound("weapons/waterpistol/heal", CHAN_WEAPON);
		TNT1 A 0 A_GiveInventory("MetaStimpack",1);
		TNT1 A 10;
		TNT1 A 0 A_JumpIf(CountInv("HolyWater") < 3, "Select");
		TNT1 A 0 A_TakeInventory("HolyWater", 3);
		TNT1 A 0 A_PlaySound("weapons/waterpistol/heal", CHAN_WEAPON);
		TNT1 A 0 A_GiveInventory("MetaStimpack",1);
		TNT1 A 10;
		goto Select;
	NoAmmo:
		HWPH A 4
		{
			A_PlaySound("weapons/waterpistol/empty", CHAN_WEAPON);
			A_Overlay(14, "Overlay.RecoilEmpty");
		}
		HWPH A 4;
		HWPH A 4;
		goto Ready;
 	Spawn:
		HWPP Z -1;
		Stop;
	Overlay.Recoil:
		TNT1 A 1 A_WeaponOffset(0, 1, WOF_ADD|WOF_INTERPOLATE);
		TNT1 A 1 A_WeaponOffset(0, 2, WOF_ADD|WOF_INTERPOLATE);
		TNT1 A 1 A_WeaponOffset(0, 3, WOF_ADD|WOF_INTERPOLATE);
		TNT1 A 1 A_WeaponOffset(0, 4, WOF_ADD|WOF_INTERPOLATE);
		TNT1 A 1 A_WeaponOffset(0, 3, WOF_ADD|WOF_INTERPOLATE);
		TNT1 A 1 A_WeaponOffset(0, 2, WOF_ADD|WOF_INTERPOLATE);
		TNT1 A 1 A_WeaponOffset(0, 1, WOF_ADD|WOF_INTERPOLATE);
		TNT1 A 1 A_WeaponOffset(GetShake(), 0.5, WOF_ADD|WOF_INTERPOLATE);
		TNT1 A 1 A_WeaponOffset(GetShake(), 0.25, WOF_ADD|WOF_INTERPOLATE);
		TNT1 A 1 A_WeaponOffset(GetShake(), 0.125, WOF_ADD|WOF_INTERPOLATE);
		TNT1 A 1 A_WeaponOffset(GetShake(), 0.125, WOF_ADD|WOF_INTERPOLATE);
		TNT1 A 1 A_WeaponOffset(0, 0.125, WOF_ADD|WOF_INTERPOLATE);
		TNT1 A 1 A_WeaponOffset(0, 0.125, WOF_ADD|WOF_INTERPOLATE);
		TNT1 A 1 A_WeaponOffset(0, 0.125, WOF_ADD|WOF_INTERPOLATE);
		TNT1 A 1 A_WeaponOffset(0, 0.125, WOF_ADD|WOF_INTERPOLATE);
		TNT1 A 1 A_WeaponOffset(0, 0.125, WOF_ADD|WOF_INTERPOLATE);
		TNT1 A 1 A_WeaponOffset(0, 38, WOF_INTERPOLATE);
		TNT1 A 1 A_WeaponOffset(0, 35, WOF_INTERPOLATE);
		TNT1 A 1 A_WeaponOffset(0, 34, WOF_INTERPOLATE);
		TNT1 A 1 A_WeaponOffset(0, 33, WOF_INTERPOLATE);
		TNT1 A 1 A_WeaponOffset(0, 32.5, WOF_INTERPOLATE);
		TNT1 A 1 A_WeaponOffset(0, 32.25, WOF_INTERPOLATE);
		TNT1 A 1 A_WeaponOffset(0, 32, WOF_INTERPOLATE);
		Stop;
	Overlay.RecoilEmpty:
		TNT1 A 1 A_WeaponOffset(0, 33, WOF_INTERPOLATE);
		TNT1 A 1 A_WeaponOffset(GetShake(), 34, WOF_INTERPOLATE);
		TNT1 A 1 A_WeaponOffset(GetShake(), 35, WOF_INTERPOLATE);
		TNT1 A 1 A_WeaponOffset(0, 34, WOF_INTERPOLATE);
		TNT1 A 1 A_WeaponOffset(0, 32, WOF_INTERPOLATE);
		Stop;
	}
}

class HolyWaterShot : Actor
{
	Default
	{
		Speed 25;
		Height 8;
		Radius 8;
		Mass 1;
		Damage 1;
		Projectile;
		-NOGRAVITY
		Obituary "$OB_HOLYWATER";
		scale 0.25;
		damagetype "HolyWater";
	}
	
	States
	{
	Spawn:
		HWPW A 1 Bright;
		Loop;
	Crash:
	Death:
		TNT1 A 0;
		Stop;
	XDeath:
		TNT1 A 0
		{
			let p = Level.SpawnVisualThinker("MetaHolyWaterPistol_BurnImpact");
			if ( p )
			{
				p.pos = pos;
			}
			S_StartSoundAt(pos, "weapons/waterpistol/burn", CHAN_BODY, volume: 0.5);
		}
		Stop;
	}
}

class HolyWaterFire : Actor
{
	Default
	{
		+NOINTERACTION
		+NOGRAVITY
		RenderStyle "Add";
		Alpha 1;
		scale 0.3;
	}
	
	States
	{
	Spawn:
		FIR2 A 0;
		FIR2 A 0 A_PlaySound("kinsie/waterpistol/flare");
		FIR2 ABCDEH 2 BRIGHT;
		Stop;
	}
}

Class MetaHolyWaterPistol_Sweat : VisualThinker
{
	Vector3 offset;
	Actor target;
	double fallSpeed;
	
	override void PostBeginPlay()
	{
		super.PostBeginPlay();
			
		if ( !target )
		{
			Destroy();
			return;
		}
		
		SetRenderStyle(STYLE_Translucent);
		alpha = 0.0;
		scale = (0.25,0.25)*frandom(0.98,1.02);
		//vel = (frandom(-0.1,0.1), frandom(-0.1,0.1), -1);
		flags = SPF_FULLBRIGHT;
		
		texture = TexMan.CheckForTexture("HWPWA0");
		fallSpeed = -1;
		
		pos.x = target.pos.x + offset.x;
		pos.y = target.pos.y + offset.y;
		pos.z = target.pos.z + offset.z;
	}
	
	int timer;
	
	override void Tick()
	{
		if ( bDESTROYED )
			return;
			
		if ( !target )
		{
			Destroy();
			return;
		}
	
		super.Tick();
		
		if ( timer < 12 )
		{
			scale.y += 0.01;
			if ( alpha < 1.0 )
			{
				alpha += 0.25;
			}
		}
		else
		{
			if ( alpha <= 0.0 )
			{
				Destroy(); return;
			}
			
			fallSpeed -= 0.5;
			alpha -= 0.1;
			scale.y += 0.05;
		}
		pos.x = target.pos.x + offset.x;
		pos.y = target.pos.y + offset.y;
		pos.z = target.pos.z + offset.z;
		offset.z += fallSpeed;
		timer++;
	}
}

Class MetaHolyWaterPistol_BurnImpact : VisualThinker
{
	static const string frames[] =
	{
		"PUFFA0",
		"PUFFB0",
		"graphics/fx/smoothpuff1.png",
		"graphics/fx/smoothpuff2.png",
		"graphics/fx/smoothpuff3.png",
		"graphics/fx/smoothpuff4.png",
		"graphics/fx/smoothpuff5.png"
	};
	
	int stagger;
	int frame;
	
	override void PostBeginPlay()
	{
		super.PostBeginPlay();
		//SetRenderStyle(STYLE_Translucent);
		SetRenderStyle(STYLE_Translucent);
		roll = random(0,3)*90;
		alpha = 1.0;//+frandom(-0.05,0.05);
		scale = (0.5,0.5);
		//scolor = "#818181";
		vel = (frandom(-0.25,0.25), frandom(-0.25,0.25), frandom(-0.25,0.25));
		UpdateSprite();
		
		//texture = TexMan.CheckForTexture("graphics/fx/spark.png");
	}
	
	void UpdateSprite()
	{
		texture = TexMan.CheckForTexture(frames[frame]);
		flags = frame <= 1 ? SPF_FULLBRIGHT : 0;
	}
	
	override void Tick()
	{
		if ( bDESTROYED )
			return;
	
		super.Tick();
		
		stagger += 1;
		if ( stagger >= 5 )
		{
			stagger = 0;
			frame += 1;
			if ( frame >= frames.Size() )
			{
				Destroy();
				return;
			}
			UpdateSprite();
		}
		
		alpha -= 0.01;
		
		scale.x += 0.01;
		scale.y += 0.01;
		
		vel.x *= 0.9;
		vel.y *= 0.9;
		vel.z += 0.1;
	}
}

Class MetaHolyWaterPistol_BurnSmoke : VisualThinker
{
	static const string frames[] =
	{
		"graphics/fx/smoothpuff1.png",
		"graphics/fx/smoothpuff2.png",
		"graphics/fx/smoothpuff3.png",
		"graphics/fx/smoothpuff4.png",
		"graphics/fx/smoothpuff5.png"
	};
	
	int stagger;
	int frame;
	
	override void PostBeginPlay()
	{
		super.PostBeginPlay();
		//SetRenderStyle(STYLE_Translucent);
		SetRenderStyle(STYLE_Translucent);
		roll = random(0,3)*90;
		alpha = 1.0;//+frandom(-0.05,0.05);
		scale = (0.5,0.5);
		//scolor = "#818181";
		vel = (frandom(-0.25,0.25), frandom(-0.25,0.25), frandom(-0.25,0.25));
		UpdateSprite();
		
		//texture = TexMan.CheckForTexture("graphics/fx/spark.png");
	}
	
	void UpdateSprite()
	{
		texture = TexMan.CheckForTexture(frames[frame]);
	}
	
	override void Tick()
	{
		if ( bDESTROYED )
			return;
	
		super.Tick();
		
		stagger += 1;
		if ( stagger >= 5 )
		{
			stagger = 0;
			frame += 1;
			if ( frame >= frames.Size() )
			{
				Destroy();
				return;
			}
			UpdateSprite();
		}
		
		alpha -= 0.01;
		
		scale.x += 0.01;
		scale.y += 0.01;
		
		vel.x *= 0.9;
		vel.y *= 0.9;
		vel.z += 0.1;
	}
}

class HolySweat : Actor
{
	Default
	{
		Radius 2;
		Height 4;
		+NOBLOCKMAP 
		+MISSILE 
		+DROPOFF
		+NOTELEPORT
		+LOWGRAVITY
		+CANNOTPUSH
		+DONTSPLASH
		+DONTBLAST
		alpha 0.75;
	}
	
	States
	{
	Spawn:
		SWET A 0;
		SWET A 0 ThrustThingZ(0,8,0,1);
		SWET ABC 8;
		SWET D 16;
		Stop;
	Death:
		TNT1 A 0;
		Stop;
	}
}