/*
----------------------------
MetaDoom
Actor Definitions
Fire Axe
----------------------------
*/

class MetaAxePickup : WeaponGiver
{
	Default
	{
		DropItem "MetaAxe";
		Inventory.PickupMessage "$GOTAXE";
		Inventory.PickupSound "weapons/axe/get";
	}
	States
	{
	Spawn:
		AXEG Z 0;
		AXEG Z 0 { bDROPPED = 0; }
		AXEG Z -1;
		Stop;
	}
}

class MetaAxe : MetaDoomMeleeWeapon
{
	Default
	{
		Weapon.SelectionOrder 2400;
		Weapon.Kickback 100;
		Obituary "$OB_AXE";
		Tag "$TAGAXE";
		+WEAPON.WIMPY_WEAPON
		+WEAPON.MELEEWEAPON
		+WEAPON.NOALERT
		Inventory.PickupMessage "$GOTAXE";
		Inventory.PickupSound "weapons/axe/get";
		Weapon.UpSound "weapons/axe/use";
		//$Category "Weapons/MetaDoom"
		//$Title "Fire Axe"
		//$NotAngled
		//$Color 14
		
		MetaDoomMeleeWeapon.ChargeTime 70;
	}
	
	Vector2 windup_start;
	int windup;
	
	States
	{
		Ready:
			AXEG A 1 A_WeaponReady;
			"####" A 0 A_JumpIfInventory("MeleePunch", 1, "MeleePunch");
			Loop;
		Deselect:
			AXEG A 0 A_JumpIf(health <= 0, "DeadDude");
			AXEG A 0 A_PlaySound("weapons/swap");
		FinishDeselect:
			AXEG A 1 A_SmoothLower();
			Loop;
		Select:
			AXEG A 0 A_OverlayScale(PSP_WEAPON, 1, 1);
			AXEG A 1 A_SmoothRaise();
			loop;
		AltFire:
		Fire:
			TNT1 A 0 A_PlaySound("weapons/swap", CHAN_AUTO, 0.5);
		WindUp:
			AXEG A 0
			{
				invoker.windup_start = (0,32);
				invoker.windup = 0;
				
				let recoil = new("Meta_RecoilInfo");
				recoil.tics_in = 7;
				recoil.tics_out = 7;
				recoil.pitch = 1;
				recoil.yaw = -0.75;
				A_MetaRecoil(recoil);
			}
			AXEG AAABBB 1
			{
				double progress = (invoker.windup/4.);
				progress = progress * progress * progress;
				double x = invoker.windup_start.x + ( 256 - invoker.windup_start.x ) * progress;
				double y = invoker.windup_start.y + ( 32 - invoker.windup_start.y ) * progress;
				
				A_WeaponOffset(x, y, WOF_INTERPOLATE);
				invoker.windup += 1;
			}
			Goto QuickMelee;
		QuickMelee:
			AXEG A 0 A_WeaponOffset(0,32);
			TNT1 A 2 A_WeaponOffset(0,32);
			AXEG I 1
			{
				
				let recoil = new("Meta_RecoilInfo");
				recoil.tics_in = 3;
				recoil.tics_out = 18;
				recoil.pitch = -2;
				recoil.yaw = 0.75*2;
				recoil.roll = -0.25;
				recoil.yaw_speed = random(25,30);
				recoil.yaw_shake = 0.2;
				recoil.roll_speed = random(30,35);
				recoil.roll_shake = 0.3;
				A_MetaRecoil(recoil);
				A_PlaySound("weapons/axe/fire");
				A_Overlay(135, "Overlay.QuickMeleeOffset");
				
				if (CountInv("PowerMetaDamage") > 0)
				{
					A_PlaySound("powerups/quad/use", CHAN_5);
				}
			}
			AXEG CCC 1;
			AXEG D 1 A_CustomPunch(7 * random(1, 5), TRUE, CPF_NOTURN,"MetaAxePuff",80,0,0,"BasicArmorBonus","weapons/axe/hit");
			AXEG DD 1;
			AXEG E 10;
			"----" A 0 A_JumpIfQuickMelee("Deselect");
			AXEG A 1 A_WeaponOffset(0,90,WOF_INTERPOLATE);
			AXEG A 1 A_WeaponOffset(0,70,WOF_INTERPOLATE);
			AXEG A 1 A_WeaponOffset(0,55,WOF_INTERPOLATE);
			AXEG A 1 A_WeaponOffset(0,44,WOF_INTERPOLATE);
			AXEG A 1 A_WeaponOffset(0,35,WOF_INTERPOLATE);
			AXEG A 1 A_WeaponOffset(0,33,WOF_INTERPOLATE);
			AXEG A 1 A_WeaponOffset(0,32,WOF_INTERPOLATE);
			Goto Ready;
		Overlay.QuickMeleeOffset:
			TNT1 A 1 A_WeaponOffset(333.58, -6.89, WOF_INTERPOLATE);
			TNT1 A 1 A_WeaponOffset(320.08, -5.09, WOF_INTERPOLATE);
			TNT1 A 1 A_WeaponOffset(299.21, 0.20, WOF_INTERPOLATE);
			TNT1 A 1 A_WeaponOffset(267.30, 9.90, WOF_INTERPOLATE);
			TNT1 A 1 A_WeaponOffset(217.59, 25.34, WOF_INTERPOLATE);
			TNT1 A 1 A_WeaponOffset(139.04, 48.56, WOF_INTERPOLATE);
			TNT1 A 1 A_WeaponOffset(34.74, 82.72, WOF_INTERPOLATE);
			TNT1 A 1 A_WeaponOffset(-52.45, 131.82, WOF_INTERPOLATE);
			TNT1 A 1 A_WeaponOffset(-109.31, 193.05, WOF_INTERPOLATE);
			TNT1 A 1 A_WeaponOffset(-146.39, 238.44, WOF_INTERPOLATE);
			TNT1 A 1 A_WeaponOffset(-171.27, 250.93, WOF_INTERPOLATE);
			Stop;
		Spawn:
			AXEG Z -1;
			Stop;
	}
}

class MetaAxePuff : Actor
{
	Default
	{
		+NOBLOCKMAP
		+NOGRAVITY
		+ALLOWPARTICLES
		+RANDOMIZE
		damagetype "Axe";
		RenderStyle "Translucent";
		Alpha 0.5;
		VSpeed 1;
		Mass 5;
		AttackSound "weapons/axe/hitwall";
		SeeSound "weapons/axe/hit";
		Obituary "$OB_AXE";
	}
	States
	{
	Spawn:
		PUFF A 4 Bright;
		PUFF B 4;
	Melee:
		PUFF CD 4;
		Stop;
	}
}