/*
----------------------------
MetaDoom
ZScript
Omni Event Handler
----------------------------
*/

// Handles most event-related things.

Class MetaDoom_ShaderInfo
{
	string shaderName;
	bool active;
	Class<Inventory> check;
	double amount;
}// Classes relating to running the game

Class MetaDoom_GameBrain : Thinker
{
	int maps_cleared;
	
	bool is_episodic;
	
	MetaDoom_GameBrain Init()
	{
		ChangeStatNum(STAT_STATIC);
		return self;
	}

	static MetaDoom_GameBrain Get()
	{
		ThinkerIterator it = ThinkerIterator.Create("MetaDoom_GameBrain", STAT_STATIC); 
		let brain = MetaDoom_GameBrain(it.Next());
		
		if ( !brain )
		{
			brain = new("MetaDoom_GameBrain").Init();
		}
		return brain;
	}
	
	bool IsEpisodic()
	{
		return is_episodic;
	}
	
	int GetMapsCleared()
	{
		return maps_cleared;
	}
}

Class Meta_StaticEventHandler : EventHandler
{
	Array<MetaDoom_ShaderInfo> shaders;
	
	override void OnRegister()
	{
		MetaDoom_ShaderInfo shader;
		
		shader = new("MetaDoom_ShaderInfo");
		shader.shaderName = "MetaDoom_HellTime";
		shader.check = "MetaArtifact_IsActive";
		shaders.Push(shader);
	}
	
	// COOL SHADER SHITE
	
	ui double lastMS;
	
	override void UiTick()
	{
		double time_diff = MSTimeF() - lastMS;
		lastMS = MSTimeF();
		
		double deltatime = time_diff / (1000. / 60.);
		
		let player = players[consoleplayer].mo;
		
		for ( int i = 0; i < shaders.Size(); i++ )
		{
			if ( player && player.CountInv(shaders[i].check) > 0 )
			{
				shaders[i].amount += deltatime*0.1;
			}
			else
			{
				shaders[i].amount -= deltatime*0.1;
			}
			shaders[i].amount = clamp(shaders[i].amount, 0.0, 1.0);
			PPShader.SetEnabled(shaders[i].shaderName, shaders[i].amount > 0.0);
			PPShader.SetUniform1f(shaders[i].shaderName, "md_timer", MSTimeF()/1000.);
			PPShader.SetUniform1f(shaders[i].shaderName, "md_amount", shaders[i].amount);
		}
	}
}

Class Meta_OmniEventHandler : EventHandler
{
	bool Meta_ThingExists(name clsname)
	{
		class<Actor> pclass = clsname;

		if(pclass == null)
		{
			return false;
		}

		return true;
	}
	
	override void WorldLoaded(WorldEvent e)
	{
		let brain = MetaDoom_GameBrain.Get();
		if ( _metadebug_forcemaps >= 0 )
		{
			brain.maps_cleared = _metadebug_forcemaps;
		}
		brain.is_episodic = level.mapname.Left(1) == "E" && ( level.mapname.ByteAt(1) >= 48 && level.mapname.ByteAt(1) < 58 );
		//Console.Printf("Is Episodic: "..brain.is_episodic);
	}
	
	override void WorldUnloaded(WorldEvent e)
	{
		let brain = MetaDoom_GameBrain.Get();
		brain.maps_cleared += 1;
	}
	
	/*override void CheckReplacee (ReplacedEvent e)
	{
		let metaMonster = MonsterCore(GetDefaultByType(e.Replacement));
		if ( metaMonster )
		{
			Console.Printf(""..metaMonster.replacee);
			e.Replacee = metaMonster.replacee;
		}
	}*/
	
	override void WorldThingDied (WorldEvent e)
	{
		if ( e.Thing.target==null||!(e.Thing.target is "PlayerPawn") )
		{
			return;
		}
		if ( !multiplayer && Meta_ThingExists(e.Thing.GetClassName()) && Meta_ThingExists("MetaCodex_"..e.Thing.GetClassName()) )
		{
			if(e.Thing.target.player!=null&&e.Thing.target.player==players[consoleplayer]&&!e.Thing.target.FindInventory("MetaCodex_"..e.Thing.GetClassName()))
			{
				//I can't figure out a way to make this work for weapons...
				/*Console.Printf("\cgNew Codex Entry!");
				e.Thing.target.A_PlaySound("misc/getcodex",CHAN_ITEM|CHAN_UI);*/
				e.Thing.target.SetInventory("MetaCodex_"..e.Thing.GetClassName(),1);
			}
		}
	}
	
	override void WorldTick()
	{
		/*if(multiplayer==true)
		{
			return;
		}*/
		/*if(!multiplayer && level.maptime%35==0)
		{
			if(players[consoleplayer].mo.FindInventory("MetaBerserkFist"))
			{
				players[consoleplayer].mo.GiveInventory("MetaCodex_MetaBerserk",1);
			}
			if(players[consoleplayer].mo.FindInventory("PowerMetaIronFeet"))
			{
				players[consoleplayer].mo.GiveInventory("MetaCodex_MetaRadSuit",1);
			}
			if(players[consoleplayer].mo.FindInventory("PowerMetaLightAmp"))
			{
				players[consoleplayer].mo.GiveInventory("MetaCodex_MetaLightAmp",1);
			}
			if(players[consoleplayer].mo.FindInventory("PowerMetaSpeed"))
			{
				players[consoleplayer].mo.GiveInventory("MetaCodex_MetaHasteSphere",1);
			}
			if(players[consoleplayer].mo.FindInventory("PowerMetaDamage"))
			{
				players[consoleplayer].mo.GiveInventory("MetaCodex_MetaQuadDamage",1);
			}
			if(players[consoleplayer].mo.FindInventory("PowerMetaInvulnerable"))
			{
				players[consoleplayer].mo.GiveInventory("MetaCodex_MetaInvulnerabilitySphere",1);
			}
			if(level.allmap == true)
			{
				players[consoleplayer].mo.GiveInventory("MetaCodex_MetaAllmap",1);
			}
			if(players[consoleplayer].mo.FindInventory("Backpack2"))
			{
				players[consoleplayer].mo.GiveInventory("MetaCodex_Backpack2",1);
			}
		}*/
	}
	
	override void NetworkProcess (ConsoleEvent e)
	{
		if ( e.name.IndexOf("metadoom") != 0 ) return;
		
		Array<string> cmds;
		e.name.Split(cmds, ":");
		
		if ( cmds.Size() < 2 ) return;
		
		let player = players[e.Player];
		
		if ( cmds[1] ~== "swapinv" )
		{
			MetaDoomPlayer(player.mo).SwapInventory();
			return;
		}
		
		if ( cmds[1] ~== "quickmelee" )
		{
			MetaDoomPlayer(player.mo).QuickMelee();
			return;
		}
	}
}