/*
----------------------------
MetaDoom
Actor Definitions
Marauder
----------------------------
*/

class MetaMarauderSpawner : Actor
{
	Default
	{
		radius 64;
		height 64;
		-SOLID
		+ISMONSTER
		+COUNTKILL
		//$Category "Monsters/MetaDoom/Marauder"
		//$Title "Marauder Portal (Proximity Based)"
		//$Color 12
		//$Sprite PARUA0
	}
	
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 1 A_SetTics(random(0,3));
			TNT1 A 1
			{
				BlockThingsIterator it = BlockThingsIterator.Create(self,128,0);
				while (it.Next())
				{
					Actor mo = it.thing;
					
					if (mo is "PlayerPawn")
					{
						if (meta_developer)
							Console.printf("Marauder spawner too close to player start, waiting...");
						SetStateLabel("WaitADamnSec");
						break;
					} else if (mo is "MetaMarauderSpawner" && mo != self)
					{
						if (meta_developer)
							Console.printf("Marauder spawner too close to other spawner, killing off");
						ClearCounters();
						Destroy();
						break;
					}
				}
			}
			goto Watch;
		WaitADamnSec:
			TNT1 A 2100;
			goto Watch;
		Watch:
			TNT1 A 1 A_LookEx (0, 0, 512, 640, 360, "SpawnShit");
			loop;
		SpawnShit:
			TNT1 A 0 A_FaceTarget();
			TNT1 A 0 
			{
				A_SpawnItemEx("MetaMarauderPortal", 0, 0, 0, 0, 0, 0, 0, SXF_SETTARGET);
				ClearCounters();
			}
			stop;
	}
}

class MetaMarauderPortal : Actor
{
	Default
	{
		radius 64;
		height 64;
		scale 0.001;
		//renderstyle "Add";
		-SOLID
		-NOBLOCKMAP
		+NOGRAVITY
		+ROLLSPRITE
		+ROLLCENTER
		+INTERPOLATEANGLES
		+ISMONSTER
		+COUNTKILL
	}
	
	states
	{
	Spawn:
		PARU A 0;
		PARU A 0
		{
			A_StartSound("monsters/marauder/portal/open", CHAN_AUTO, 0, 1.0, ATTN_NONE);
		}
	Open:
		PARU A 1 BRIGHT
		{
			A_FaceTarget();
			
			if (scale.x < 2.0)
			{
				A_SetScale(scale.x + 0.1);
			} else {
				SetStateLabel("SpawnBadMan");
			}
		}
		loop;
	SpawnBadMan:
		PARU A 35 BRIGHT;
		PARU A 16 BRIGHT
		{
			A_FaceTarget();
			A_StartSound("monsters/marauder/portal/enter", CHAN_AUTO, 0, 1.0, ATTN_NONE);
			A_SpawnItemEx("MetaMarauder", 0, 0, 0, 0, 0, 0, 0, SXF_SETTARGET);
			ClearCounters();
		}
		PARU A 0
		{
			A_StartSound("monsters/marauder/portal/close", CHAN_AUTO, 0, 1.0, ATTN_NONE);
		}
		goto Close;
	Close:
		PARU A 1 BRIGHT
		{
			if (scale.x > 0.001)
			{
				A_SetScale(scale.x - 0.1);
			} else {
				A_Remove(AAPTR_DEFAULT, RMVF_EVERYTHING);
			}
		}
		loop;
	}
	
	override void Tick()
	{
		roll = roll + 8;
		
		Super.Tick();
	}
}

class MetaMarauder : MonsterCore
{
	Default
	{
		Health 700;
		Radius 20;
		Height 56;
		Speed 8;
		PainChance 255;
		Monster;
		+FLOORCLIP
		-DOHARMSPECIES
		+NODAMAGE
		+NOBLOOD
		+LOOKALLAROUND
		+DROPOFF
		+NOBLOCKMONST
		+BLOCKASPLAYER
		DropItem "BFGAmmo";
		DeathSound "monsters/marauder/die";
		PainSound "monsters/marauder/pain";
		Obituary "$OB_MARAUDER";
		damagefactor "HolyWater", 0;
		painchance "HolyWater", 0;
		painchance "Axe", 0;
		damagefactor "ChaingunTurret", 0.2;
		damagefactor "Vampire", 0.25;
		damagefactor "Tesla", 0.25;
		MonsterCore.CanBeScared false;
		Tag "Marauder";
		//$Category "Monsters/MetaDoom/Marauder"
		//$Title "Marauder"
		//$Color 12
	}
	
	bool stunned;
	bool shielding;
	int shielddamage;
	int dodgedir;
	
	const DISTANCE_SHOTGUN = 192;
	const DISTANCE_SWEETSPOT = 324;
	
	States
	{
	Spawn:
		MARU A 10 A_Look;
		Loop;
	See:
		MARU A 0
		{
			if ( !target )
			{
				SetStateLabel("SeeFast");
				return;
			}
			
			/*if ( self.pos.z != self.floorz )
			{
				SetStateLabel("SeeFast");
				return;
			}*/
			
			if ( CheckSight(target) && Distance3D(target) <= DISTANCE_SWEETSPOT )
			{
				SetStateLabel("SeeSidestep");
				return;	
			}
			
			SetStateLabel("SeeFast");
			return;
		}
		//MARU A 0 A_Jump (256, "SeeDodgy", "SeeFast");
	SeeSidestep:
		MARU A 1 A_MarauderSidestep();
		Wait;
	SeeSidestepLeft:
		MARU FFFFFGGGGGHHHHH 1 A_MarauderSidestep();
		goto See;
	SeeSidestepRight:
		MARU IIIIIJJJJJKKKKK 1 A_MarauderSidestep();
		goto See;
	SeeFast:
		MARU A 0 { speed = 12; }
		MARU BBBBBCCCCCDDDDDEEEEE 1 A_MarauderChase();
		goto See;
	Dodge:
		MARU B 0 A_StartSound("monsters/marauder/dodge", CHAN_BODY);
		MARU BBBBBBBBBB 1
		{
			vel.x *= 0.85;
			vel.y *= 0.85;
			MetaMarauder_AfterImage.Spawn(self);
			A_FaceTarget();
		}
		MARU AAAAAA 1
		{
			vel.x *= 0.85;
			vel.y *= 0.85;
			A_FaceTarget();
		}
		Goto See;
	Missile:
		Goto MissileAxe;
	MissileShotgun:
		MARU E 10 A_FaceTarget;
		MARU F 10 BRIGHT
		{
			A_FaceTarget();
			A_SpawnProjectile("MonsterShotgunGuyTracer",32,0,random(-16,16),CMF_OFFSETPITCH,random(-4,4));
			A_SpawnProjectile("MonsterShotgunGuyTracer",32,0,random(-16,16),CMF_OFFSETPITCH,random(-4,16));
			A_SpawnProjectile("MonsterShotgunGuyTracer",32,0,random(-16,16),CMF_OFFSETPITCH,random(-4,4));
			A_SpawnProjectile("MonsterShotgunGuyTracer",32,0,random(-2,2),CMF_OFFSETPITCH,random(-2,2));
			A_PlaySound("monsters/marauder/fire");
		}
		MARU E 10 A_FaceTarget;
		Goto See;
	MissileAxe:
		MARU LM 4 A_FaceTarget;
		MARU N 8 BRIGHT
		{
			A_SpawnProjectile("MetaMarauderAxe");
			A_PlaySound("monsters/marauder/effort");
		}
		MARU A 8;
		Goto See;
	MissileSweetSpot:
		MARU O 4
		{
			A_Stop();
			A_FaceTarget();
			//A_Recoil(-32);
			A_PlaySound("monsters/marauder/eyeflare");
			A_SpawnItemEx("MetaMarauderEyeflash", 1, 0, 56, 0, 0, 0, SXF_SETMASTER);
			
			bFORCEPAIN = 1;
			bNODAMAGE = 0;
			bNOBLOOD = 0;
		}
		MARU O 0 
		{
			A_StartSound("monsters/marauder/axe/charge");
			A_StartSound("monsters/marauder/charge", CHAN_VOICE);
		}
		MARU OPPQQ 3 
		{
			A_FaceTarget();
			A_Recoil(-8);
		}
		MARU R 2
		{
			A_Stop();
			A_CustomMeleeAttack(random(1, 10) * 6, "monsters/marauder/axe/hitactor");
		}
		MARU SSS 1
		{
			SpriteOffset.x = level.maptime % 2 == 0 ? -1 : 1;
		}
		MARU S 3
		{
			SpriteOffset.x = 0;
		}
		MARU A 0
		{
			bFORCEPAIN = 0;
			bNODAMAGE = 1;
			bNOBLOOD = 1;
		}
		Goto See;
	MissileNoChargeWall:
		MARU J 0 
		{
			A_Recoil(-8);
			shielddamage = 101;
		}
		goto PainShield;
	Pain.Vampire:
	Pain.LightningStun:
	Pain.Axe:
	Pain.Fist:
	Pain.BerserkFist:
	Pain.KrautBoot:
	Pain.ChainsawMelee:
	Pain:
		MARU A 0
		{
			SpriteOffset.x = 0;
			if (bNODAMAGE)
			{
				SetStateLabel("PainShield");
			} else {
				SetStateLabel("Stunned");
			}
		}
		goto See;
	PainShield:
		MARU J 0
		{
			bInvulnerable = true;
		}
		MARU J 0
		{
			if (!shielding)
			{
				A_SpawnItemEx("MetaMarauderShield", 16, 0, 3, 0, 0, 0, SXF_SETMASTER);
				shielding = true;
				A_StartSound("monsters/marauder/shield");
			}
		}
		MARU JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ 1
		{
			A_FaceTarget();
		}
		MARU O 0
		{
			bInvulnerable = false;
			A_RemoveChildren(true, RMVF_EVERYTHING, "MetaMarauderShield");
			shielding = false;
			
			if (shielddamage > 100)
			{
				SetStateLabel("Summon");
			}
			
			shielddamage = 0;
		}
		Goto See;
		
	Stunned:
		MARU A 0
		{
			bNOPAIN = 1;
			bNODAMAGE = 0;
			bNOBLOOD = 0;
			
			stunned = true;
			
			A_SpawnItem("HolySweat",0,height-2);
			
			A_Pain();
		}
		MARU Q 4;
		MARP ABACABACABAC 4;
		MARU A 8
		{
			bNOPAIN = 0;
			bNODAMAGE = 1;
			bNOBLOOD = 1;
			
			stunned = false;
			
			A_FaceTarget();
			ReactionTime = random(15,70);
			A_MarauderDodge(random(-90,90));
		}
		goto See;
		
	Summon:
		MARU G 0;
		MARU G 0
		{
			shielddamage = 0;
			
			A_StartSound("monsters/summoner/popcorn", CHAN_VOICE);
			
			A_SpawnItemEx("MetaMarauderPopcorn",0,0,2,4,0,0,90);
			A_SpawnItemEx("MetaMarauderPopcorn",0,0,2,4,0,0,270);
		}
		MARU GHI 4 BRIGHT;
		Goto See;
		
	Death:
		MARU R 0 { bSPRITEFLIP = random(0,1); } // random chance of sprite flipping
		TNT1 A 0 
		{
			SpriteOffset.x = 0;
			A_SpawnItem("SoulSpawner");
			
			A_MetaPinata("MetaHealthPinataPerm", 4);
			A_MetaPinata("MetaArmorPinata", 4);
			A_MetaPinata("MetaPinataClip", 4);
			A_MetaPinata("MetaPinataShell", 4);
			A_MetaPinata("MetaPinataRocket", 4);
			A_MetaPinata("MetaPinataCell", 4);
			
			A_KillChildren();
		}
		MARU R 5 A_GiveToTarget("ScoreItem", 8000);
		MARU S 5 A_Scream;
		MARU T 5 A_NoBlocking;
		MARU UVWX 5;
		MARU Y -1 A_PlaySound("bodyfalls/heavy");
		Stop;
	XDeath:
		TNT1 A 0 
		{
			SpriteOffset.x = 0;
			A_SpawnItem("SoulSpawner");
			
			A_MetaPinata("MetaHealthPinataPerm", 4);
			A_MetaPinata("MetaArmorPinata", 4);
			A_MetaPinata("MetaPinataClip", 4);
			A_MetaPinata("MetaPinataShell", 4);
			A_MetaPinata("MetaPinataRocket", 4);
			A_MetaPinata("MetaPinataCell", 4);
			
			A_KillChildren();
		}
		MARU R 5 A_GiveToTarget("ScoreItem", 8000);
		"####" # 0 A_Fall;
		TNT1 A 0 A_SpawnItemEx("MetaGibber",0,0,0,0,0,0,0,SXF_TRANSFERPOINTERS);
		Stop;
	}
	
	override int DamageMobj(Actor inflictor, Actor source, int damage, Name mod, int flags, double angle)
	{
		// Stop Marauder from getting stunned by nearby enemies when attacking player
		// [Py] Let's make this a little more specific so that co-op players can spitroast the marauder if desired
		// [Py] Very popular strategy look up Two Doomguys Spitroast a Marauder on illicit websites
		bool sourceIsPlayer = source && source.player != null;
		if ( !shielding && !sourceIsPlayer )
		{
			damage = 0;
		}
		
		if ( stunned )
		{
			A_Pain();
		}
		
		if ( shielding )
		{
			shielddamage = shielddamage + damage;
		}
		
		return Super.DamageMobj(inflictor, source, damage, mod, flags, angle);
	}
	
	override void Tick()
	{
		A_TakeInventory("BleedingCounter", 99999);
		Super.Tick();
	}	
	
	void A_MarauderChase(statelabel melee = "Melee", statelabel missile = "Missile", int flags = 0)
	{
		//DoClimbing();
		dodgedir = 0;
		
		if ( target == null ) return;
		
		if ( A_MarauderTryAttack() ) return;
		
		Vector3 diff = level.Vec3Diff(pos, target.pos);
		int dist = diff.Length();
		
		if ( dist <= DISTANCE_SWEETSPOT )
		{
			SetStateLabel("SeeSidestep");
			return;
		}
		
		let tracer = new('LineTracer');
		tracer.Trace(pos+(0,0,height/2), cursector, diff.Unit(), 256, TRACE_HitSky, Line.ML_BLOCKEVERYTHING, false, self);
		let res = tracer.results;
		
		if ( res.HitType != TRACE_HitNone || ( res.HitType == TRACE_HitActor && res.HitActor != target ) )
		{
			A_Chase(null, null);
			return;
		}
		
		if ( !TryMove(pos.xy+(diff.xy.Unit())*speed, 24) )
		{
			A_Chase(null, null);
			return;
		}
		
		A_FaceTarget();
		//A_MarauderChase("Missile","Missile");
		//A_MetaChase(null, null, flags);
	}
	
	void A_MarauderSidestep()
	{
		if ( target == null ) return;
		
		A_FaceTarget();
		
		if ( A_MarauderTryAttack() ) return;
		
		Vector3 diff = level.Vec3Diff(pos, target.pos);
		int dist = diff.Length();
		
		// [Py] Don't stand so close to me!
		if ( dist <= 112 )
		{
			A_MarauderDodge(random(-90,90));
			return;
		}
		
		speed = 8;
		
		if ( dist <= DISTANCE_SHOTGUN )
		{
			speed = 4;
			switch ( frame )
			{
				case 5: frame = 19; break;
				case 6: frame = 20; break;
				case 7: frame = 21; break;
				case 8: frame = 22; break;
				case 9: frame = 23; break;
				case 10: frame = 24; break;
			}
		}
		
		if ( dodgedir == 0 )
		{
			dodgedir = random(0,1) ? 1 : -1;
		}
		
		if ( dodgedir < 0 && !InStateSequence(CurState, resolveState("SeeSidestepLeft")) )
		{
			SetStateLabel("SeeSidestepLeft");
			return;
		}
		if ( dodgedir > 0 && !InStateSequence(CurState, resolveState("SeeSidestepRight")) )
		{
			SetStateLabel("SeeSidestepRight");
			return;
		}
		
		double angler = AngleTo(target) + (90+sin(GetAge()*15))*dodgedir;
		
		if ( !TryMove(pos.xy + (cos(angler),sin(angler)) * speed, 24) )
		{
			A_Chase(null, null);
			A_FaceTarget();
		}
	}
	
	bool TryDodgeInDirection(double angler)
	{
		if ( CheckMove(pos.xy + (cos(angler)*radius, sin(angler)*radius)) )
		{
			SetStateLabel("Dodge");
			vel += (cos(angler)*32, sin(angler)*32, 0);
			A_FaceTarget();
			return true;
		}
		return false;
	}
	
	void A_MarauderDodge(double angleOffset = 0)
	{
		if ( target == null ) return;
		
		int startDir = random(0,1) ? -1 : 1;
		
		for ( double angler = angleOffset; abs(angler) < 90; angler += 15*startDir )
		{
			double angleCheck = (AngleTo(target)+180) + angler;
			if ( TryDodgeInDirection(angleCheck) ) return;
		}
		
		startDir *= -1;
		
		for ( double angler = angleOffset; angler < -90; angler += 15*startDir )
		{
			double angleCheck = (AngleTo(target)+180) + angler;
			if ( TryDodgeInDirection(angleCheck) ) return;
		}
	}
	
	bool A_MarauderTryAttack()
	{
		if ( !target ) return false;
		
		int dist = Distance3D(target);
		
		if ( ReactionTime > 0 )
		{
			ReactionTime--;
			ReactionTime = max(0, ReactionTime);
		}
		
		if ( dist > 1536 ) return false;
		
		if ( ReactionTime > 0 || !CheckSight(target) || random(0,5) != 0 ) return false;
		
		if ( dist <= DISTANCE_SHOTGUN )
		{
			SetStateLabel("MissileShotgun");
			ReactionTime = 55;
			return true;
		}
		else if ( dist <= DISTANCE_SWEETSPOT )
		{
			SetStateLabel("MissileSweetSpot");
			ReactionTime = 55;
			return true;
		}
		
		SetStateLabel("MissileAxe");
		ReactionTime = 45;
		return true;
	}
	
	virtual void DoClimbing()
	{
		FLineTraceData SurfaceData;
		self.LineTrace(self.angle, 72, 0, TRF_THRUACTORS, offsetz: MaxStepHeight + 2, data:SurfaceData);
		
		if (health > 0 && pos.z == floorz
		&& SurfaceData.HitType == SurfaceData.TRACE_HitWall
		&& SurfaceData.LinePart == Side.bottom)
		{
			if (SurfaceData.HitLine.Flags & Line.ML_TWOSIDED)
			{
				FLineTraceData ConfirmData;
				
				for (int i = self.height; i < 170; i = i + 10)
				{
					self.LineTrace(self.angle, SurfaceData.Distance + 16, 0, TRF_THRUACTORS|TRF_BLOCKSELF, offsetz: i, data:ConfirmData);
				
					if (ConfirmData.HitType == SurfaceData.TRACE_HitNone)
					{
						if (meta_developer)
							Console.printf("Height: %i, Vel: %f", i, (i / 6));
						self.vel.z = i / 6;
						A_FaceTarget();
						A_Recoil(-3);
						break;
					} else {				
						
					}
				}
			}
		}
	}
}

class MetaMarauderAxe : Actor 
{
	Default
	{
		Radius 10;
		Height 8;
		Speed 18;
		Damage 2;
		Projectile;
		-NOBLOCKMAP
		-ACTIVATEIMPACT
		-ACTIVATEPCROSS
		+WINDTHRUST
		+THRUGHOST
		DeathSound "monsters/marauder/axe/hitworld";
	}

	States
	{
	Spawn:
		SPAX A 3 BRIGHT A_StartSound("monsters/marauder/axe/fly");
		SPAX BC 3 BRIGHT;
		Loop;
	Death:
		SPAX DEF 6 BRIGHT;
		Stop;
	}
}

class MetaMarauderShield : Actor
{
	Default
	{
		-SOLID
		+WALLSPRITE
		+NOGRAVITY
	}
	
	States
	{
		Spawn:
			MARS AB 1 BRIGHT
			{
				if (target)
				{
					master = target;
					A_Warp(AAPTR_TARGET, 16, 0, 3, target.angle, WARPF_ABSOLUTEANGLE);
				}
			}
			Loop;
	}
}

class MetaMarauderPopcorn : Actor
{
	Default
	{
		+CANBOUNCEWATER
		Radius 20;
		Height 56;
		Speed 20;
		Damage 0;
		PROJECTILE;
		+RANDOMIZE
		+NOGRAVITY
		gravity 0.5;
		scale 0.5;
	}

	States
	{
	Spawn:
		BOSF A 0;
		BOSF ABCDABCD 3 BRIGHT;
	Death:
		TNT1 A 0 
		{
			A_PlaySound("inventory/siphongrenade/explode");
			A_SpawnItem("MetaArchvileFire");
			
			BlockThingsIterator it = BlockThingsIterator.Create(self,32,0);
			while (it.Next())
			{
				Actor mo = it.thing;
				
				if (mo is "MetaSpiritWolf")
				{
					if (meta_developer)
						Console.printf("Marauder Popcorn %i x %i uncomfortable with popcorn proximity", self.pos.x, self.pos.y);
					SetStateLabel("See");
					break;
				}
			}
			A_SpawnItem("MetaSpiritWolf");
		}
		Stop;
	}
}

class MetaMarauderEyeflash : Actor
{
	Default
	{
		-SOLID
		+NOGRAVITY
		scale 0.4;
	}
	
	States
	{
		Spawn:
			BFE1 ABCD 1 BRIGHT
			{
				if (target)
				{
					A_Warp(AAPTR_TARGET, 1, 0, 54, target.angle, WARPF_ABSOLUTEANGLE);
				}
			}
			stop;
	}
}

Class MetaMarauder_AfterImage : VisualThinker
{
	double fade;
	
	override void PostBeginPlay()
	{
		super.PostBeginPlay();
		SetRenderStyle(STYLE_AddStencil);
		alpha = 0.25;
		flags = SPF_FULLBRIGHT;
		fade = 0.25;
		scolor = "#FF0000";
	}
	
	static void Spawn(Actor owner)
	{
		if (!owner) return;
		
		let p = Level.SpawnVisualThinker("MetaMarauder_AfterImage");
		if ( p )
		{
			p.pos = owner.pos;
			p.texture = owner.CurState.GetSpriteTexture(0);
		}
	}
	
	override void Tick()
	{
		if ( bDESTROYED )
			return;
	
		super.Tick();
		
		fade -= 0.025;
		
		if ( fade <= 0.0 )
		{
			Destroy();
			return;
		}
		
		alpha = max(0.0, fade + frandom(-0.1,0.1));
	}
}