/*
----------------------------
MetaDoom
Actor Definitions
Maggot
----------------------------
*/

/*
	Crawls at hyper speed along the ground, and is a little harder to hit if
	you're just spraying indiscriminately.
*/

Class MetaMaggot : MonsterCore
{
	Default
	{
		Health 125;
		PainChance 120;
		Speed 12;
		Radius 30;
		Height 56;
		Mass 400;
		Monster;
		+FLOORCLIP
		SeeSound "monsters/maggot/sight";
		//AttackSound "monsters/pinky/attack";
		PainSound "monsters/maggot/pain";
		//DeathSound "monsters/pinky/die";
		//ActiveSound "monsters/pinky/idle";
		Obituary "$OB_DEMONHIT";
		painchance "HolyWater", 255;
		Tag "Maggot";
		//$Category "Monsters/MetaDoom/Pinky"
		//$Title "Pinky"
		//$Color 12
	}
	
	int hitHeight;
	
	bool CloseQuarters()
	{
		if ( !target ) return false;
		int dist = Distance3D(target);
		return ( dist <= 200 && !bFRIGHTENED );
	}
	
	action void A_MaggotChase(int goSpeed = 12)
	{
		if ( !target ) return;
		
		int dist = Distance3D(target);
		
		bool runBitchRun = invoker.CloseQuarters();
		
		if ( runBitchRun && InStateSequence(CurState, resolveState("See")) )
		{
			SetStateLabel("SeeToRun");
			return;
		}
		else if ( !runBitchRun && InStateSequence(CurState, resolveState("Run")) )
		{
			SetStateLabel("RunToSee");
			return;
		}
		
		invoker.hitHeight = runBitchRun ? 56 : 30;
		
		A_SetSize(radius, 56);
		
		speed = goSpeed;
		
		if ( runBitchRun && TryMove(pos.xy + (target.pos.xy - pos.xy).Unit()*speed, 0) )
		{
			angle = AngleTo(target);
			return;
		}
		invoker.A_MetaChase();
		
		A_SetSize(radius, invoker.hitHeight);
	}
	
	States
	{
		Spawn:
			MGGT A 10 A_Look();
			Loop;
		
		See:
			MGGT BBCCDDEE 2 Fast A_MaggotChase(15);
			Loop;
		SeeToRun:
			"----" A 0 A_StartSound("monsters/maggot/getup", CHAN_BODY);
			MGGT JJ 2 Fast A_MaggotChase(12);
			Goto Run;
		Run:
			MGGT FFGGHHII 2 Fast A_MaggotChase(10);
			Loop;
		RunToSee:
			"----" A 0 A_StartSound("monsters/maggot/getdown", CHAN_BODY);
			MGGT JJ 2 Fast A_MaggotChase(12);
			Goto See;
			
		Melee:
			MGGT K 6 Fast A_FaceTarget();
			MGGT L 6 Fast
			{
				A_FaceTarget();
				A_StartSound("monsters/maggot/swing", CHAN_BODY);
			}
			MGGT M 6 Fast A_CustomMeleeAttack(random(1, 10) * 4, "imp/melee");
			Goto See;
		
		Pain:
			MGGT A -1
			{
				return invoker.CloseQuarters() ? resolveState("PainRun") : resolveState("PainSee");
			}
			Stop;
		PainSee:
			MGGT N 2 Fast;
			MGGT N 3 Fast A_Pain;
			Goto See;
		PainRun:
			MGGT O 2 Fast;
			MGGT O 3 Fast A_Pain;
			Goto Run;
		Death:
			SARG I 0 { bSPRITEFLIP = random(0,1); } // random chance of sprite flipping
			TNT1 A 0 A_SpawnItem("SoulSpawner");
			SARG I 8 A_GiveToTarget("ScoreItem", 200);
			SARG J 8 A_Scream;
			SARG K 4;
			SARG L 4 A_NoBlocking;
			SARG M 4 A_PlaySound("bodyfalls/heavy");
			SARG N -1;
			Stop;
	}
}