/*
----------------------------
MetaDoom
Actor Definitions
Spawners
----------------------------
*/

Class MetaSpawnInfo
{
	Map<String, int> nearby;
	Actor src;
	
	void SearchInRadius(int radius)
	{
		BlockThingsIterator it = BlockThingsIterator.Create(src, radius);
		//Console.Printf("\ck-----");
		while ( it.Next() )
		{
			Actor mo = it.thing;
			
			if ( mo.health <= 0 ) return;
			
			int val = nearby.Get(mo.GetClassName());
			nearby.Insert(mo.GetClassName(), val+1);
			//Console.Printf(""..mo.GetClassName());
		}
	}
	
	bool IsNearby (Class<Actor> thing)
	{
		return nearby.CheckKey(thing.GetClassName());
	}
}

Class MetaSpawner : Actor
{
	Default
	{
		+ISMONSTER
		-COUNTKILL
	}
	
	MetaDoom_GameBrain brain;
	
	MetaSpawnInfo GetNearbyInfo (int searchRadius)
	{
		let spawninfo = new("MetaSpawnInfo");
		spawninfo.src = self;
		spawninfo.SearchInRadius(searchRadius);
		return spawninfo;
	}
	
	Actor SpawnVariant (Class<Actor> toSpawn)
	{
		let newFella = Spawn(toSpawn, pos);
		if ( newFella )
		{
			newFella.SpawnAngle = SpawnAngle;
			newFella.angle = angle;
			newFella.pitch = pitch;
			newFella.roll = roll;
			newFella.SpawnPoint = SpawnPoint;
			newFella.special = special;
			for ( int i = 0; i < 5; i++ )
			{
				newFella.args[i] = args[i];
			}
			newFella.special1 = special1;
			newFella.special2 = special2;
			newFella.SpawnFlags = SpawnFlags & ~MTF_SECRET;
			newFella.HandleSpawnFlags();
			newFella.SpawnFlags = SpawnFlags;
			newFella.bCountSecret = SpawnFlags & MTF_SECRET;
			newFella.ChangeTid(tid);
			newFella.vel = vel;
			newFella.master = master;
			newFella.target = target;
			newFella.tracer = tracer;
			newFella.CopyFriendliness(self, false);
			if ( health != SpawnHealth() ) newFella.health = health;
		}
		
		return newFella;
	}
	
	Array< Class<Actor> > spawns_class;
	Array<int> spawns_weight;
	
	override void PostBeginPlay()
	{
		super.PostBeginPlay();
		brain = MetaDoom_GameBrain.Get();
		DoSpawn();
		int totalWeight;
		//Console.Printf("=========================");
		for ( int i = 0; i < spawns_weight.Size(); i++ )
		{
			//Console.Printf("\t%s - %d", spawns_class[i].GetClassName(), spawns_weight[i]);
			totalWeight += spawns_weight[i];
		}
		//Console.Printf("------");
		int randomWeight = random(0,totalWeight);
		for ( int i = 0; i < spawns_class.Size(); i++ )
		{
			if ( randomWeight < spawns_weight[i] )
			{
				let fella = SpawnVariant(spawns_class[i]);
				AfterSpawn(MonsterCore(fella));
				//Console.Printf("\tSpawned %s at %f %f %f", spawns_class[i].GetClassName(), fella.pos.x, fella.pos.y, fella.pos.z);
				return;
			}
			randomWeight -= spawns_weight[i];
		}
	}
	
	virtual void AfterSpawn(MonsterCore fella)
	{
		Destroy();
	}
	
	void AddSpawn(Class<Actor> toSpawn, int weight)
	{
		spawns_class.Push(toSpawn);
		spawns_weight.Push(weight);
	}
	
	virtual void DoSpawn()
	{
	}
}

Class ZombiemanSpawner : MetaSpawner // replaces ZombieMan
{
	override void DoSpawn()
	{
		if ( meta_contentlocust )
		{
			AddSpawn("MetaZombieman", 128);
			AddSpawn("MetaHellRazer", 128);
		}
		
		int maps = brain.GetMapsCleared();
		
		if ( brain.IsEpisodic() ? (maps >= 2) : (maps >= 5) )
		{
			AddSpawn("MetaHellRazer", 128);
		}
		AddSpawn("MetaZombieman", 128);
	}
}

Class ShotgunGuySpawner : MetaSpawner // replaces ShotgunGuy
{
	override void DoSpawn()
	{
		if ( meta_contentlocust )
		{
			AddSpawn("MetaShotgunGuy", 128);
			AddSpawn("MetaZSec", 128);
		}
		
		int maps = brain.GetMapsCleared();
		
		if ( brain.IsEpisodic() ? (maps >= 3) : (maps >= 4) )
		{
			AddSpawn("MetaZSec", 128);
		}
		AddSpawn("MetaShotgunGuy", 128);
	}
}

class ChaingunGuySpawner : MetaSpawner // replaces ChaingunGuy
{	
	override void DoSpawn()
	{
		if ( meta_contentlocust )
		{
			AddSpawn("MetaAssassinGuy", 128);
			AddSpawn("MetaChainGunGuy", 128);
			AddSpawn("MetaMachineGunGuy", 128);
		}
		
		int maps = brain.GetMapsCleared();
		
		if ( brain.IsEpisodic() ? (maps >= 6) : (maps >= 13) )
		{
			AddSpawn("MetaAssassinGuy", 64);
		}
		if ( brain.IsEpisodic() ? (maps >= 2) : (maps >= 4) )
		{
			AddSpawn("MetaChainGunGuy", 128);
		}
		AddSpawn("MetaMachineGunGuy", 128);
	}
}

class ImpSpawner : MetaSpawner // replaces DoomImp
{
	States
	{
	Spawn:
		TROO A 0;
		TNT1 A 0 A_JumpIf(meta_noalts_actors, "Imp");
		TNT1 A 0 A_JumpIf(meta_contentlocust, "ContentLocustVarietyPack");
		TNT1 A 0 A_JumpIf(meta_episodicspawns && CallACS("Item_GameDetector", 0, 0, 0) >= 2, "EpisodicSelector");
		goto Doom2Selector;
	EpisodicSelector:
		TNT1 A 0 A_JumpIf(CallACS("Monster_ReturnMaps", 0, 0, 0) >= 7, "Tier3");
		TNT1 A 0 A_JumpIf(CallACS("Monster_ReturnMaps", 0, 0, 0) >= 2, "Tier2");
		goto Imp;
	Doom2Selector:
		TNT1 A 0 A_JumpIf(CallACS("Monster_ReturnMaps", 0, 0, 0) >= 12, "Tier3");
		TNT1 A 0 A_JumpIf(CallACS("Monster_ReturnMaps", 0, 0, 0) >= 3, "Tier2");
		goto Imp;
	ContentLocustVarietyPack:
		TNT1 A 0;
		TNT1 A 0 A_Jump(64, "NightmareImp", "ImpLord");
		goto Imp;
	Tier2:
		TNT1 A 0;
		TNT1 A 0 //A_JumpIf(CallACS("Spectre_SectorLight", 0, 0, 0) != 1, "LetsGetNightmarish");
		{
		if (level.PointInSector(self.pos.xy).GetLightLevel() < 128)
			{
				if (meta_developer)
						Console.printf("Spawners: ImpSpawner at %i x %i is ready for some darkness (%i)", self.pos.x, self.pos.y, level.PointInSector(self.pos.xy).GetLightLevel());
				SetStateLabel("LetsGetNightmarish");
			} else {
				if (meta_developer)
						Console.printf("Spawners: ImpSpawner at %i x %i is ready for some fun (%i)", self.pos.x, self.pos.y, level.PointInSector(self.pos.xy).GetLightLevel());
			}
		}
		goto Imp;
	Tier3:
		TNT1 A 0;
		TNT1 A 0 //A_JumpIf(CallACS("Spectre_SectorLight", 0, 0, 0) != 1, "LetsGetNightmarishVarietyPack");
		{
		if (level.PointInSector(self.pos.xy).GetLightLevel() < 128)
			{
				if (meta_developer)
						Console.printf("Spawners: ImpSpawner at %i x %i is ready for some darkness (%i)", self.pos.x, self.pos.y, level.PointInSector(self.pos.xy).GetLightLevel());
				SetStateLabel("LetsGetNightmarishVarietyPack");
			} else {
				if (meta_developer)
						Console.printf("Spawners: ImpSpawner at %i x %i is ready for some fun (%i)", self.pos.x, self.pos.y, level.PointInSector(self.pos.xy).GetLightLevel());
			}
		}
		TNT1 A 0 A_Jump(64, "ImpLord");
		goto Imp;
	VarietyPack:
		TNT1 A 0;
		TNT1 A 0 //A_JumpIf(CallACS("Spectre_SectorLight", 0, 0, 0) != 1, "LetsGetNightmarishVarietyPack");
		{
		if (level.PointInSector(self.pos.xy).GetLightLevel() < 128)
			{
				if (meta_developer)
						Console.printf("Spawners: ImpSpawner at %i x %i is ready for some darkness (%i)", self.pos.x, self.pos.y, level.PointInSector(self.pos.xy).GetLightLevel());
				SetStateLabel("LetsGetNightmarishVarietyPack");
			} else {
				if (meta_developer)
						Console.printf("Spawners: ImpSpawner at %i x %i is ready for some fun (%i)", self.pos.x, self.pos.y, level.PointInSector(self.pos.xy).GetLightLevel());
			}
		}
		TNT1 A 0 A_Jump(64, "ImpLord");
		goto Imp;
	LetsGetNightmarish:
		TNT1 A 0;
		TNT1 A 0 A_Jump(128, "NightmareImp");
		goto Imp;
	LetsGetNightmarishVarietyPack:
		TNT1 A 0;
		TNT1 A 0 A_Jump(128, "NightmareImp");
		TNT1 A 0 A_Jump(64, "ImpLord");
		goto Imp;
	Imp:
		TNT1 A 0 A_SpawnItemEx("MetaDoomImp",0,0,8,0,0,0,0,SXF_TRANSFERPOINTERS|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERSPECIAL|SXF_NOCHECKPOSITION,0,tid);
		stop;
	NightmareImp:
		TNT1 A 0 A_SpawnItemEx("MetaNightmareImp",0,0,8,0,0,0,0,SXF_TRANSFERPOINTERS|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERSPECIAL|SXF_NOCHECKPOSITION,0,tid);
		stop;
	ImpLord:
		TNT1 A 0 A_SpawnItemEx("MetaDoomImpLord",0,0,8,0,0,0,0,SXF_TRANSFERPOINTERS|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERSPECIAL|SXF_NOCHECKPOSITION,0,tid);
		stop;
	}
}

class PinkySpawner : MetaSpawner // replaces Demon
{	
	override void DoSpawn()
	{
		int maps = brain.GetMapsCleared();
		let info = GetNearbyInfo(256);
		
		bool humanNear = ( info.IsNearby("ZombiemanSpawner")
			|| info.IsNearby("MetaZombieman")
			|| info.IsNearby("MetaHellRazer")
			|| info.IsNearby("ShotgunGuySpawner")
			|| info.IsNearby("MetaShotgunGuy")
			|| info.IsNearby("MetaZSec")
			|| info.IsNearby("ChaingunGuySpawner")
			|| info.IsNearby("MetaMachineGunGuy")
			|| info.IsNearby("MetaChainGunGuy")
			|| info.IsNearby("MetaAssassinGuy")
		);
		
		if ( maps >= 2 )
		{
			AddSpawn("MetaHellhound", humanNear ? 192 : 64);
		}
		if ( maps >= 4 )
		{
			AddSpawn("MetaDemonDog", humanNear ? 192 : 64);
		}
		if ( maps >= 8 )
		{
			AddSpawn("MetaCerberus", humanNear ? 192 : 64);
		}
		
		// Add bulls...
		if ( brain.IsEpisodic() ? (maps >= 7) : (maps >= 10) )
		{
			AddSpawn("MetaBullDemon", 72);
		}
		else if ( brain.IsEpisodic() ? (maps >= 4) : (maps >= 8) )
		{
			AddSpawn("MetaBullDemon", 64);
		}
		
		// Add maggots...
		// A little rare starting out, but creeps in more about 12 maps in
		if ( brain.IsEpisodic() ? (maps >= 7) : (maps >= 12) )
		{
			if ( level.PointInSector(self.pos.xy).GetLightLevel() <= 128 )
			{
				AddSpawn("MetaMaggot", 256);
			}
			else
			{
				AddSpawn("MetaMaggot", info.IsNearby("MetaMaggot") ? 64 : 128);
			}
		}
		else if ( brain.IsEpisodic() ? (maps >= 4) : (maps >= 6) )
		{
			if ( level.PointInSector(self.pos.xy).GetLightLevel() <= 128 )
			{
				AddSpawn("MetaMaggot", 192);
			}
			else
			{
				AddSpawn("MetaMaggot", info.IsNearby("MetaMaggot") ? 32 : 96);
			}
		}
		
		AddSpawn("MetaDemon", 128);
	}
	States
	{
	/*Spawn:
		SARG A 0;
		TNT1 A 0 A_JumpIf(meta_noalts_actors, "Pinky");
		TNT1 A 0 A_JumpIf(meta_contentlocust, "ContentLocustVarietyPack");
		TNT1 A 0 A_JumpIf(CallACS("Monster_ReturnMaps", 0, 0, 0) >= 2, "IntroduceTheDogs");
		goto Pinky;
	IntroduceTheDogs:
		TNT1 A 0;
		TNT1 A 0
		{
			BlockThingsIterator it = BlockThingsIterator.Create(self,256,0);
			while (it.Next())
			{
				Actor mo = it.thing;
				
				if (mo is "ZombiemanSpawner"
				|| mo is "MetaZombieman"
				|| mo is "MetaHellRazer"
				|| mo is "ShotgunGuySpawner"
				|| mo is "MetaShotgunGuy"
				|| mo is "MetaZSec"
				|| mo is "ChaingunGuySpawner"
				|| mo is "MetaMachineGunGuy"
				|| mo is "MetaChainGunGuy"
				|| mo is "MetaAssassinGuy")
				{
					if (meta_developer)
						Console.printf("Spawners: Pinky spawner at %i x %i is dog-biased.", self.pos.x, self.pos.y);
					SetStateLabel("DogsWeighted");
					break;
				}
			}
		}
	DogsUnweighted:
		TNT1 A 0; //A_Log("Demon Bias!")
		TNT1 A 0 A_Jump(64, "LotsofDogs");
		goto Doom2Selector;
	DogsWeighted:
		TNT1 A 0; //A_Log("Dog Bias!")
		TNT1 A 0 A_Jump(192, "LotsofDogs");
		TNT1 A 0 A_JumpIf(meta_episodicspawns && CallACS("Item_GameDetector", 0, 0, 0) >= 2, "EpisodicSelector");
		goto Doom2Selector;
	EpisodicSelector:
		TNT1 A 0 A_JumpIf(CallACS("Monster_ReturnMaps", 0, 0, 0) >= 4, "Tier2");
		goto Pinky;
	Doom2Selector:
		TNT1 A 0 A_JumpIf(CallACS("Monster_ReturnMaps", 0, 0, 0) >= 8, "Tier2");
		goto Pinky;
	ContentLocustVarietyPack:
		TNT1 A 0;
		TNT1 A 0 A_Jump(64, "IntroduceTheDogs");
		TNT1 A 0 A_Jump(64, "BullDemon");
		goto Pinky;
	LotsOfDogs:
		TNT1 A 0; //A_Log("Dog Spawned")
		TNT1 A 0 A_JumpIf(meta_contentlocust, "ContentLocustDogs");
		TNT1 A 0
		{
			if (meta_mapbreakers)
			{
				return A_JumpIf(CallACS("Monster_ReturnMaps", 0, 0, 0) >= 8, "DogsTier3");
			} else {
				return A_JumpIf(CallACS("Monster_ReturnMaps", 0, 0, 0) >= 4, "DogsTier2");
			}
		}		
		TNT1 A 0 A_JumpIf(CallACS("Monster_ReturnMaps", 0, 0, 0) >= 4, "DogsTier2");
		goto Hellhound;
	DogsTier2:
		TNT1 A 0; 
		TNT1 A 0 A_Jump(192, "DemonDog");
		goto Hellhound;
	DogsTier3:
		TNT1 A 0; 
		TNT1 A 0 A_Jump(192, "DemonDog", "Cerberus");
		goto Hellhound;
	Tier2:
		TNT1 A 0; 
		TNT1 A 0 A_Jump(64, "BullDemon");
		goto Pinky;
	ContentLocustDogs:
		TNT1 A 0;
		TNT1 A 0 
		{
			if (meta_mapbreakers)
			{
				A_Jump(128, "DemonDog");
			} else {
				A_Jump(128, "DemonDog", "Cerberus");
			}
		}
		goto Hellhound;
	Hellhound:
		TNT1 A 0 A_SpawnItemEx("MetaHellhound",0,0,0,0,0,0,0,SXF_TRANSFERPOINTERS|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERSPECIAL|SXF_NOCHECKPOSITION,0,tid);
		stop;
	DemonDog:
		TNT1 A 0 A_SpawnItemEx("MetaDemonDog",0,0,0,0,0,0,0,SXF_TRANSFERPOINTERS|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERSPECIAL|SXF_NOCHECKPOSITION,0,tid);
		stop;
	Cerberus:
		TNT1 A 0 A_SpawnItemEx("MetaCerberus",0,0,0,0,0,0,0,SXF_TRANSFERPOINTERS|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERSPECIAL|SXF_NOCHECKPOSITION,0,tid);
		stop;
	Pinky:
		TNT1 A 0 A_SpawnItemEx("MetaDemon",0,0,0,0,0,0,0,SXF_TRANSFERPOINTERS|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERSPECIAL|SXF_NOCHECKPOSITION,0,tid);
		stop;
	BullDemon:
		TNT1 A 0 A_SpawnItemEx("MetaBullDemon",0,0,0,0,0,0,0,SXF_TRANSFERPOINTERS|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERSPECIAL|SXF_NOCHECKPOSITION,0,tid);
		stop;*/
	}
}

class DogSpawner : PinkySpawner // replaces MBFHelperDog
{
	States
	{
	Spawn:
		DOGS A 0;
		TNT1 A 0 A_JumpIf(meta_noalts_actors, "Hellhound");
		goto LotsOfDogs;
	}
}

class SpectreSpawner : MetaSpawner // replaces Spectre
{
	Default
	{
	RenderStyle "OptFuzzy";
	}
	
	States
	{
	Spawn:
		SARG E 0;
		TNT1 A 0 A_JumpIf(meta_noalts_actors, "Spectre");
		TNT1 A 0 A_JumpIf(meta_contentlocust, "ContentLocustVarietyPack");
		TNT1 A 0 
		{
			if (level.PointInSector(self.pos.xy).GetLightLevel() > 128)
			{
				if (meta_developer)
						Console.printf("Spawners: SpectreSpawner at %i x %i is a bright one (%i)", self.pos.x, self.pos.y, level.PointInSector(self.pos.xy).GetLightLevel());
				SetStateLabel("BrightMap");
			} else {
				if (meta_developer)
						Console.printf("Spawners: SpectreSpawner at %i x %i is a bit dim (%i)", self.pos.x, self.pos.y, level.PointInSector(self.pos.xy).GetLightLevel());
			}
		}
		goto Darkmap;
	BrightMap:
		TNT1 A 0;
		TNT1 A 0 A_JumpIf(CallACS("Monster_ReturnMaps", 0, 0, 0) >= 5, "BrightMapVarietyPack");
		goto Spectre;
	DarkMap:
		TNT1 A 0; 
		TNT1 A 0 A_JumpIf(CallACS("Monster_ReturnMaps", 0, 0, 0) >= 5, "DarkMapVarietyPack");
		TNT1 A 0 A_Jump(80, "Trite");
		goto Brightmap;
	BrightMapVarietyPack:
		TNT1 A 0;
		TNT1 A 0 A_Jump(128, "Sawcubus");
		goto Spectre;
	DarkMapVarietyPack:
		TNT1 A 0;
		TNT1 A 0 A_Jump(128, "NightmareSpectre");
		goto Spectre;
	ContentLocustVarietyPack:
		TNT1 A 0;
		TNT1 A 0 A_Jump(128, "NightmareSpectre", "Sawcubus");
		TNT1 A 0 A_Jump(64, "Trite");
		goto Spectre;
	Spectre:
		TNT1 A 0 A_SpawnItemEx("MetaSpectre",0,0,0,0,0,0,0,SXF_TRANSFERPOINTERS|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERSPECIAL|SXF_NOCHECKPOSITION,0,tid);
		stop;
	NightmareSpectre:
		TNT1 A 0 A_SpawnItemEx("MetaNightmareSpectre",0,0,0,0,0,0,0,SXF_TRANSFERPOINTERS|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERSPECIAL|SXF_NOCHECKPOSITION,0,tid);
		stop;
	Sawcubus:
		TNT1 A 0 A_SpawnItemEx("MetaSawcubus",0,0,0,0,0,0,0,SXF_TRANSFERPOINTERS|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERSPECIAL|SXF_NOCHECKPOSITION,0,tid);
		stop;
	Trite:
		TNT1 A 0
		{
			if (meta_nospoders)
			{
				if (meta_developer)
						Console.printf("Spawners: Trite spawn at %i x %i averted due to arachnophobia", self.pos.x, self.pos.y);
				SetStateLabel("Spectre");
			}
			
			if (level.PointInSector(self.pos.xy).damageamount != 0)
			{
				if (meta_developer)
						Console.printf("Spawners: Trite spawn at %i x %i averted due to nukage", self.pos.x, self.pos.y);
				SetStateLabel("Spectre");
			}
		}
		TNT1 A 16 A_SpawnItemEx("MetaTrite",0,0,0,random(0,16),random(0,16),0,random(0,360),SXF_TRANSFERPOINTERS|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERSPECIAL|SXF_NOCHECKPOSITION,0,tid);
		TNT1 A 16 A_SpawnItemEx("MetaTrite",0,0,0,random(0,16),random(0,16),0,random(0,360),SXF_TRANSFERPOINTERS|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERSPECIAL|SXF_NOCHECKPOSITION,0,tid);
		TNT1 A 16 A_SpawnItemEx("MetaTrite",0,0,0,random(0,16),random(0,16),0,random(0,360),SXF_TRANSFERPOINTERS|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERSPECIAL|SXF_NOCHECKPOSITION,0,tid);
		stop;
	}
}

class CacodemonSpawner : MetaSpawner // replaces Cacodemon
{
	States
	{
	Spawn:
		HEAD A 0;
		TNT1 A 0 A_JumpIf(meta_noalts_actors, "Cacodemon");
		TNT1 A 0 A_JumpIf(meta_contentlocust, "ContentLocustVarietyPack");
		TNT1 A 0 A_JumpIf(meta_episodicspawns && CallACS("Item_GameDetector", 0, 0, 0) >= 2, "EpisodicSelector");
		goto Doom2Selector;
	EpisodicSelector:
		TNT1 A 0 A_JumpIf(CallACS("Monster_ReturnMaps", 0, 0, 0) >= 7, "Tier3");
		TNT1 A 0 A_JumpIf(CallACS("Monster_ReturnMaps", 0, 0, 0) >= 3, "Tier2");
		goto Cacodemon;
	Doom2Selector:
		TNT1 A 0 A_JumpIf(CallACS("Monster_ReturnMaps", 0, 0, 0) >= 19, "Tier3");
		TNT1 A 0 A_JumpIf(CallACS("Monster_ReturnMaps", 0, 0, 0) >= 7, "Tier2");
		goto Cacodemon;
	Tier2:
		TNT1 A 0 A_Jump(72, "Malwraith");
		goto Cacodemon;
	ContentLocustVarietyPack:
	Tier3:
		TNT1 A 0 
		{
			if (meta_mapbreakers)
			{
				return A_Jump(64, "Malwraith", "Wretched");
			} else {
				return A_Jump(256, "Tier2");
			}
		}
		goto Cacodemon;
	Cacodemon:
		TNT1 A 0 A_SpawnItemEx("MetaCacodemon",0,0,0,0,0,0,0,SXF_TRANSFERPOINTERS|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERSPECIAL|SXF_NOCHECKPOSITION,0,tid);
		stop;
	Malwraith:
		TNT1 A 0 A_SpawnItemEx("MetaMalwraith",0,0,0,0,0,0,0,SXF_TRANSFERPOINTERS|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERSPECIAL|SXF_NOCHECKPOSITION,0,tid);
		stop;
	Wretched:
		TNT1 A 0 A_SpawnItemEx("MetaWretched",0,0,0,0,0,0,0,SXF_TRANSFERPOINTERS|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERSPECIAL|SXF_NOCHECKPOSITION,0,tid);
		stop;
	}
}

class HellKnightSpawner : MetaSpawner // replaces HellKnight
{
	States
	{
	Spawn:
		BOS2 A 0;
		TNT1 A 0 A_SpawnItemEx("MetaHellKnight",0,0,0,0,0,0,0,SXF_TRANSFERPOINTERS|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERSPECIAL|SXF_NOCHECKPOSITION,0,tid);
		stop;
	}
}

class PainElementalSpawner : MetaSpawner // replaces PainElemental
{	
	States
	{
	Spawn:
		PAIN A 0;
		TNT1 A 0 A_JumpIf(meta_noalts_actors, "PainElemental");
		TNT1 A 0 A_JumpIf(meta_contentlocust, "ContentLocustVarietyPack");
		TNT1 A 0 A_JumpIf(meta_episodicspawns && CallACS("Item_GameDetector", 0, 0, 0) >= 2, "EpisodicSelector");
		goto Doom2Selector;
	EpisodicSelector:
		TNT1 A 0 A_JumpIf(CallACS("Monster_ReturnMaps", 0, 0, 0) >= 5, "Tier2");
		goto PainElemental;
	Doom2Selector:
		TNT1 A 0 A_JumpIf(CallACS("Monster_ReturnMaps", 0, 0, 0) >= 10, "Tier2");
		goto PainElemental;
	ContentLocustVarietyPack:
	Tier2:
		TNT1 A 0 A_Jump(64, "Beholder", "Rahovart");
		goto PainElemental;
	PainElemental:
		TNT1 A 0 A_SpawnItemEx("MetaPainElemental",0,0,0,0,0,0,0,SXF_TRANSFERPOINTERS|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERSPECIAL|SXF_NOCHECKPOSITION,0,tid);
		stop;
	Beholder:
		TNT1 A 0 A_SpawnItemEx("MetaBeholder",0,0,0,0,0,0,0,SXF_TRANSFERPOINTERS|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERSPECIAL|SXF_NOCHECKPOSITION,0,tid);
		stop;
	Rahovart:
		TNT1 A 0 A_SpawnItemEx("MetaRahovart",0,0,0,0,0,0,0,SXF_TRANSFERPOINTERS|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERSPECIAL|SXF_NOCHECKPOSITION,0,tid);
		stop;
	}
}

class LostSoulSpawner : MetaSpawner // replaces LostSoul
{

	States
	{
	Spawn:
		SKUL A 0;
		TNT1 A 0 A_JumpIf(meta_noalts_actors, "LostSoul");
		TNT1 A 0 A_JumpIf(meta_contentlocust, "ContentLocustVarietyPack");
		TNT1 A 0 A_JumpIf(meta_episodicspawns && CallACS("Item_GameDetector", 0, 0, 0) >= 2, "EpisodicSelector");
		goto Doom2Selector;
	EpisodicSelector:
		TNT1 A 0 A_JumpIf(CallACS("Monster_ReturnMaps", 0, 0, 0) >= 3, "VarietyPack");
		goto LostSoul;
	Doom2Selector:
		TNT1 A 0 A_JumpIf(CallACS("Monster_ReturnMaps", 0, 0, 0) >= 4, "VarietyPack");
		goto LostSoul;
	ContentLocustVarietyPack:
		TNT1 A 0;
		TNT1 A 0 A_Jump(128, "Phantom");
		goto LostSoul;
	VarietyPack:
		TNT1 A 0;
		TNT1 A 0 A_Jump(128, "Phantom");
		goto LostSoul;
	LostSoul:
		TNT1 A 0 A_SpawnItemEx("MetaLostSoul",0,0,0,0,0,0,0,SXF_TRANSFERPOINTERS|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERSPECIAL|SXF_NOCHECKPOSITION,0,tid);
		stop;
	Phantom:
		TNT1 A 0 A_SpawnItemEx("MetaPhantom",0,0,0,0,0,0,0,SXF_TRANSFERPOINTERS|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERSPECIAL|SXF_NOCHECKPOSITION,0,tid);
		stop;
	}
}

class ArchVileSpawner : MetaSpawner // replaces ArchVile
{
	States
	{
	Spawn:
		VILE A 0;
		TNT1 A 0 A_JumpIf(meta_noalts_actors, "Archvile");
		TNT1 A 0 A_JumpIf(meta_contentlocust, "ContentLocustVarietyPack");
		TNT1 A 0 A_JumpIf(meta_episodicspawns && CallACS("Item_GameDetector", 0, 0, 0) >= 2, "EpisodicSelector");
		goto Doom2Selector;
	EpisodicSelector:
		TNT1 A 0 A_JumpIf(CallACS("Monster_ReturnMaps", 0, 0, 0) >= 5, "VarietyPack");
		goto Archvile;
	Doom2Selector:
		TNT1 A 0 A_JumpIf(CallACS("Monster_ReturnMaps", 0, 0, 0) >= 20, "VarietyPack");
		TNT1 A 0 A_JumpIf(CallACS("Monster_ReturnMaps", 0, 0, 0) >= 15, "Tier2");
		goto Archvile;
	Tier2:
		TNT1 A 0 A_Jump(72, "Summoner");
		goto Archvile;
	VarietyPack:
		TNT1 A 0 A_Jump(72, "Summoner", "Infernis");
		goto Archvile;
	ContentLocustVarietyPack:
		TNT1 A 0 A_Jump(128, "Summoner", "Infernis");
		goto Archvile;
	Archvile:
		TNT1 A 0 A_SpawnItemEx("MetaArchVile",0,0,0,0,0,0,0,SXF_TRANSFERPOINTERS|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERSPECIAL|SXF_NOCHECKPOSITION,0,tid);
		stop;
	Summoner:
		TNT1 A 0 A_SpawnItemEx("MetaSummoner",0,0,0,0,0,0,0,SXF_TRANSFERPOINTERS|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERSPECIAL|SXF_NOCHECKPOSITION,0,tid);
		stop;
	Infernis:
		TNT1 A 0 A_SpawnItemEx("MetaInfernis",0,0,0,0,0,0,0,SXF_TRANSFERPOINTERS|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERSPECIAL|SXF_NOCHECKPOSITION,0,tid);
		stop;
	}
}

class RevenantSpawner : MetaSpawner // replaces Revenant
{
	States
	{
	Spawn:
		SKEL A 0;
		TNT1 A 0 A_JumpIf(meta_noalts_actors, "Revenant");
		TNT1 A 0 A_JumpIf(meta_contentlocust, "ContentLocustVarietyPack");
		TNT1 A 0 A_JumpIf(meta_episodicspawns && CallACS("Item_GameDetector", 0, 0, 0) >= 2, "EpisodicSelector");
		goto Doom2Selector;
	EpisodicSelector:
		TNT1 A 0 A_JumpIf(CallACS("Monster_ReturnMaps", 0, 0, 0) >= 5, "VarietyPack");
		goto Revenant;
	Doom2Selector:
		TNT1 A 0 A_JumpIf(CallACS("Monster_ReturnMaps", 0, 0, 0) >= 10, "VarietyPack");
		goto Revenant;
	ContentLocustVarietyPack:
		TNT1 A 0;
		TNT1 A 0 A_Jump(128, "Fiend");
		goto Revenant;
	VarietyPack:
		TNT1 A 0;
		TNT1 A 0 A_Jump(96, "Fiend");
		goto Revenant;
	Revenant:
		TNT1 A 0 A_SpawnItemEx("MetaRevenant",0,0,0,0,0,0,0,SXF_TRANSFERPOINTERS|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERSPECIAL|SXF_NOCHECKPOSITION,0,tid);
		stop;
	Fiend:
		TNT1 A 0 A_SpawnItemEx("MetaFiend",0,0,0,0,0,0,0,SXF_TRANSFERPOINTERS|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERSPECIAL|SXF_NOCHECKPOSITION,0,tid);
		stop;
	}
}

// These ones need special attention due to +BOSSDEATH handling

class MetaBossSpawner : MetaSpawner
{
	Default
	{
		+NOBLOCKMAP
		+NOSECTOR
		+NOGRAVITY
		+THRUACTORS
	}
	
	override void AfterSpawn(MonsterCore fella)
	{
		fella.bossTracker = MetaBossSpawner(self);
	}

	void StopIt()
	{
		A_BossDeath();
		Destroy();
	}
}

Class BaronOfHellSpawner : MetaBossSpawner // replaces BaronOfHell
{
	override void DoSpawn()
	{
		AddSpawn("MetaBaronOfHell", 1);
	}
}

class ArachnotronSpawner : MetaBossSpawner // replaces Arachnotron
{
	override void DoSpawn()
	{
		int maps = brain.GetMapsCleared();
		
		if ( brain.IsEpisodic() ? (maps >= 6) : (maps >= 20) )
		{
			AddSpawn("MetaSpiborg", 90);
			AddSpawn("MetaTitantula", 64);
		}
		else if ( brain.IsEpisodic() ? (maps >= 4) : (maps >= 8) )
		{
			AddSpawn("MetaSpiborg", 128);
		}
		
		AddSpawn("MetaArachnotron", 128);
	}
}

Class MancubusSpawner : MetaBossSpawner // replaces Fatso
{
	override void DoSpawn()
	{
		int maps = brain.GetMapsCleared();
		
		if ( brain.IsEpisodic() ? (maps >= 7) : (maps >= 16) )
		{
			AddSpawn("MetaBehemoth", 128);
			AddSpawn("MetaCyberManc", 64);
		}
		else if ( brain.IsEpisodic() ? (maps >= 3) : (maps >= 8) )
		{
			AddSpawn("MetaBehemoth", 64);
		}
		
		AddSpawn("MetaMancubus", 128);
	}
}

class CyberdemonSpawner : MetaBossSpawner // replaces Cyberdemon
{
	States
	{
	Spawn:
		CYBR A 0;
		TNT1 A 0 A_JumpIf(meta_uniquebosses == 0, "Cyberdemon");
		TNT1 A 0
		{
			BlockThingsIterator it = BlockThingsIterator.Create(self,32767,0);
			while (it.Next())
			{
				Actor mo = it.thing;
				
				if (mo is "WolfSSSpawner"
				|| mo is "MetaWolfensteinSS"
				|| mo is "MetaWolfensteinSNES"
				|| mo is "MetaWolfensteinApple"
				|| mo is "MetaWolfensteinMacOS"
				|| mo is "MetaWolfensteinJava")
				{
					SetStateLabel("Harbinger");
					break;
				}
			}
		}
	Cyberdemon:
		TNT1 A 0 A_SpawnItemEx("MetaCyberdemon",0,0,0,0,0,0,0,SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERSPECIAL|SXF_NOCHECKPOSITION,0,tid);
		goto CreepyStalker;
	Harbinger:
		TNT1 A 0 A_SpawnItemEx("MetaHarbinger",0,0,0,0,0,0,0,SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERSPECIAL|SXF_NOCHECKPOSITION,0,tid);
		goto CreepyStalker;
	}
}

// For "Doom 64 for Doom 2"
class CyberdemonSpawner_D64D2 : CyberdemonSpawner
{
	States
	{
	Death:
		TNT1 A 1;
		TNT1 A 1 A_KeenDie;
		Stop;
	}
}



class SpiderMastermindSpawner : MetaBossSpawner // replaces SpiderMastermind
{
	States
	{
	Spawn:
		SPID A 0;
		TNT1 A 0 A_JumpIf(meta_uniquebosses == 0, "SpiderMastermind");
		TNT1 A 0
		{
			if(level.MapName ~== "e4m8")
			{
				return ResolveState("MotherDemon");
			} else if(level.MapName ~== "map28") {
				return ResolveState("HellGuard");
			} else {
				return ResolveState("SpiderMastermind");
			}
		}
	SpiderMastermind:
		TNT1 A 0 A_SpawnItemEx("MetaSpiderMastermind",0,0,0,0,0,0,0,SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERSPECIAL|SXF_NOCHECKPOSITION,0,tid);
		goto CreepyStalker;
	MotherDemon:
		TNT1 A 0 A_SpawnItemEx("MetaMotherDemon",0,0,0,0,0,0,0,SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERSPECIAL|SXF_NOCHECKPOSITION,0,tid);
		goto CreepyStalker;
	HellGuard:
		TNT1 A 0 A_SpawnItemEx("MetaHellGuard",0,0,0,0,0,0,0,SXF_SETMASTER|SXF_TRANSFERPOINTERS|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERSPECIAL|SXF_NOCHECKPOSITION,0,tid);
		goto CreepyStalker;
	}
}

// Doom 64 Shit

class NightmareImpSpawner : MetaSpawner // replaces 64NightmareImp
{
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItemEx("MetaNightmareImp",0,0,0,0,0,0,0,SXF_TRANSFERPOINTERS|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERSPECIAL|SXF_NOCHECKPOSITION,0,tid);
		stop;
	}
}

// stealth monsters are shit for losers. let's fix this.
class StealthArachnotronSpawner : ArachnotronSpawner replaces StealthArachnotron {}
class StealthArchVileSpawner : ArchVileSpawner replaces StealthArchvile {}
class StealthBaronOfHellSpawner : BaronOfHellSpawner replaces StealthBaron {}
class StealthCacodemonSpawner : CacodemonSpawner replaces StealthCacodemon {}
class StealthChaingunGuySpawner : ChaingunGuySpawner replaces StealthChaingunGuy {}
class StealthDemonSpawner : SpectreSpawner replaces StealthDemon {}
class StealthHellKnightSpawner : HellKnightSpawner replaces StealthHellKnight {}
class StealthImpSpawner : ImpSpawner replaces StealthDoomImp {}
class StealthMancubusSpawner : MancubusSpawner replaces StealthFatso {}
class StealthRevenantSpawner : RevenantSpawner replaces StealthRevenant {}
class StealthShotgunGuySpawner : ShotgunGuySpawner replaces StealthShotgunGuy {}
class StealthZombiemanSpawner : ZombiemanSpawner replaces StealthZombieMan {}

// The once and former "Optional" content spawners. Now EVERYTHING is optional,
// so seperating them is less relevant, but here they are.
class WolfSSSpawner : MetaSpawner
{
	States
	{
	Spawn:
		SSWV A 0;
		TNT1 A 0 A_JumpIf(meta_noalts_actors, "WolfSS");
		TNT1 A 0 A_Jump (256, "WolfSS", "WolfSNES", "WolfApple", "WolfMac", "WolfJava");
	WolfSS:
		TNT1 A 0 A_SpawnItemEx("MetaWolfensteinSS",0,0,0,0,0,0,0,SXF_TRANSFERPOINTERS|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERSPECIAL|SXF_NOCHECKPOSITION);
		stop;
	WolfSNES:
		TNT1 A 0 A_SpawnItemEx("MetaWolfensteinSNES",0,0,0,0,0,0,0,SXF_TRANSFERPOINTERS|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERSPECIAL|SXF_NOCHECKPOSITION);
		stop;
	WolfApple:
		TNT1 A 0 A_SpawnItemEx("MetaWolfensteinApple",0,0,0,0,0,0,0,SXF_TRANSFERPOINTERS|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERSPECIAL|SXF_NOCHECKPOSITION);
		stop;
	WolfMac:
		TNT1 A 0 A_SpawnItemEx("MetaWolfensteinMacOS",0,0,0,0,0,0,0,SXF_TRANSFERPOINTERS|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERSPECIAL|SXF_NOCHECKPOSITION);
		stop;
	WolfJava:
		TNT1 A 0 A_SpawnItemEx("MetaWolfensteinJava",0,0,0,0,0,0,0,SXF_TRANSFERPOINTERS|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERSPECIAL|SXF_NOCHECKPOSITION);
		stop;
	}
}

class KeenSpawner : MetaSpawner
{
	Default
	{
		Health 0x7fffffff;
		Height 0;
		Radius 0;
		MONSTER;
		-COUNTKILL
		-SOLID
		+NOCLIP
		+NOTDMATCH
		+SPAWNCEILING 
	}
	
	States
	{
	Spawn:
		KEEN A 0;
		KEEN A 0 A_JumpIf(meta_noalts_actors, "Keen");
		KEEN A 0 A_Jump(256,"Keen","Budo","Dave","Hovertank","Rover","Catacomb");
	Keen:
		TNT1 A 0 A_SpawnItemEx("MetaKeen",0,0,0,0,0,0,0,SXF_SETMASTER|SXF_NOCHECKPOSITION|SXF_TRANSFERAMBUSHFLAG);
		goto CreepyStalker;
	Budo:
		TNT1 A 0 A_SpawnItemEx("MetaBudo",0,0,0,0,0,0,0,SXF_SETMASTER|SXF_NOCHECKPOSITION|SXF_TRANSFERAMBUSHFLAG);
		goto CreepyStalker;
	Dave:
		TNT1 A 0 A_SpawnItemEx("MetaDave",0,0,0,0,0,0,0,SXF_SETMASTER|SXF_NOCHECKPOSITION|SXF_TRANSFERAMBUSHFLAG);
		goto CreepyStalker;
	Hovertank:
		TNT1 A 0 A_SpawnItemEx("MetaHovertank",0,0,0,0,0,0,0,SXF_SETMASTER|SXF_NOCHECKPOSITION|SXF_TRANSFERAMBUSHFLAG);
		goto CreepyStalker;
	Rover:
		TNT1 A 0 A_SpawnItemEx("MetaRover",0,0,0,0,0,0,0,SXF_SETMASTER|SXF_NOCHECKPOSITION|SXF_TRANSFERAMBUSHFLAG);
		goto CreepyStalker;
	Catacomb:
		TNT1 A 0 A_SpawnItemEx("MetaCatacomb",0,0,0,0,0,0,0,SXF_SETMASTER|SXF_NOCHECKPOSITION|SXF_TRANSFERAMBUSHFLAG);
		goto CreepyStalker;
	CreepyStalker:
		TNT1 A 1; // SFX: HEAVY BREATHING
		loop;
	Death:
		TNT1 A 1;
		TNT1 A 1 A_KeenDie;
		TNT1 A -1;
		Stop;
	}
}