/*
----------------------------
MetaDoom
ZScript Definitions
Status Bar
----------------------------
*/

// The HUD! ZScript edition. ZScript HUDs are also nasty, but they're mostly a
// kind of nasty I can deal with. This port wasn't TOO troublesome, probably
// because I got most of the profanity out of the way during JPF.

Class MetaDoom_NotifyMessage
{
	string text;
	int time;
	double prev;
	double y;
}

class MetaDoomStatusBar : BaseStatusBar
{
	HUDFont mHUDFont;
	HUDFont mIndexFont;
	HUDFont mAmountFont;
	InventoryBarState diparms;
	HUDFont mSmallFont;
	HUDFont mSmallFont2;
	HUDFont mTinyFont;
	
	// You need a DynamicValueInterpolator for any value that you want to have interpolated
	DynamicValueInterpolator mHealthInterpolator;
	DynamicValueInterpolator mArmorInterpolator;
	DynamicValueInterpolator mScoreInterpolator;
	DynamicValueInterpolator mAmmoInterpolator;
	
	// Things for the Powerup bar system.
	static const string powerupStuff[] =
	{
		//Name of Powerup Giver - Powerup Icon
		"MetaHasteSphere","POWRPINS",
		"MetaRadSuit","POWRSUIT",
		"MetaLightAmp","POWRLAMP",
		"MetaBerserkTimer","POWRBZRK",
		"MetaQuadDamage","POWRQUAD",
		"BufferLineDONOTEDIT","POWRFART" //This line has to be here for things to work
	};
	int barArraySize; //amount of 'columns' that the array has
	int barArrayColumns; //size of the array divided by the columns
	
	double lowHealthFade;
	
	int x_off;
	
	Array<MetaDoom_NotifyMessage> msg_logs;
	int score_time;
	int score_prev;
	double score_scale;
	double score_scalePrev;
	
	override bool ProcessNotify(EPrintLevel printlevel, String outline)
	{
		if ( printlevel <= PRINT_TEAMCHAT )
		{
			let msg = new("MetaDoom_NotifyMessage");
			msg.text = outline;
			msg.time = 35*4;
			msg_logs.Push(msg);
			if ( msg_logs.Size() > 3 )
			{
				msg_logs.Delete(0);
			}
			return true;
		}
		return false;
	}

	override void Init()
	{
		Super.Init();
		//SetSize(32, 320, 200);
		SetSize(0, 320, 200);

		// Create the fonts used for the HUD
		Font fnt = "HUDFONT_DOOM";
		mHUDFont = HUDFont.Create(fnt, fnt.GetCharWidth("0"), true, 1, 1);
		fnt = "INDEXFONT_DOOM";
		mIndexFont = HUDFont.Create(fnt, fnt.GetCharWidth("0"), true);
		mAmountFont = HUDFont.Create("INDEXFONT");
		//diparms = InventoryBarState.Create();
		diparms = InventoryBarState.Create(mIndexfont, Font.CR_UNTRANSLATED, 1.0, "ARTIBOX", "INVCURS");
		
		mSmallFont = HUDFont.Create("SMALLFONT");
		mSmallFont2 = HUDFont.Create("SMALLFONT2");
		mTinyFont = HUDFont.Create("TINYBABY");
		
		// More Powerup Bar Shit
		barArrayColumns = 2;
		barArraySize = powerupStuff.Size()/barArrayColumns;
		
		// Initialize the interpolation variables
		mHealthInterpolator = DynamicValueInterpolator.Create(0, 0.25, 1, 32);
		mArmorInterpolator = DynamicValueInterpolator.Create(0, 0.25, 1, 32);
		mScoreInterpolator = DynamicValueInterpolator.Create(0, 0.25, 1, 64000);
		mAmmoInterpolator = DynamicValueInterpolator.Create(0, 0.25, 1, 32);
		
		x_off = 53;
	}

	// What happens when a new game begins
	override void NewGame ()
	{
		// Run the parent status bar's NewGame() function
		Super.NewGame();

		// Reset any interpolators that you declared
		mHealthInterpolator.Reset(0);
		mArmorInterpolator.Reset(0);
		mScoreInterpolator.Reset(0);
		mAmmoInterpolator.Reset(0);
	}
	
	// What needs to run every tick
	override void Tick()
	{
		// Run the parent status bar's Tick() function
		Super.Tick();

		// Update the value of the interpolators
		mHealthInterpolator.Update(CPlayer.health); // Set the interpolator's value to this player's health
		mArmorInterpolator.Update(GetArmorAmount());
		mScoreInterpolator.Update(players[consoleplayer].mo.score);
		Ammo ammo1, ammo2;
		int ammomax;
		int ammocount1, ammocount2;
		[ammo1, ammo2, ammocount1, ammocount2] = GetCurrentAmmo();
		mAmmoInterpolator.Update(ammocount1);
		
		if ( CPlayer.health <= 25 )
		{
			lowHealthFade = 1.0;
		}
		else
		{
			if ( lowHealthFade > 0.0 )
			{
				lowHealthFade -= 0.1;
			}
		}
		
		for ( int i = 0; i < msg_logs.Size(); i++ )
		{
			msg_logs[i].time -= 1;
			if ( msg_logs[i].time <= 0 )
			{
				msg_logs.Delete(i);
				i -= 1;
				continue;
			}
			msg_logs[i].prev = msg_logs[i].y;
			int targY = i*9;
			if ( targY >= msg_logs[i].y )
			{
				msg_logs[i].y = targY;
				msg_logs[i].prev = targY;
			}
			else
			{
				msg_logs[i].y = msg_logs[i].y + (targY - msg_logs[i].y) * 0.8;
			}
		}
		
		if ( score_time > 0 )
		{
			score_time -= 1;
		}
		
		if ( mScoreInterpolator.GetValue() > score_prev )
		{
			score_time = 35*4;
			int diff = mScoreInterpolator.GetValue() - score_prev;
			score_scale = min(1.0, diff/1000.0);
		}
		
		score_prev = mScoreInterpolator.GetValue();
		
		score_scalePrev = score_scale;
		score_scale *= 0.75;
	}

	override void Draw (int state, double TicFrac)
	{
		Super.Draw (state, TicFrac);
		
		if ( screenblocks >= 11 )
		{
			return;
		}
		
		let player = MetaDoomPlayer(CPlayer.mo);
		if ( !player ) return;
		
		BeginStatusBar();
		
		if ( lowHealthFade > 0.0 )
		{
			let tex_pulse = TexMan.CheckForTexture("graphics/hud_v2/hurtpulse.png");
			screen.DrawTexture(tex_pulse, false, 0, 0,
				DTA_Alpha, lowHealthFade,
				DTA_DestWidth, Screen.GetWidth(), DTA_DestHeight, Screen.GetHeight());
		}
		
		int y = 170;
		
		let tex = TexMan.CheckForTexture("graphics/hud_v2/hud_main.png");
		screen.DrawTexture(tex, false, -x_off, 0,
			DTA_SrcWidth, 124, DTA_DestWidth, 124,
			DTA_320x200, true
			);
		screen.DrawTexture(tex, false, 320+x_off-110, 0,
			DTA_SrcX, 320-110,
			DTA_SrcWidth, 110, DTA_DestWidth, 110,
			DTA_320x200, true
			);
		screen.DrawTexture(tex, false, 160-32, 0,
			DTA_SrcX, 160-32,
			DTA_SrcWidth, 64, DTA_DestWidth, 64,
			DTA_320x200, true
			);
			
		DrawFaceBox();
		DrawVitals();
		
		int x_right = 320 + x_off - 110;
		int x_left = -x_off;
		
		DrawItemBox(x_left, y);
		DrawKeys(x_left, y);
		DrawScore(x_left, y);
		DrawAmmo(x_right, y);
		DrawReserve(x_right, y);
		
		for ( int i = 0; i < msg_logs.Size(); i++ )
		{
			double alpha = msg_logs[i].time <= 35 ? msg_logs[i].time/35. : 1.0;
			double y = msg_logs[i].prev + (msg_logs[i].y - msg_logs[i].prev) * ticFrac;
			DrawString(mSmallFont, msg_logs[i].text, (x_left+2, 2+floor(y)), DI_ITEM_OFFSETS|DI_TEXT_ALIGN_LEFT, alpha: alpha);
		}
		
		if ( score_time > 0 || automapactive )
		{
			double scalar = score_scalePrev + (score_scale - score_scalePrev) * TicFrac;
			double alpha;
			if ( automapactive )
			{
				alpha = 1.0;
			}
			else
			{
				alpha = score_time <= 35 ? score_time/35. : 1.0;
			}
			int yoff = (score_time >= (4*35)) ? (level.maptime % 2) : 0;
			double flashbert = (level.maptime % 12) / 5.;
			DrawString(mSmallFont, ""..mScoreInterpolator.GetValue(), (320+x_off-4, 2-yoff), DI_ITEM_OFFSETS|DI_TEXT_ALIGN_RIGHT, Font.CR_WHITE, alpha: alpha, scale: (1.0+scalar,1.0+scalar));
			if ( score_time >= 4*35 )
			{
				DrawString(mSmallFont, ""..mScoreInterpolator.GetValue(), (320+x_off-4, 2-yoff), DI_ITEM_OFFSETS|DI_TEXT_ALIGN_RIGHT, Font.FindFontColor("MetaWhite"), alpha: flashbert*0.25, scale: (1.0+scalar,1.0+scalar));
			}
		}
		
		if (isInventoryBarVisible())
		{
			DrawInventoryBar(diparms, (160, 168), 6);
		}
		
		let meleeWeapon = MetaDoomMeleeWeapon(player.weaponSave[1]);
		if ( meleeWeapon )
		{
			DrawString(mAmountFont, ""..meleeWeapon.charges, (x_left+103, y+11), DI_ITEM_OFFSETS|DI_TEXT_ALIGN_RIGHT, Font.CR_WHITE);
			//DrawString(mSmallFont, ""..(100*meleeWeapon.GetChargePercent()).."%", (64, 72), DI_ITEM_OFFSETS|DI_TEXT_ALIGN_LEFT, Font.CR_GOLD);
			DrawBar("graphics/hud_v2/bar_meleebar.png", "", meleeWeapon.charges == meleeWeapon.maxCharges ? meleeWeapon.chargeTime : meleeWeapon.GetChargePercent()*meleeWeapon.chargeTime, meleeWeapon.chargeTime, (x_left+106, y+2), 0, SHADER_VERT|SHADER_REVERSE, DI_ITEM_OFFSETS);
		}
		
		/*if (state == HUD_StatusBar)
		{
			BeginStatusBar();
			DrawMainBar (TicFrac);
		} else if (state == HUD_Fullscreen)	{
			BeginStatusBar();
			DrawMainBar (TicFrac);
		} else if (state == HUD_AltHud) {
			BeginStatusBar();
			DrawAltBar (TicFrac);
		}*/
	}

	/*protected void DrawMainBar (double TicFrac)
	{
		if (!CheckInventory("DisableHUD", 1))
		{
			// Everything's a seperate method for sanity's sake.
			// This made sense at the time, I assure you.
			DrawScore();
			DrawHealth();
			DrawArmor();
			DrawKeys();
			DrawAmmo();
			DrawReserve();
			DrawStats();
			DrawFaceBox();
			DrawItemBox();
			DrawPowerupBars();
		}
	}*/
	
	override void DrawAutomapHUD(double ticFrac)
	{
		// game needs to be checked here, so that SBARINFO also gets the correct colors.
		DrawString(mSmallFont, level.FormatMapName(0), (160, 200-32-8), DI_ITEM_OFFSETS|DI_TEXT_ALIGN_CENTER);
		
		DrawString(mSmallFont, level.TimeFormatted(), ((320+x_off)-4, 2+9), DI_ITEM_OFFSETS|DI_TEXT_ALIGN_RIGHT);
		
		DrawString(mSmallFont, String.Format("Kills: %d/%d", level.killed_monsters, level.total_monsters), ((-x_off)+2, 2), DI_ITEM_OFFSETS|DI_TEXT_ALIGN_LEFT);
		DrawString(mSmallFont, String.Format("Items: %d/%d", level.found_items, level.total_items), ((-x_off)+2, 2+9), DI_ITEM_OFFSETS|DI_TEXT_ALIGN_LEFT);
		DrawString(mSmallFont, String.Format("Secrets: %d/%d", level.found_secrets, level.total_secrets), ((-x_off)+2, 2+18), DI_ITEM_OFFSETS|DI_TEXT_ALIGN_LEFT);
	}

	// Extremely cut down version of the HUD for weirdo althud-havers
	protected void DrawAltBar (double TicFrac)
	{
		if (!CheckInventory("DisableHUD", 1))
		{
			DrawPowerupBars();
		}
	}
	
	void DrawScore(int x, int y)
	{
		// Draw frags in Deathmatch, score if not.
		/*if (deathmatch || teamplay)
		{
			DrawImage("FGICON", (27, 171), DI_ITEM_OFFSETS);
			DrawString(mSmallFont2, FormatNumber(CPlayer.FragCount, 3), (89, 172), DI_ITEM_OFFSETS|DI_TEXT_ALIGN_RIGHT, Font.CR_RED);
		} else {
		}*/
	}
	
	void DrawVitals()
	{
		DrawImage("HPICON", (126, 189), DI_ITEM_OFFSETS);
		DrawImage("APICON", (186, 189), DI_ITEM_OFFSETS);
		DrawString(mSmallFont2, ""..CPlayer.health, (124, 190), DI_ITEM_OFFSETS|DI_TEXT_ALIGN_RIGHT, Font.CR_WHITE);
		DrawString(mSmallFont2, ""..GetArmorAmount(), (194, 190), DI_ITEM_OFFSETS|DI_TEXT_ALIGN_LEFT, Font.CR_WHITE);
		/*DrawImage("HUDBAR", (36, 189), DI_ITEM_OFFSETS);*/
		DrawBar("graphics/hud_v2/bar_lifebar.png", "", mHealthInterpolator.GetValue(), CPlayer.mo.GetMaxHealth(false), (137, 172), 0, SHADER_VERT|SHADER_REVERSE, DI_ITEM_OFFSETS);
		if ( mHealthInterpolator.GetValue() > 100 )
		{
			DrawBar("graphics/hud_v2/bar_lifebar2.png", "", mHealthInterpolator.GetValue()-100, CPlayer.mo.GetMaxHealth(true), (137, 172), 0, SHADER_VERT|SHADER_REVERSE, DI_ITEM_OFFSETS);
		}
		DrawBar("graphics/hud_v2/bar_armorbar.png", "", mArmorInterpolator.GetValue(), 100, (178, 172), 0, SHADER_VERT|SHADER_REVERSE, DI_ITEM_OFFSETS);
		if ( mArmorInterpolator.GetValue() > 100 )
		{
			DrawBar("graphics/hud_v2/bar_armorbar2.png", "", mArmorInterpolator.GetValue()-100, 100, (178, 172), 0, SHADER_VERT|SHADER_REVERSE, DI_ITEM_OFFSETS);
		}
		/*if (mHealthInterpolator.GetValue() > 100)
		{
			DrawBar("LIFEBAR2", "MTBAR3", mHealthInterpolator.GetValue() - 100, CPlayer.mo.GetMaxHealth(true),
			(37, 190), 0, SHADER_HORZ, DI_ITEM_OFFSETS);
		}
		
		// special powerup timer for invuln sphere
		if (CheckInventory("PowerMetaInvulnerable", 1))
		{
			int itemTimeLeft, itemDuration;
			[itemTimeLeft,itemDuration] = CPlayer.mo.GetEffectTicsForItem("MetaInvulnerabilitySphere");
			
			DrawImage("POWRINV", (26, 188), DI_ITEM_OFFSETS);			
			DrawBar("POWRBAR", "MTBAR3", itemTimeLeft, itemDuration, (37, 190), 0, SHADER_HORZ, DI_ITEM_OFFSETS);
		}*/
	}
	
	void DrawArmor()
	{
		if (GetArmorSavePercent() == 50)
		{
			DrawImage("AP2ICON", (27, 180), DI_ITEM_OFFSETS);
		} else {
			DrawImage("APICON", (27, 180), DI_ITEM_OFFSETS);
		}
		DrawString(mSmallFont2, FormatNumber(GetArmorAmount(), 3), (24, 180), DI_ITEM_OFFSETS|DI_TEXT_ALIGN_RIGHT, Font.CR_WHITE);
		
		DrawImage("HUDBAR", (36, 180), DI_ITEM_OFFSETS);
		DrawBar("ARMRBAR", "MTBAR", mArmorInterpolator.GetValue(), 100, (37, 181), 0, SHADER_HORZ, DI_ITEM_OFFSETS);
		if (mArmorInterpolator.GetValue() > 100)
		{
			DrawBar("ARMRBAR2", "MTBAR3", (mArmorInterpolator.GetValue() - 100), 100, (37, 181), 0, SHADER_HORZ, DI_ITEM_OFFSETS);
		}
	}
	
	void DrawKeys(int x, int y)
	{
		int kX = 44;
		int kY = 21;
		
		bool locks[6];
		String icon;
		
		for ( int i = 0; i < 6; i++ )
		{
			bool gotKey = CPlayer.mo.CheckKeys(i + 1, false, true);
			if ( !gotKey ) continue;
			switch (i)
			{
				case 0: icon = "graphics/hud_v2/keys/key_redcard.png"; break;
				case 1: icon = "graphics/hud_v2/keys/key_bluecard.png"; break;
				case 2: icon = "graphics/hud_v2/keys/key_yellowcard.png"; break;
				case 3: icon = "graphics/hud_v2/keys/key_redskull.png"; break;
				case 4: icon = "graphics/hud_v2/keys/key_blueskull.png"; break;
				case 5: icon = "graphics/hud_v2/keys/key_yellowskull.png"; break;
			}
			DrawImage(icon, (x+kX, y+kY), DI_ITEM_OFFSETS);
			kX += 6;
		}
	}
	
	void DrawAmmo (int x, int y)
	{
		string ammoIcon = "AMICON";
		if (CPlayer.ReadyWeapon != null)
		{
			if (CheckWeaponSelected("MetaPistol") && meta_pistolammo == 0)
			{
				ammoIcon = "AMICNBAT";
			} else if (CPlayer.ReadyWeapon.Ammo1 is "Shell")
			{
				ammoIcon = "AMICNSHL";
			} else if (CPlayer.ReadyWeapon.Ammo1 is "RocketAmmo")
			{
				ammoIcon = "AMICNRCK";
			} else if (CPlayer.ReadyWeapon.Ammo1 is "Cell")
			{
				ammoIcon = "AMICNPLS";
			} else if (CPlayer.ReadyWeapon.Ammo1 is "HolyWater")
			{
				ammoIcon = "AMICNWAT";
			} else if (CPlayer.ReadyWeapon.Ammo1 is "HalonCannister")
			{
				ammoIcon = "AMICNEXT";
			} else if (CPlayer.ReadyWeapon.Ammo1 is "BFGAmmo")
			{
				ammoIcon = "AMICNBFG";
			} else if (CPlayer.ReadyWeapon.Ammo1 is "SoulAmmo")
			{
				ammoIcon = "AMICNSOL";
			}/* else if (CPlayer.ReadyWeapon.Ammo1 is "DogGunHealth")
			{
				DrawImage("HPICON", (283, 180), DI_ITEM_OFFSETS);
			} else {
				DrawImage("AMICON", (283, 180), DI_ITEM_OFFSETS);
			}*/
		}
		DrawImage(ammoIcon, (x+2, y+8), DI_ITEM_OFFSETS);
		
		//DrawImage("HUDBAR", (225, 180), DI_ITEM_OFFSETS);
		
		// Draw current ammo amounts
		Ammo ammo1, ammo2;
		int ammomax;
		int ammocount1, ammocount2;
		[ammo1, ammo2, ammocount1, ammocount2] = GetCurrentAmmo();
		
		// Get the maximum ammo of the current weapon, but WITHOUT crashing
		if (ammo1 != NULL)
		{ ammomax = CPlayer.ReadyWeapon.Ammo1.MaxAmount; }
		
		string ammoReadout = ammo1 ? FormatNumber(ammocount1, 3) : "---";
		DrawString(mSmallFont2, ammoReadout, (x+34, y+9), DI_ITEM_OFFSETS|DI_TEXT_ALIGN_RIGHT, Font.CR_WHITE);
		
			/*if (meta_pistolammo == 1 && CheckWeaponSelected("MetaPistol"))
			{
				DrawString(mSmallFont2, FormatNumber(GetAmount("Clip"), 3), (295, 180), DI_ITEM_OFFSETS|DI_TEXT_ALIGN_LEFT, Font.CR_WHITE);
			} else {
				DrawString(mSmallFont2, "---", (295, 180), DI_ITEM_OFFSETS|DI_TEXT_ALIGN_LEFT, Font.CR_WHITE);
			}*/
		DrawBar("graphics/hud_v2/bar_ammobar.png", "graphics/hud_v2/bar_horzbg.png", mAmmoInterpolator.GetValue(), ammomax, (x+36, y+9), 0, SHADER_REVERSE, DI_ITEM_OFFSETS);
		
		int slotX = 85-(7*8);
		int slotY = 0;
		bool found;
		int slot, index;
		if ( CPlayer.ReadyWeapon )
		{
			[found, slot, index] = CPlayer.weapons.LocateWeapon(CPlayer.ReadyWeapon.GetClass());
		}
		
		for ( int i = 0; i <= 7; i++ )
		{
			bool hasInSlot = CPlayer.HasWeaponsInSlot(i+1);
			int textColor = Font.FindFontColor("MetaHudDark");
			if ( i == slot-1 )
			{
				textColor = Font.CR_UNTRANSLATED;
				let tex = TexMan.CheckForTexture("graphics/hud_v2/hud_main.png");
				screen.DrawTexture(tex, false, x+slotX-2, y,
					DTA_SrcX, 201, DTA_SrcY, 170,
					DTA_SrcWidth, 7, DTA_SrcHeight, 8,
					DTA_DestWidth, 7, DTA_DestHeight, 8,
					DTA_320x200, true
					);
			}
			else if ( hasInSlot )
			{
				textColor = Font.FindFontColor("MetaHudGray");
			}
			DrawString(mIndexFont, ""..(i+1), (x+slotX, y+1), DI_TEXT_ALIGN_LEFT|DI_NOSHADOW, textColor);
			slotX += 7;
		}
	}
	
	void DrawReserve (int x, int y)
	{
		/*if (screenblocks < 11 || automapactive)
		{
			DrawImage("HUDAMMO", (225, 170), DI_ITEM_OFFSETS);
		} else {
			DrawImage("HUDAMMO2", (225, 170), DI_ITEM_OFFSETS);
		}*/
		//DrawImage("HUDAMMO", (225, 170), DI_ITEM_OFFSETS);
		DrawString(mIndexFont, FormatNumber(GetAmount("Clip"), 3), (x+20, y+21), DI_TEXT_ALIGN_RIGHT);
		DrawString(mIndexFont, FormatNumber(GetAmount("Shell"), 3), (x+41, y+21), DI_TEXT_ALIGN_RIGHT);
		DrawString(mIndexFont, FormatNumber(GetAmount("RocketAmmo"), 3), (x+62, y+21), DI_TEXT_ALIGN_RIGHT);
		DrawString(mIndexFont, FormatNumber(GetAmount("Cell"), 3), (x+83, y+21), DI_TEXT_ALIGN_RIGHT);
		
		DrawString(mIndexFont, FormatNumber(GetAmount("SoulAmmo"), 3), (x+104, y+11), DI_TEXT_ALIGN_RIGHT);
		DrawString(mIndexFont, FormatNumber(GetAmount("BFGAmmo"), 3), (x+104, y+2), DI_TEXT_ALIGN_RIGHT);
	}
	
	void DrawStats()
	{
		if (screenblocks < 11 || automapactive)
		{
			DrawImage("HUDSTAT", (94, 169), DI_ITEM_OFFSETS);
		} else {
			DrawImage("HUDSTAT2", (94, 169), DI_ITEM_OFFSETS);
		}
		
		DrawString(mIndexFont, FormatNumber(level.killed_monsters, 3), (119, 171), DI_TEXT_ALIGN_RIGHT);
		DrawString(mIndexFont, FormatNumber(level.total_monsters, 3), (138, 171), DI_TEXT_ALIGN_RIGHT);
		
		DrawString(mIndexFont, FormatNumber(level.found_items, 3), (119, 181), DI_TEXT_ALIGN_RIGHT);
		DrawString(mIndexFont, FormatNumber(level.total_items, 3), (138, 181), DI_TEXT_ALIGN_RIGHT);
		
		DrawString(mIndexFont, FormatNumber(level.found_secrets, 3), (119, 191), DI_TEXT_ALIGN_RIGHT);
		DrawString(mIndexFont, FormatNumber(level.total_secrets, 3), (138, 191), DI_TEXT_ALIGN_RIGHT);
	}
	
	void DrawFaceBox()
	{
		DrawImage("graphics/hud_v2/hud_facebg.png", (144, 170), DI_ITEM_OFFSETS);
		
		string faceTex = "";
		int flags = MugShot.ANIMATEDGODMODE|Mugshot.XDEATHFACE;
		switch ( CPlayer.GetGender() )
		{
			case GENDER_FEMALE:
				faceTex = "SFF";
				flags = flags|MugShot.CUSTOM;
				break;
			case GENDER_NEUTRAL:
			case GENDER_OTHER:
				faceTex = "STC";
				flags = flags|MugShot.CUSTOM;
				break;
		}
		
		DrawTexture(GetMugShot(5, flags, faceTex), (143, 167), DI_ITEM_OFFSETS);
	}
	
	void DrawItemBox (int x, int y)
	{
		let player = MetaDoomPlayer(CPlayer.mo);
		
		if ( !player ) return;
		
		let item1 = MetaEquipmentBase(CPlayer.mo.InvSel);
		let item2 = MetaEquipmentBase(player.invSlot_backup);
		
		if ( item1 )
		{
			int amount, max;
			[amount, max] = item1.GetCooldownVals();
			
			bool isFull = amount == max;
			DrawInventoryIcon(CPlayer.mo.InvSel, (x+19, y+14), DI_ITEM_CENTER, isFull ? 1.0 : 0.5);
			DrawBar("graphics/hud_v2/bar_invbar.png", "", isFull ? max : amount, max, (x+34, y+2), 0, SHADER_VERT|SHADER_REVERSE, DI_ITEM_OFFSETS);
		}
		if ( item2 )
		{
			int amount, max;
			[amount, max] = item2.GetCooldownVals();
			
			bool isFull = amount == max;
			DrawInventoryIcon(item2, (x+51, y+9), DI_ITEM_CENTER, isFull ? 1.0 : 0.5, scale: (0.5, 0.5));
			DrawBar("graphics/hud_v2/bar_invbar2.png", "", isFull ? max : amount, max, (x+61, y+2), 0, SHADER_VERT|SHADER_REVERSE, DI_ITEM_OFFSETS);
		}
		// Handle drawing inventory items and the cooldown timer.
		/*if (CPlayer.mo.InvSel != null && !level.NoInventoryBar)
		{
			static const string invItem[] =
			{
				"HandGrenade",
				"DogCollar",
				"Hologram",
				"KineticMine",
				"ShieldWall",
				"SiphonGrenade",
				"TeslaRocket",
				"Artifact",
				"FlameBelch"
			};

			static const string invCooldownCounter[] =
			{
				"InventoryFuel_HandGrenade",
				"InventoryFuel_DogCollar",
				"InventoryFuel_Hologram",
				"InventoryFuel_KineticMine",
				"InventoryFuel_ShieldWall",
				"InventoryFuel_SiphonGrenade",
				"InventoryFuel_TeslaRocket",
				"InventoryFuel_TheArtifact",
				"InventoryFuel_FlameBelch"
			};

			static const int invCooldownCap[] =
			{
				INV_COOLDOWN_GENERIC,
				INV_COOLDOWN_GENERIC,
				INV_COOLDOWN_HOLOGRAM,
				INV_COOLDOWN_GENERIC,
				INV_COOLDOWN_SHIELD,
				INV_COOLDOWN_SIPHON,
				INV_COOLDOWN_SIPHON,
				INV_COOLDOWN_ARTIFACT,
				INV_COOLDOWN_GENERIC
			};
			
			for(int i = 0; i < invItem.size(); i++)
			{
				// Draw the cooldown timers for the selected item.
				if ( !(CPlayer.mo.InvSel is invItem[i]) ) continue;
				
				//DrawBar("COOLBAR1", "COOLBAR0", GetAmount(invCooldownCounter[i]),
				//invCooldownCap[i], (185, 169), 0, SHADER_VERT|SHADER_REVERSE, DI_ITEM_OFFSETS);
				bool isFull = GetAmount(invCooldownCounter[i]) == invCooldownCap[i];
				DrawBar("graphics/hud_v2/bar_invbar.png", "graphics/hud_v2/bar_vert.png", isFull ? invCooldownCap[i] : GetAmount(invCooldownCounter[i]), invCooldownCap[i], (x+34, y+2), 0, SHADER_VERT|SHADER_REVERSE, DI_ITEM_OFFSETS);
				
				// Render the icon half-transparent (greyed out) if we're still
				// under cooldown and unable to spam Cyberdemons to death with
				// Siphon Grenades. Yeah, I know you.
				if (CPlayer.mo.InvSel is invItem[i] && GetAmount(invCooldownCounter[i]) < invCooldownCap[i])
				{
					DrawInventoryIcon(CPlayer.mo.InvSel, (185, 168), DI_ITEM_OFFSETS, 0.5);
				} else if (CPlayer.mo.InvSel is invItem[i] && GetAmount(invCooldownCounter[i]) >= invCooldownCap[i]){
					DrawInventoryIcon(CPlayer.mo.InvSel, (185, 168), DI_ITEM_OFFSETS);
				} else {
					// original inventory item handling, for demon key cheat and non-metadoom inventory items
					DrawInventoryIcon(CPlayer.mo.InvSel, (185, 168), DI_ITEM_OFFSETS);
					if (CPlayer.mo.InvSel.Amount > 1)
					{
						DrawString(mAmountFont, FormatNumber(CPlayer.mo.InvSel.Amount), (219, 199-mIndexFont.mFont.GetHeight()), DI_TEXT_ALIGN_RIGHT, Font.CR_GOLD);
					}
				}
			}
		}*/
	}
	
	// This is redefined with some minor tweaks to a single line I'll mark down below
	// so as to better position the inventory cursor. Wasteful, huh.
	void DrawInventoryBar(InventoryBarState parms, Vector2 position, int numfields, int flags = 0, double bgalpha = 1.)
	{
		double width = parms.boxsize.X * numfields;
		//[position, flags] = AdjustPosition(position, flags, width, parms.boxsize.Y);
		position.x -= 28*3;
		
		CPlayer.mo.InvFirst = ValidateInvFirst(numfields);
		if (CPlayer.mo.InvFirst == null) return;	// Player has no listed inventory items.
		
		Vector2 boxsize = parms.boxsize;
		// First draw all the boxes
		let tex = TexMan.CheckForTexture("graphics/hud_v2/hud_main.png");
		for( int i = 0; i < numfields; i++ )
		{
			screen.DrawTexture(tex, false, position.x+28*i, 170,
				DTA_SrcX, 5, DTA_SrcY, 170,
				DTA_SrcWidth, 28, DTA_SrcHeight, 28,
				DTA_DestWidth, 28, DTA_DestHeight, 28,
				DTA_320x200, true);
			//DrawTexture(parms.box, position + (boxsize.X * i, 0), flags | DI_ITEM_LEFT_TOP, bgalpha);
		}
		
		// now the items and the rest
		
		Vector2 itempos = position + boxsize / 2;
		Vector2 textpos = position + boxsize - (1, 1 + parms.amountfont.mFont.GetHeight());

		int i = 0;
		Inventory item;
		for(item = CPlayer.mo.InvFirst; item != NULL && i < numfields; item = item.NextInv())
		{
			/*for(int j = 0; j < 2; j++)
			{
				if (j ^ !!(flags & DI_DRAWCURSORFIRST))
				{
					if (item == CPlayer.mo.InvSel)
					{
						double flashAlpha = bgalpha;
						if (flags & DI_ARTIFLASH) flashAlpha *= itemflashFade;
						// This is the one line I changed. Cool.
						DrawTexture(parms.selector, (28*i, 170), flags | DI_ITEM_LEFT_TOP, flashAlpha);
					}
				}
				else
				{*/
			if (item == CPlayer.mo.InvSel)
			{
				DrawTexture(parms.selector, (position.x+28*i, 170) + (14, 14), flags | DI_ITEM_CENTER, 1.0);
			}
			DrawInventoryIcon(item, (position.x+28*i, 170) + (14, 14), flags | DI_ITEM_CENTER, scale: (0.9, 0.9));
			/*	}
			}*/
			
			if (parms.amountfont != null && (item.Amount > 1 || (flags & DI_ALWAYSSHOWCOUNTERS)))
			{
				DrawString(parms.amountfont, FormatNumber(item.Amount, 0, 5), textpos + (boxsize.X * i, 0), flags | DI_TEXT_ALIGN_RIGHT, parms.cr, parms.itemalpha);
			}
			i++;
		}
		/*// Is there something to the left?
		if (CPlayer.mo.FirstInv() != CPlayer.mo.InvFirst)
		{
			DrawTexture(parms.left, position + (-parms.arrowoffset.X, parms.arrowoffset.Y), flags | DI_ITEM_RIGHT|DI_ITEM_VCENTER);
		}
		// Is there something to the right?
		if (item != NULL)
		{
			DrawTexture(parms.right, position + parms.arrowoffset + (width, 0), flags | DI_ITEM_LEFT|DI_ITEM_VCENTER);
		}*/
	}
	
	// THIS IS ALL A NIGHTMARE. I HAVE NO IDEA WHAT ANY OF THIS DOES. IF YOU
	// WANT TO KNOW WHAT ANY OF THIS IS, ASK THEZOMBIEKILLER AND/OR DRPYSPY.
	void DrawPowerupBars()
	{
		if(!CPlayer.mo) return;

		int iterator   = 0;
		int totalWidth = 0;

		let barTexture = TexMan.CheckForTexture("POWRBAR", TexMan.Type_Any);
		int barWidth, barHeight; [barWidth, barHeight] = TexMan.GetSize(barTexture);

		for(int i = 0; i < barArraySize; i++)
		{
			string powerupClass = powerupStuff[barArrayColumns * i + 0];

			int timeLeft, duration;
			[timeLeft, duration] = CPlayer.mo.GetEffectTicsForItem(powerupClass);

			if(duration <= -1) continue;

			string powerupImage = powerupStuff[barArrayColumns * i + 1];
			let powerupTexture  = TexMan.CheckForTexture(powerupImage, TexMan.Type_Any);

			int width, height; [width, height] = TexMan.GetSize(powerupTexture);

			totalWidth += width + barWidth;
		}

		for(int i = 0; i < barArraySize; i++)
		{
			string powerupClass = powerupStuff[barArrayColumns * i + 0];

			int timeLeft, duration;
			[timeLeft, duration] = CPlayer.mo.GetEffectTicsForItem(powerupClass);

			if(duration <= -1) continue;

			string powerupImage = powerupStuff[barArrayColumns * i + 1];
			let powerupTexture  = TexMan.CheckForTexture(powerupImage, TexMan.Type_Any);

			int width, height; [width, height] = TexMan.GetSize(powerupTexture);

			int distance = 5;
			let origin   = (160 - totalWidth / 2, 0);
			let pos      = origin + ((barWidth + width + distance) * iterator, 165);
			int flags    = /*DI_SCREEN_HCENTER |*/ DI_ITEM_LEFT;

			DrawImage(powerupImage, pos - (width + 1, 0), flags);
			DrawImage("HUDBAR", pos, flags);
			DrawBar("POWRBAR", "MTBAR", timeLeft, duration, pos + (1, -1), 0, SHADER_HORZ, flags);

			iterator++;
		}
	}
}	