/*
----------------------------
MetaDoom
Actor Definitions
Flame Belch
----------------------------
*/

// Seperate GFX for Codex
class FlameBelchDummy : Actor
{
	States
	{
	Spawn:
		FBLC Y -1;
		loop;
	}
}

class FlameBelchPickup : CustomInventory
{
	Default
	{
		inventory.pickupmessage "$GOTFLAMEBELCH";
		Tag "$TAGFLAMEBELCH";
		inventory.icon "INVBLCH";
		inventory.pickupsound "inventory/flamebelch/get";
		+INVENTORY.ALWAYSPICKUP;
		+BLOCKASPLAYER;
		//$Category "MetaDoom Inventory Items"
		//$Title "Flame Belch"
		//$NotAngled
		//$Color 9
	}
	
	states
	{
	Spawn:
		FBLC Z -1;
		stop;
	Pickup:
		TNT1 A 0 
		{
			A_GiveInventory ("FlameBelch", 1);
			A_GiveInventory("InventoryFuel_FlameBelch", INV_COOLDOWN_GENERIC);
		}
		stop;
	}
}

Extend Class MetaDoomWeapon
{
	States
	{
		Overlay.FlameBelch:
			FBLC A 1 A_OverlayOffset(PSP_METAINV, -128, -64);
			FBLC A 1 A_OverlayOffset(PSP_METAINV, -64, -32, WOF_INTERPOLATE);
			FBLC A 1 A_OverlayOffset(PSP_METAINV, -32, -16, WOF_INTERPOLATE);
			FBLC A 1 A_OverlayOffset(PSP_METAINV, -16, -8, WOF_INTERPOLATE);
			FBLC A 1 A_OverlayOffset(PSP_METAINV, -8, -4, WOF_INTERPOLATE);
			FBLC A 1 A_OverlayOffset(PSP_METAINV, -4, -2, WOF_INTERPOLATE);
			FBLC A 1 A_OverlayOffset(PSP_METAINV, -2, -1, WOF_INTERPOLATE);
			FBLC A 1 A_OverlayOffset(PSP_METAINV, -1, -0.5, WOF_INTERPOLATE);
			FBLC A 24 A_OverlayOffset(PSP_METAINV, 0, 0, WOF_INTERPOLATE);
			FBLC A 1 A_OverlayOffset(PSP_METAINV, -1, -0.5, WOF_INTERPOLATE);
			FBLC A 1 A_OverlayOffset(PSP_METAINV, -2, -1, WOF_INTERPOLATE);
			FBLC A 1 A_OverlayOffset(PSP_METAINV, -4, -2, WOF_INTERPOLATE);
			FBLC A 1 A_OverlayOffset(PSP_METAINV, -8, -4, WOF_INTERPOLATE);
			FBLC A 1 A_OverlayOffset(PSP_METAINV, -16, -8, WOF_INTERPOLATE);
			FBLC A 1 A_OverlayOffset(PSP_METAINV, -32, -16, WOF_INTERPOLATE);
			FBLC A 1 A_OverlayOffset(PSP_METAINV, -64, -32, WOF_INTERPOLATE);
			FBLC A 1 A_OverlayOffset(PSP_METAINV, -128, -64, WOF_INTERPOLATE);
			Stop;
	}
}

class FlameBelch : MetaEquipmentBase
{
	Default
	{
		inventory.pickupmessage "$GOTFLAMEBELCH";
		Tag "$TAGFLAMEBELCH";
		inventory.icon "INVBLCH";
		inventory.pickupsound "inventory/flamebelch/get";
		inventory.amount 1;
		inventory.maxamount 1;
		+INVENTORY.INVBAR
		scale 0.5;
		
		MetaEquipmentBase.CooldownTime INV_COOLDOWN_GENERIC;
	}
	
	override void UseEquipment()
	{
		ThrowProjectile("FlameBelchAttack", 0);
		let def = GetDefaultByType("MetaDoomWeapon");
		let psp = owner.player.GetPSprite(PSP_METAINV);
		psp.SetState(def.resolveState("Overlay.FlameBelch"));
		psp.bAddBob = false;
		psp.bAddWeapon = false;
		//psp.y = -32;
	}
}

// Based on "FlashlightInterpBug.pk3" by DrPySpy
Class FlameBelchAttack : Actor
{
	Default
	{
		-NOGRAVITY
		-INVISIBLE
		RenderRadius 512;
	}
	
	override void Tick()
	{
        A_Warp(AAPTR_TARGET,0,0,48,0,WARPF_NOCHECKPOSITION|WARPF_INTERPOLATE|WARPF_COPYPITCH);
		Super.Tick();  
	}
	
	action void A_BelchFlame()
	{
		let target = PlayerPawn(target);
		if ( !target ) return;
		Quat base = Quat.FromAngles(target.angle, target.pitch, target.roll);
		Vector3 spawnPos = (target.pos.x, target.pos.y, target.player.viewz);
		Vector3 offset = (0, 11, 7);
		spawnPos += base * offset;
		let fire = Spawn("FlameBelchFire", spawnPos);
		if ( fire )
		{
			fire.target = target;
			fire.Vel3DFromAngle(fire.speed, angle-2, pitch+3.5);
		}
	}
	
	States
	{
		Spawn:
			TNT1 A 0 NoDelay
			{
				target.A_StartSound("inventory/flamebelch/fire", 451, 0, 1.0, ATTN_NORM, 1.0);
			}
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 1 
			{
				target.A_AlertMonsters();
				A_BelchFlame();
			}
			Stop;
	}
}

// Imported from Reelism 2, which was imported from FauxDM...
Class FlameBelchFire : Actor
{
	Default
	{
		Radius 10;
		Height 10;
		Projectile;
		
		DamageFunction 5*random(1,3);
		DamageType "BelchFire";
		
		Scale 0.03;
		
		Speed 20;
		RenderStyle "ColorAdd";
		Obituary "$OB_FLAMEBELCH";
		
		+FORCEXYBILLBOARD
		+DONTSPLASH
		+ROLLSPRITE
		+ROLLCENTER
	}
	
	int dir;
	int dottimer;
	bool fadeOut;
	
	States
	{
		Spawn:
			FTHR A 0 NoDelay
			{
				self.vel.xy += target.vel.xy;
				scale *= frandom(0.95,1.05);
			}
		SpawnLoop:
			FTHR A 0
			{
				dir = random(0,1) ? 1 : -1;
				roll = random(0,360);
			}
			goto Start;
		Start:
			FTHR AAAAAAAA 1 BRIGHT
			{
				roll += 4*dir;
				
				A_SetScale(scale.x + 0.1);
				vel *= 0.96;
				//vel.z += 0.025;
			}
			goto Looper;
		Looper:
			FTHR ABCDEFGHIJKLMNOP 1 BRIGHT
			{
				fadeOut = true;
			}
			Stop;
		Death:
			Stop;
		XDeath:
			Stop;
	}
	
	override void Tick()
	{
		Super.Tick();
		
		roll += 4*dir;
		
		if ( fadeOut )
		{
			A_SetScale(scale.x + 0.05);
			vel *= 0.96;
		}
		
		dottimer++;
		
		if (dottimer >= 6)
		{
			A_SpawnParticle("ffff9c", SPF_FULLBRIGHT, 35, 1, Random(0,255), 0, 0, 0, Random(0,1), Random(0,1), Random(2,6), 0, 0, 0, 1.0, -1, 0.3);
			dottimer = 0;
		}
		
		if (waterlevel > 0 || (pos.z == GetZAt() && (GetFloorTerrain().TerrainName == "Water" || GetFloorTerrain().TerrainName == "FakeWater")))
		{
			A_StartSound("inventory/flamebelch/sizzle");
			A_SpawnItem("MetaExtinguishSmokeGenerator");
			self.Destroy();
		}
	}
	
	override int SpecialMissileHit(Actor victim)
	{
		if ( victim == target ) return 1;
		if ( !victim.bSHOOTABLE ) return 1;
		if ( victim.health <= 0 ) return 1;
		
		victim.GiveInventory("MetaFlameBelch_DOT", 1);
		
		return -1;
	}
}

Class MetaFlameBelch_DOT : Inventory
{
	Actor causer;
	int timer;
	
	// If on fire, spawn some Armor
	// Based on Shadsy's Mega Imp code from Reelism 2
	override void ModifyDamage(int damage, Name damageType, out int newdamage, bool passive, Actor inflictor, Actor source, int flags)
	{
		int twiddle;
		bool willKill = (owner.health - damage) <= 0;
		
		if ( willKill )
		{
			twiddle = GetSpawnHealth() / 25;
			
			if (twiddle < 4)
			{
				twiddle = 4;
			} else if (twiddle > 12)
			{
				twiddle = 12;
			}
		}
		else
		{
			if (damage >= 100)
			{
				twiddle = 8;
			} else {
				twiddle = (damage / 25);
			}
		}
		
		for (int i = 0; i < 1+ twiddle; i++) 
		{
			owner.A_SpawnItemEx("MetaArmorPinataFade",random(0,radius/2),random(0,radius/2),random(16,height),random(2,8),0,random(4,8),random(0,365),SXF_NOCHECKPOSITION);
		}
	}
	
	override void DoEffect()
	{
		if ( owner.health <= 0 )
		{
			Destroy();
			return;
		}
		
		if ( timer % 3 == 0 )
		{
			owner.DamageMobj(causer, causer, 3, 'BelchFire');
			owner.A_StartSound("inventory/flamebelch/crak", 67+(level.maptime%10), volume: frandom(0.5,0.7), pitch: frandom(0.5,1.0));
		}
		
		let p = Level.SpawnVisualThinker("MetaFlameBelch_Flame");
		if ( p )
		{
			p.pos = owner.pos + (frandom(-radius/2,radius/2),frandom(-radius/2,radius/2),owner.height/2);
		}
		
		timer++;
		
		if ( timer >= 35*3 )
		{
			Destroy();
			return;
		}
	}
}

Class MetaFlameBelch_Flame : VisualThinker
{
	static const string frames[] =
	{
		"FFLAA0",
		"FFLAB0",
		"FFLAC0",
		"FFLAD0",
		"FFLAE0",
		"FFLAF0",
		"FFLAG0",
		"FFLAH0",
		"FFLAI0",
		"FFLAJ0",
		"FFLAK0",
		"FFLAL0",
		"FFLAM0",
		"FFLAN0",
		"FFLAO0",
		"FFLAP0",
		
		"FFLAA0",
		"FFLAB0",
		"FFLAC0",
		"FFLAD0",
		"FFLAE0",
		"FFLAF0",
		"FFLAG0",
		"FFLAH0",
		"FFLAI0",
		"FFLAJ0",
		"FFLAK0",
		"FFLAL0",
		"FFLAM0",
		"FFLAN0",
		"FFLAO0",
		"FFLAP0",
		
		"FFLAQ0",
		"FFLAR0",
		"FFLAS0",
		"FFLAT0",
		"FFLAU0",
		"FFLAV0",
		"FFLAW0",
		"FFLAX0",
		"FFLAY0",
		"FFLAZ0"
	};
	
	int frame;
	int stagger;
	
	override void PostBeginPlay()
	{
		super.PostBeginPlay();
		SetRenderStyle(STYLE_ColorAdd);
		flags = SPF_ROLL|SPF_FULLBRIGHT;
		roll = random(0,360);
		frame = random(0, frames.Size()-1);
		
		texture = TexMan.CheckForTexture(frames[frame]);
	}
	
	override void Tick()
	{
		if ( bDESTROYED )
			return;
	
		super.Tick();
		
		stagger += 1;
		if ( stagger >= 3 )
		{
			frame += 1;
			if ( frame >= frames.Size() )
			{
				Destroy();
				return;
			}
			frame = frame % frames.Size();
			texture = TexMan.CheckForTexture(frames[frame]);
		}
		
		vel.z += 0.1;
		//scolor = Color(fadeOut_red, fadeOut_other, fadeOut_other);
		scale.x -= 0.01;
		scale.y -= 0.01;
	}
}

class MetaGroundFireFlame : Actor
{
	Default
	{
		RenderStyle "Add";
		Alpha 0.9;
		Scale 0.5;
		
		+DONTSPLASH
		+NOINTERACTION
	}
	
	States
	{
		Spawn:
			FFLA ABCDEFGHIJKLMN 2 Bright
			{
				if (waterlevel > 0)
				{
					A_StartSound("inventory/flamebelch/sizzle");
					A_Remove(AAPTR_DEFAULT,RMVF_EVERYTHING);
					A_SpawnItem("MetaExtinguishSmokeGenerator");
				}
			}
			Stop;
	}
	
	override void Tick()
	{
		super.Tick();
		
		if (isFrozen() || level.isFrozen())
			return;
		
		scale.x -= min(0.02, scale.x);
		scale.y -= min(0.02, scale.y);
		
		A_StartSound("inventory/flamebelch/crak",CHAN_BODY,0,(scale.x / 2),ATTN_NORM,frandom(0.1,0.5));
	}
}

class MetaExtinguishSmoke : Actor
{
	Default
	{
		+NOBLOCKMAP
		+NOGRAVITY
		+ALLOWPARTICLES
		+RANDOMIZE
		+ZDOOMTRANS
		+DONTSPLASH
		RenderStyle "Translucent";
		Alpha 0.5;
		VSpeed 1;
		Mass 5;
		Scale 2;
	}
	States
	{
	Spawn:
		PUFF C 1 A_FadeOut(0.01);
		loop;
	}
}

class MetaExtinguishSmokeGenerator : Actor
{
	Default
	{
		+NOGRAVITY
		+DONTSPLASH
	}
	States
	{
	Spawn:
		TNT1 AAAAAAAAAAAAA 1
		{
			// Check to see if the smoke will spawn at roughly the same height
			// as the smoke generator. If it's too high up, re-roll the RNG
			// until you get a position that works.
			
			// This prevents fire from spawning on top of taller adjacent sectors.
			
			bool okfire = false;
			while (okfire == false)
			{
				int randomx = random(-32,32);
				int randomy = random(-32,32);
				if (GetZAt(randomx,randomy) <= GetZAt()+16 && GetZAt(randomx,randomy) >= GetZAt())
				{
					A_SpawnItemEx("MetaExtinguishSmoke", randomx, randomy, 0,0,0,2);
					okfire = true;
				}
			}
		}
		stop;
	}
}